package kap.ksp

import com.google.devtools.ksp.processing.*
import com.google.devtools.ksp.symbol.*
import com.google.devtools.ksp.validate
import java.io.OutputStreamWriter

class KapTypeSafeProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger,
) : SymbolProcessor {

    override fun process(resolver: Resolver): List<KSAnnotated> {
        val symbols = resolver.getSymbolsWithAnnotation("kap.KapTypeSafe")
        val unprocessed = mutableListOf<KSAnnotated>()

        symbols.forEach { symbol ->
            if (!symbol.validate()) {
                unprocessed.add(symbol)
                return@forEach
            }
            if (symbol is KSClassDeclaration && symbol.classKind == ClassKind.CLASS) {
                generateTypeSafeWrappers(symbol)
            } else {
                logger.error("@KapTypeSafe can only be applied to data classes", symbol)
            }
        }

        return unprocessed
    }

    private fun generateTypeSafeWrappers(classDecl: KSClassDeclaration) {
        val className = classDecl.simpleName.asString()
        val packageName = classDecl.packageName.asString()
        val constructor = classDecl.primaryConstructor ?: run {
            logger.error("@KapTypeSafe requires a primary constructor", classDecl)
            return
        }
        val params = constructor.parameters

        if (params.isEmpty()) {
            logger.error("@KapTypeSafe requires at least one constructor parameter", classDecl)
            return
        }

        val qualifiedClassName = if (packageName.isEmpty()) className else "$packageName.$className"
        val hasPackage = packageName.isNotEmpty()

        val file = codeGenerator.createNewFile(
            Dependencies(true, classDecl.containingFile!!),
            packageName,
            "${className}KapTypeSafe"
        )

        OutputStreamWriter(file).use { writer ->
            writer.write("// AUTO-GENERATED by kap-ksp — do not edit\n")
            if (hasPackage) {
                writer.write("package $packageName\n\n")
            }
            writer.write("import kap.Kap\n")
            writer.write("import kap.of\n\n")

            // Generate value class wrappers
            params.forEach { param ->
                val paramName = param.name!!.asString()
                val wrapperName = "$className${paramName.replaceFirstChar { it.uppercase() }}"
                val typeName = param.type.resolve().declaration.qualifiedName?.asString()
                    ?: param.type.resolve().toString()

                writer.write("@JvmInline\n")
                writer.write("value class $wrapperName(val value: $typeName)\n\n")
            }

            // Generate kapSafe function
            val originalTypes = params.joinToString(", ") { param ->
                param.type.resolve().declaration.qualifiedName?.asString()
                    ?: param.type.resolve().toString()
            }

            val wrapperTypes = params.map { param ->
                val paramName = param.name!!.asString()
                "$className${paramName.replaceFirstChar { it.uppercase() }}"
            }

            // Build curried return type: (W1) -> (W2) -> ... -> R
            val curriedType = wrapperTypes.joinToString(" -> ") { "($it)" } + " -> $qualifiedClassName"

            writer.write("/**\n")
            writer.write(" * Type-safe variant of `kap(::$className)` where each parameter\n")
            writer.write(" * has a distinct wrapper type — swapping same-typed parameters\n")
            writer.write(" * causes a compile error.\n")
            writer.write(" */\n")
            writer.write("fun kapSafe(f: ($originalTypes) -> $qualifiedClassName): Kap<$curriedType> =\n")
            writer.write("    Kap.of(")

            // Build nested lambda: { a: W1 -> { b: W2 -> ... f(a.value, b.value, ...) }}
            val paramNames = params.mapIndexed { i, _ -> "p$i" }
            val wrapperParams = wrapperTypes.zip(paramNames)

            wrapperParams.forEach { (wrapper, name) ->
                writer.write("{ $name: $wrapper -> ")
            }
            val callArgs = paramNames.joinToString(", ") { "$it.value" }
            writer.write("f($callArgs)")
            writer.write(" }".repeat(params.size))
            writer.write(")\n")
        }
    }
}
