// AUTO-GENERATED by kap-ksp — do not edit
import arrow.core.Either
import arrow.core.NonEmptyList
import kap.Kap
import kap.KapLike
import kap.of
import kap.withV
import kap.thenV
import kap.thenValueV
import kap.evalGraph

// ── Validated infix `from` — maps Either<Nel<E>, FieldType> into tagged wrapper ──

infix fun <E, A> FixtMultiGenericFirstTag.from(value: Either<NonEmptyList<E>, A>): Either<NonEmptyList<E>, FixtMultiGenericFirst<A>> =
    value.map(::FixtMultiGenericFirst)

infix fun <E, B> FixtMultiGenericSecondTag.from(value: Either<NonEmptyList<E>, B>): Either<NonEmptyList<E>, FixtMultiGenericSecond<B>> =
    value.map(::FixtMultiGenericSecond)

infix fun <E> FixtMultiGenericNoteTag.from(value: Either<NonEmptyList<E>, kotlin.String>): Either<NonEmptyList<E>, FixtMultiGenericNote> =
    value.map(::FixtMultiGenericNote)

/** Validated scoped builder for @KapTypeSafe FixtMultiGeneric. Uses the same per-slot
 *  tag interfaces as FixtMultiGenericKap — each `.withV { field from validateField() }`
 *  narrows the receiver to one slot, accumulating errors via Arrow's applicative.
 */
class FixtMultiGenericValidatedKap<E, F>(@PublishedApi internal val _kap: Kap<Either<NonEmptyList<E>, F>>) : KapLike<Either<NonEmptyList<E>, F>>, FixtMultiGenericFirstSlot, FixtMultiGenericSecondSlot, FixtMultiGenericNoteSlot {
    override val asKap: Kap<Either<NonEmptyList<E>, F>> get() = _kap
    override val first: FixtMultiGenericFirstTag = FixtMultiGenericFirstTag()
    override val second: FixtMultiGenericSecondTag = FixtMultiGenericSecondTag()
    override val note: FixtMultiGenericNoteTag = FixtMultiGenericNoteTag()

    companion object {
        val first: FixtMultiGenericFirstTag = FixtMultiGenericFirstTag()
        val second: FixtMultiGenericSecondTag = FixtMultiGenericSecondTag()
        val note: FixtMultiGenericNoteTag = FixtMultiGenericNoteTag()
    }
}

// ── Per-slot .withV / .thenV / .thenValueV operators ──

@kotlin.jvm.JvmName("withV_first")
inline infix fun <E, A, Rest> FixtMultiGenericValidatedKap<E, (FixtMultiGenericFirst<A>) -> Rest>.withV(
    crossinline fa: suspend FixtMultiGenericFirstSlot.() -> Either<NonEmptyList<E>, FixtMultiGenericFirst<A>>,
): FixtMultiGenericValidatedKap<E, Rest> {
    val self = this
    return FixtMultiGenericValidatedKap(self._kap.withV(Kap { self.fa() }))
}

@kotlin.jvm.JvmName("thenV_first")
inline infix fun <E, A, Rest> FixtMultiGenericValidatedKap<E, (FixtMultiGenericFirst<A>) -> Rest>.thenV(
    crossinline fa: suspend FixtMultiGenericFirstSlot.() -> Either<NonEmptyList<E>, FixtMultiGenericFirst<A>>,
): FixtMultiGenericValidatedKap<E, Rest> {
    val self = this
    return FixtMultiGenericValidatedKap(self._kap.thenV(Kap { self.fa() }))
}

@kotlin.jvm.JvmName("thenValueV_first")
inline infix fun <E, A, Rest> FixtMultiGenericValidatedKap<E, (FixtMultiGenericFirst<A>) -> Rest>.thenValueV(
    crossinline fa: suspend FixtMultiGenericFirstSlot.() -> Either<NonEmptyList<E>, FixtMultiGenericFirst<A>>,
): FixtMultiGenericValidatedKap<E, Rest> {
    val self = this
    return FixtMultiGenericValidatedKap(self._kap.thenValueV(Kap { self.fa() }))
}

@kotlin.jvm.JvmName("withV_second")
inline infix fun <E, B, Rest> FixtMultiGenericValidatedKap<E, (FixtMultiGenericSecond<B>) -> Rest>.withV(
    crossinline fa: suspend FixtMultiGenericSecondSlot.() -> Either<NonEmptyList<E>, FixtMultiGenericSecond<B>>,
): FixtMultiGenericValidatedKap<E, Rest> {
    val self = this
    return FixtMultiGenericValidatedKap(self._kap.withV(Kap { self.fa() }))
}

@kotlin.jvm.JvmName("thenV_second")
inline infix fun <E, B, Rest> FixtMultiGenericValidatedKap<E, (FixtMultiGenericSecond<B>) -> Rest>.thenV(
    crossinline fa: suspend FixtMultiGenericSecondSlot.() -> Either<NonEmptyList<E>, FixtMultiGenericSecond<B>>,
): FixtMultiGenericValidatedKap<E, Rest> {
    val self = this
    return FixtMultiGenericValidatedKap(self._kap.thenV(Kap { self.fa() }))
}

@kotlin.jvm.JvmName("thenValueV_second")
inline infix fun <E, B, Rest> FixtMultiGenericValidatedKap<E, (FixtMultiGenericSecond<B>) -> Rest>.thenValueV(
    crossinline fa: suspend FixtMultiGenericSecondSlot.() -> Either<NonEmptyList<E>, FixtMultiGenericSecond<B>>,
): FixtMultiGenericValidatedKap<E, Rest> {
    val self = this
    return FixtMultiGenericValidatedKap(self._kap.thenValueV(Kap { self.fa() }))
}

@kotlin.jvm.JvmName("withV_note")
inline infix fun <E, A, B> FixtMultiGenericValidatedKap<E, (FixtMultiGenericNote) -> FixtMultiGeneric<A, B>>.withV(
    crossinline fa: suspend FixtMultiGenericNoteSlot.() -> Either<NonEmptyList<E>, FixtMultiGenericNote>,
): Kap<Either<NonEmptyList<E>, FixtMultiGeneric<A, B>>> {
    val self = this
    return self._kap.withV(Kap { self.fa() })
}

@kotlin.jvm.JvmName("thenV_note")
inline infix fun <E, A, B> FixtMultiGenericValidatedKap<E, (FixtMultiGenericNote) -> FixtMultiGeneric<A, B>>.thenV(
    crossinline fa: suspend FixtMultiGenericNoteSlot.() -> Either<NonEmptyList<E>, FixtMultiGenericNote>,
): Kap<Either<NonEmptyList<E>, FixtMultiGeneric<A, B>>> {
    val self = this
    return self._kap.thenV(Kap { self.fa() })
}

@kotlin.jvm.JvmName("thenValueV_note")
inline infix fun <E, A, B> FixtMultiGenericValidatedKap<E, (FixtMultiGenericNote) -> FixtMultiGeneric<A, B>>.thenValueV(
    crossinline fa: suspend FixtMultiGenericNoteSlot.() -> Either<NonEmptyList<E>, FixtMultiGenericNote>,
): Kap<Either<NonEmptyList<E>, FixtMultiGeneric<A, B>>> {
    val self = this
    return self._kap.thenValueV(Kap { self.fa() })
}

infix fun <E, A, B> FixtMultiGenericValidatedKap<E, (A) -> B>.withV(fa: Kap<Either<NonEmptyList<E>, A>>): FixtMultiGenericValidatedKap<E, B> =
    FixtMultiGenericValidatedKap(_kap.withV(fa))

infix fun <E, A, B> FixtMultiGenericValidatedKap<E, (A) -> B>.thenV(fa: Kap<Either<NonEmptyList<E>, A>>): FixtMultiGenericValidatedKap<E, B> =
    FixtMultiGenericValidatedKap(_kap.thenV(fa))

infix fun <E, A, B> FixtMultiGenericValidatedKap<E, (A) -> B>.thenValueV(fa: Kap<Either<NonEmptyList<E>, A>>): FixtMultiGenericValidatedKap<E, B> =
    FixtMultiGenericValidatedKap(_kap.thenValueV(fa))

infix fun <E, A, B> FixtMultiGenericValidatedKap<E, (FixtMultiGenericNote) -> FixtMultiGeneric<A, B>>.withV(fa: Kap<Either<NonEmptyList<E>, FixtMultiGenericNote>>): Kap<Either<NonEmptyList<E>, FixtMultiGeneric<A, B>>> =
    _kap.withV(fa)

infix fun <E, A, B> FixtMultiGenericValidatedKap<E, (FixtMultiGenericNote) -> FixtMultiGeneric<A, B>>.thenV(fa: Kap<Either<NonEmptyList<E>, FixtMultiGenericNote>>): Kap<Either<NonEmptyList<E>, FixtMultiGeneric<A, B>>> =
    _kap.thenV(fa)

infix fun <E, A, B> FixtMultiGenericValidatedKap<E, (FixtMultiGenericNote) -> FixtMultiGeneric<A, B>>.thenValueV(fa: Kap<Either<NonEmptyList<E>, FixtMultiGenericNote>>): Kap<Either<NonEmptyList<E>, FixtMultiGeneric<A, B>>> =
    _kap.thenValueV(fa)

suspend fun <E, A> FixtMultiGenericValidatedKap<E, A>.evalGraph(): Either<NonEmptyList<E>, A> = _kap.evalGraph()


/** Validated entry — returns FixtMultiGenericValidatedKap so `.withV { field from validate() }` works without imports. */
fun <E, A, B> kapVFixtMultiGeneric(): FixtMultiGenericValidatedKap<E, (FixtMultiGenericFirst<A>) -> (FixtMultiGenericSecond<B>) -> (FixtMultiGenericNote) -> FixtMultiGeneric<A, B>> {
    val fn: (FixtMultiGenericFirst<A>) -> (FixtMultiGenericSecond<B>) -> (FixtMultiGenericNote) -> FixtMultiGeneric<A, B> = { p0: FixtMultiGenericFirst<A> -> { p1: FixtMultiGenericSecond<B> -> { p2: FixtMultiGenericNote -> FixtMultiGeneric(p0.value, p1.value, p2.value) } } }
    val kap: Kap<Either<NonEmptyList<E>, (FixtMultiGenericFirst<A>) -> (FixtMultiGenericSecond<B>) -> (FixtMultiGenericNote) -> FixtMultiGeneric<A, B>>> = Kap.of(Either.Right(fn))
    return FixtMultiGenericValidatedKap(kap)
}
