// AUTO-GENERATED by kap-ksp — do not edit
import kap.Kap
import kap.KapLike
import kap.of
import kap.with
import kap.then
import kap.thenValue
import kap.map
import kap.andThen
import kap.evalGraph

// ── Opaque wrappers — one per field ──

data class FixtParamRestBody<Rest>(val value: Rest)

data class FixtParamRestCount(val value: kotlin.Int)

// ── Tag classes (receivers for infix `from`) ──

class FixtParamRestBodyTag internal constructor()
class FixtParamRestCountTag internal constructor()

// ── Infix `from` — wraps raw value or Kap<T> into the tagged wrapper ──

infix fun <Rest> FixtParamRestBodyTag.from(value: Rest): FixtParamRestBody<Rest> = FixtParamRestBody(value)
infix fun <Rest> FixtParamRestBodyTag.from(kap: Kap<Rest>): Kap<FixtParamRestBody<Rest>> = kap.map(::FixtParamRestBody)

infix fun FixtParamRestCountTag.from(value: kotlin.Int): FixtParamRestCount = FixtParamRestCount(value)
infix fun FixtParamRestCountTag.from(kap: Kap<kotlin.Int>): Kap<FixtParamRestCount> = kap.map(::FixtParamRestCount)

// ── Per-slot interfaces (lambda receivers for `.with` / `.then`) ──

interface FixtParamRestBodySlot { val body: FixtParamRestBodyTag }
interface FixtParamRestCountSlot { val count: FixtParamRestCountTag }

/** Scoped builder for @KapTypeSafe FixtParamRest. Implements every slot interface
 *  so each field is reachable as a member. The per-slot `.with` overloads
 *  below narrow the lambda receiver to a single tag — the IDE shows only the
 *  field expected at the current curry position when the body is empty.
 *
 *  The wrapper deliberately does NOT delegate to `Kap<F>`. If it did, the
 *  imported `Kap.with(suspend () -> A)` would compete with the slot-specific
 *  `.with { field from … }` and K2's overload resolution sometimes picks the
 *  generic one (before typechecking the lambda body), causing the slot's tag
 *  reference to fail with `Unresolved reference`.
 *
 *  The wrapper implements `KapLike<F>`, so kap-core operators (.map /
 *  .recover / .timeout / .settled / .memoize / .timed / .andThen /
 *  .evalGraph) are available directly on partial wrappers as well. For raw
 *  `Kap<F>` (e.g. an external API parameter), use `.asKap`.
 */
class FixtParamRestKap<F>(@PublishedApi internal val _kap: Kap<F>) : KapLike<F>, FixtParamRestBodySlot, FixtParamRestCountSlot {
    override val asKap: Kap<F> get() = _kap
    override val body: FixtParamRestBodyTag = FixtParamRestBodyTag()
    override val count: FixtParamRestCountTag = FixtParamRestCountTag()

    companion object {
        val body: FixtParamRestBodyTag = FixtParamRestBodyTag()
        val count: FixtParamRestCountTag = FixtParamRestCountTag()
    }
}

// ── Per-slot operators — IDE shows exactly the field expected at this position ──

@kotlin.jvm.JvmName("with_body")
inline infix fun <Rest, Rest_> FixtParamRestKap<(FixtParamRestBody<Rest>) -> Rest_>.with(
    crossinline fa: suspend FixtParamRestBodySlot.() -> FixtParamRestBody<Rest>,
): FixtParamRestKap<Rest_> {
    val self = this
    return FixtParamRestKap(self._kap.with(suspend { self.fa() }))
}

@kotlin.jvm.JvmName("then_body")
inline infix fun <Rest, Rest_> FixtParamRestKap<(FixtParamRestBody<Rest>) -> Rest_>.then(
    crossinline fa: suspend FixtParamRestBodySlot.() -> FixtParamRestBody<Rest>,
): FixtParamRestKap<Rest_> {
    val self = this
    return FixtParamRestKap(self._kap.then(suspend { self.fa() }))
}

@kotlin.jvm.JvmName("thenValue_body")
inline infix fun <Rest, Rest_> FixtParamRestKap<(FixtParamRestBody<Rest>) -> Rest_>.thenValue(
    crossinline fa: suspend FixtParamRestBodySlot.() -> FixtParamRestBody<Rest>,
): FixtParamRestKap<Rest_> {
    val self = this
    return FixtParamRestKap(self._kap.thenValue(suspend { self.fa() }))
}

@kotlin.jvm.JvmName("with_count")
inline infix fun <Rest> FixtParamRestKap<(FixtParamRestCount) -> FixtParamRest<Rest>>.with(
    crossinline fa: suspend FixtParamRestCountSlot.() -> FixtParamRestCount,
): Kap<FixtParamRest<Rest>> {
    val self = this
    return self._kap.with(suspend { self.fa() })
}

@kotlin.jvm.JvmName("then_count")
inline infix fun <Rest> FixtParamRestKap<(FixtParamRestCount) -> FixtParamRest<Rest>>.then(
    crossinline fa: suspend FixtParamRestCountSlot.() -> FixtParamRestCount,
): Kap<FixtParamRest<Rest>> {
    val self = this
    return self._kap.then(suspend { self.fa() })
}

@kotlin.jvm.JvmName("thenValue_count")
inline infix fun <Rest> FixtParamRestKap<(FixtParamRestCount) -> FixtParamRest<Rest>>.thenValue(
    crossinline fa: suspend FixtParamRestCountSlot.() -> FixtParamRestCount,
): Kap<FixtParamRest<Rest>> {
    val self = this
    return self._kap.thenValue(suspend { self.fa() })
}

infix fun <A, B> FixtParamRestKap<(A) -> B>.with(fa: Kap<A>): FixtParamRestKap<B> =
    FixtParamRestKap(_kap.with(fa))

infix fun <A, B> FixtParamRestKap<(A) -> B>.then(fa: Kap<A>): FixtParamRestKap<B> =
    FixtParamRestKap(_kap.then(fa))

infix fun <A, B> FixtParamRestKap<(A) -> B>.thenValue(fa: Kap<A>): FixtParamRestKap<B> =
    FixtParamRestKap(_kap.thenValue(fa))

infix fun <Rest> FixtParamRestKap<(FixtParamRestCount) -> FixtParamRest<Rest>>.with(fa: Kap<FixtParamRestCount>): Kap<FixtParamRest<Rest>> =
    _kap.with(fa)

infix fun <Rest> FixtParamRestKap<(FixtParamRestCount) -> FixtParamRest<Rest>>.then(fa: Kap<FixtParamRestCount>): Kap<FixtParamRest<Rest>> =
    _kap.then(fa)

infix fun <Rest> FixtParamRestKap<(FixtParamRestCount) -> FixtParamRest<Rest>>.thenValue(fa: Kap<FixtParamRestCount>): Kap<FixtParamRest<Rest>> =
    _kap.thenValue(fa)

inline infix fun <A, B> FixtParamRestKap<A>.andThen(
    crossinline f: (A) -> Kap<B>,
): Kap<B> = _kap.andThen(f)

suspend fun <A> FixtParamRestKap<A>.evalGraph(): A = _kap.evalGraph()


/** Official entry — `kap(::C)` plain, `kap<Double>(::C)` for generics. */
fun <Rest> kap(f: (Rest, kotlin.Int) -> FixtParamRest<Rest>): FixtParamRestKap<(FixtParamRestBody<Rest>) -> (FixtParamRestCount) -> FixtParamRest<Rest>> =
    FixtParamRestKap(Kap.of({ p0: FixtParamRestBody<Rest> -> { p1: FixtParamRestCount -> f(p0.value, p1.value) } }))

/** Generic zero-arg alternative — `kapFixtParamRest<Double>()`. */
fun <Rest> kapFixtParamRest(): FixtParamRestKap<(FixtParamRestBody<Rest>) -> (FixtParamRestCount) -> FixtParamRest<Rest>> =
    FixtParamRestKap(Kap.of({ p0: FixtParamRestBody<Rest> -> { p1: FixtParamRestCount -> FixtParamRest(p0.value, p1.value) } }))

