// AUTO-GENERATED by kap-ksp — do not edit
import kap.Kap
import kap.KapLike
import kap.of
import kap.with
import kap.then
import kap.thenValue
import kap.map
import kap.andThen
import kap.evalGraph

// ── Opaque wrappers — one per field ──

data class FixtBuildLeftValue(val value: kotlin.String)

// ── Tag classes (receivers for infix `from`) ──

class FixtBuildLeftValueTag internal constructor()

// ── Infix `from` — wraps raw value or Kap<T> into the tagged wrapper ──

infix fun FixtBuildLeftValueTag.from(value: kotlin.String): FixtBuildLeftValue = FixtBuildLeftValue(value)
infix fun FixtBuildLeftValueTag.from(kap: Kap<kotlin.String>): Kap<FixtBuildLeftValue> = kap.map(::FixtBuildLeftValue)

// ── Per-slot interfaces (lambda receivers for `.with` / `.then`) ──

interface FixtBuildLeftValueSlot { val value: FixtBuildLeftValueTag }

/** Scoped builder for @KapTypeSafe FixtBuildLeft. Implements every slot interface
 *  so each field is reachable as a member. The per-slot `.with` overloads
 *  below narrow the lambda receiver to a single tag — the IDE shows only the
 *  field expected at the current curry position when the body is empty.
 *
 *  The wrapper deliberately does NOT delegate to `Kap<F>`. If it did, the
 *  imported `Kap.with(suspend () -> A)` would compete with the slot-specific
 *  `.with { field from … }` and K2's overload resolution sometimes picks the
 *  generic one (before typechecking the lambda body), causing the slot's tag
 *  reference to fail with `Unresolved reference`.
 *
 *  The wrapper implements `KapLike<F>`, so kap-core operators (.map /
 *  .recover / .timeout / .settled / .memoize / .timed / .andThen /
 *  .evalGraph) are available directly on partial wrappers as well. For raw
 *  `Kap<F>` (e.g. an external API parameter), use `.asKap`.
 */
class FixtBuildLeftKap<F>(@PublishedApi internal val _kap: Kap<F>) : KapLike<F>, FixtBuildLeftValueSlot {
    override val asKap: Kap<F> get() = _kap
    override val value: FixtBuildLeftValueTag = FixtBuildLeftValueTag()

    companion object {
        val value: FixtBuildLeftValueTag = FixtBuildLeftValueTag()
    }
}

// ── Per-slot operators — IDE shows exactly the field expected at this position ──

@kotlin.jvm.JvmName("with_value")
inline infix fun FixtBuildLeftKap<(FixtBuildLeftValue) -> kotlin.String>.with(
    crossinline fa: suspend FixtBuildLeftValueSlot.() -> FixtBuildLeftValue,
): Kap<kotlin.String> {
    val self = this
    return self._kap.with(suspend { self.fa() })
}

@kotlin.jvm.JvmName("then_value")
inline infix fun FixtBuildLeftKap<(FixtBuildLeftValue) -> kotlin.String>.then(
    crossinline fa: suspend FixtBuildLeftValueSlot.() -> FixtBuildLeftValue,
): Kap<kotlin.String> {
    val self = this
    return self._kap.then(suspend { self.fa() })
}

@kotlin.jvm.JvmName("thenValue_value")
inline infix fun FixtBuildLeftKap<(FixtBuildLeftValue) -> kotlin.String>.thenValue(
    crossinline fa: suspend FixtBuildLeftValueSlot.() -> FixtBuildLeftValue,
): Kap<kotlin.String> {
    val self = this
    return self._kap.thenValue(suspend { self.fa() })
}

infix fun <A, B> FixtBuildLeftKap<(A) -> B>.with(fa: Kap<A>): FixtBuildLeftKap<B> =
    FixtBuildLeftKap(_kap.with(fa))

infix fun <A, B> FixtBuildLeftKap<(A) -> B>.then(fa: Kap<A>): FixtBuildLeftKap<B> =
    FixtBuildLeftKap(_kap.then(fa))

infix fun <A, B> FixtBuildLeftKap<(A) -> B>.thenValue(fa: Kap<A>): FixtBuildLeftKap<B> =
    FixtBuildLeftKap(_kap.thenValue(fa))

infix fun FixtBuildLeftKap<(FixtBuildLeftValue) -> kotlin.String>.with(fa: Kap<FixtBuildLeftValue>): Kap<kotlin.String> =
    _kap.with(fa)

infix fun FixtBuildLeftKap<(FixtBuildLeftValue) -> kotlin.String>.then(fa: Kap<FixtBuildLeftValue>): Kap<kotlin.String> =
    _kap.then(fa)

infix fun FixtBuildLeftKap<(FixtBuildLeftValue) -> kotlin.String>.thenValue(fa: Kap<FixtBuildLeftValue>): Kap<kotlin.String> =
    _kap.thenValue(fa)

inline infix fun <A, B> FixtBuildLeftKap<A>.andThen(
    crossinline f: (A) -> Kap<B>,
): Kap<B> = _kap.andThen(f)

suspend fun <A> FixtBuildLeftKap<A>.evalGraph(): A = _kap.evalGraph()


/** Official entry — `kap(::C)` plain, `kap<Double>(::C)` for generics. */
fun kapFixtBuildLeft(f: (kotlin.String) -> kotlin.String): FixtBuildLeftKap<(FixtBuildLeftValue) -> kotlin.String> =
    FixtBuildLeftKap(Kap.of({ p0: FixtBuildLeftValue -> f(p0.value) }))

