// AUTO-GENERATED by kap-ksp — do not edit
import arrow.core.Either
import arrow.core.NonEmptyList
import kap.Kap
import kap.KapLike
import kap.of
import kap.withV
import kap.thenV
import kap.thenValueV
import kap.evalGraph

// ── Validated infix `from` — maps Either<Nel<E_>, FieldType> into tagged wrapper ──

infix fun <E_, E> FixtParamEPayloadTag.from(value: Either<NonEmptyList<E_>, E>): Either<NonEmptyList<E_>, FixtParamEPayload<E>> =
    value.map(::FixtParamEPayload)

infix fun <E_> FixtParamENoteTag.from(value: Either<NonEmptyList<E_>, kotlin.String>): Either<NonEmptyList<E_>, FixtParamENote> =
    value.map(::FixtParamENote)

/** Validated scoped builder for @KapTypeSafe FixtParamE. Uses the same per-slot
 *  tag interfaces as FixtParamEKap — each `.withV { field from validateField() }`
 *  narrows the receiver to one slot, accumulating errors via Arrow's applicative.
 */
class FixtParamEValidatedKap<E_, F>(@PublishedApi internal val _kap: Kap<Either<NonEmptyList<E_>, F>>) : KapLike<Either<NonEmptyList<E_>, F>>, FixtParamEPayloadSlot, FixtParamENoteSlot {
    override val asKap: Kap<Either<NonEmptyList<E_>, F>> get() = _kap
    override val payload: FixtParamEPayloadTag = FixtParamEPayloadTag()
    override val note: FixtParamENoteTag = FixtParamENoteTag()

    companion object {
        val payload: FixtParamEPayloadTag = FixtParamEPayloadTag()
        val note: FixtParamENoteTag = FixtParamENoteTag()
    }
}

// ── Per-slot .withV / .thenV / .thenValueV operators ──

@kotlin.jvm.JvmName("withV_payload")
inline infix fun <E_, E, Rest> FixtParamEValidatedKap<E_, (FixtParamEPayload<E>) -> Rest>.withV(
    crossinline fa: suspend FixtParamEPayloadSlot.() -> Either<NonEmptyList<E_>, FixtParamEPayload<E>>,
): FixtParamEValidatedKap<E_, Rest> {
    val self = this
    return FixtParamEValidatedKap(self._kap.withV(Kap { self.fa() }))
}

@kotlin.jvm.JvmName("thenV_payload")
inline infix fun <E_, E, Rest> FixtParamEValidatedKap<E_, (FixtParamEPayload<E>) -> Rest>.thenV(
    crossinline fa: suspend FixtParamEPayloadSlot.() -> Either<NonEmptyList<E_>, FixtParamEPayload<E>>,
): FixtParamEValidatedKap<E_, Rest> {
    val self = this
    return FixtParamEValidatedKap(self._kap.thenV(Kap { self.fa() }))
}

@kotlin.jvm.JvmName("thenValueV_payload")
inline infix fun <E_, E, Rest> FixtParamEValidatedKap<E_, (FixtParamEPayload<E>) -> Rest>.thenValueV(
    crossinline fa: suspend FixtParamEPayloadSlot.() -> Either<NonEmptyList<E_>, FixtParamEPayload<E>>,
): FixtParamEValidatedKap<E_, Rest> {
    val self = this
    return FixtParamEValidatedKap(self._kap.thenValueV(Kap { self.fa() }))
}

@kotlin.jvm.JvmName("withV_note")
inline infix fun <E_, E> FixtParamEValidatedKap<E_, (FixtParamENote) -> FixtParamE<E>>.withV(
    crossinline fa: suspend FixtParamENoteSlot.() -> Either<NonEmptyList<E_>, FixtParamENote>,
): Kap<Either<NonEmptyList<E_>, FixtParamE<E>>> {
    val self = this
    return self._kap.withV(Kap { self.fa() })
}

@kotlin.jvm.JvmName("thenV_note")
inline infix fun <E_, E> FixtParamEValidatedKap<E_, (FixtParamENote) -> FixtParamE<E>>.thenV(
    crossinline fa: suspend FixtParamENoteSlot.() -> Either<NonEmptyList<E_>, FixtParamENote>,
): Kap<Either<NonEmptyList<E_>, FixtParamE<E>>> {
    val self = this
    return self._kap.thenV(Kap { self.fa() })
}

@kotlin.jvm.JvmName("thenValueV_note")
inline infix fun <E_, E> FixtParamEValidatedKap<E_, (FixtParamENote) -> FixtParamE<E>>.thenValueV(
    crossinline fa: suspend FixtParamENoteSlot.() -> Either<NonEmptyList<E_>, FixtParamENote>,
): Kap<Either<NonEmptyList<E_>, FixtParamE<E>>> {
    val self = this
    return self._kap.thenValueV(Kap { self.fa() })
}

infix fun <E_, A, B> FixtParamEValidatedKap<E_, (A) -> B>.withV(fa: Kap<Either<NonEmptyList<E_>, A>>): FixtParamEValidatedKap<E_, B> =
    FixtParamEValidatedKap(_kap.withV(fa))

infix fun <E_, A, B> FixtParamEValidatedKap<E_, (A) -> B>.thenV(fa: Kap<Either<NonEmptyList<E_>, A>>): FixtParamEValidatedKap<E_, B> =
    FixtParamEValidatedKap(_kap.thenV(fa))

infix fun <E_, A, B> FixtParamEValidatedKap<E_, (A) -> B>.thenValueV(fa: Kap<Either<NonEmptyList<E_>, A>>): FixtParamEValidatedKap<E_, B> =
    FixtParamEValidatedKap(_kap.thenValueV(fa))

infix fun <E_, E> FixtParamEValidatedKap<E_, (FixtParamENote) -> FixtParamE<E>>.withV(fa: Kap<Either<NonEmptyList<E_>, FixtParamENote>>): Kap<Either<NonEmptyList<E_>, FixtParamE<E>>> =
    _kap.withV(fa)

infix fun <E_, E> FixtParamEValidatedKap<E_, (FixtParamENote) -> FixtParamE<E>>.thenV(fa: Kap<Either<NonEmptyList<E_>, FixtParamENote>>): Kap<Either<NonEmptyList<E_>, FixtParamE<E>>> =
    _kap.thenV(fa)

infix fun <E_, E> FixtParamEValidatedKap<E_, (FixtParamENote) -> FixtParamE<E>>.thenValueV(fa: Kap<Either<NonEmptyList<E_>, FixtParamENote>>): Kap<Either<NonEmptyList<E_>, FixtParamE<E>>> =
    _kap.thenValueV(fa)

suspend fun <E_, A> FixtParamEValidatedKap<E_, A>.evalGraph(): Either<NonEmptyList<E_>, A> = _kap.evalGraph()


/** Validated entry — returns FixtParamEValidatedKap so `.withV { field from validate() }` works without imports. */
fun <E_, E> kapVFixtParamE(): FixtParamEValidatedKap<E_, (FixtParamEPayload<E>) -> (FixtParamENote) -> FixtParamE<E>> {
    val fn: (FixtParamEPayload<E>) -> (FixtParamENote) -> FixtParamE<E> = { p0: FixtParamEPayload<E> -> { p1: FixtParamENote -> FixtParamE(p0.value, p1.value) } }
    val kap: Kap<Either<NonEmptyList<E_>, (FixtParamEPayload<E>) -> (FixtParamENote) -> FixtParamE<E>>> = Kap.of(Either.Right(fn))
    return FixtParamEValidatedKap(kap)
}
