// AUTO-GENERATED by kap-ksp — do not edit
import arrow.core.Either
import arrow.core.NonEmptyList
import kap.Kap
import kap.KapLike
import kap.of
import kap.withV
import kap.thenV
import kap.thenValueV
import kap.evalGraph

// ── Validated infix `from` — maps Either<Nel<E>, FieldType> into tagged wrapper ──

infix fun <E> FixtBuildLeftValueTag.from(value: Either<NonEmptyList<E>, kotlin.String>): Either<NonEmptyList<E>, FixtBuildLeftValue> =
    value.map(::FixtBuildLeftValue)

/** Validated scoped builder for @KapTypeSafe FixtBuildLeft. Uses the same per-slot
 *  tag interfaces as FixtBuildLeftKap — each `.withV { field from validateField() }`
 *  narrows the receiver to one slot, accumulating errors via Arrow's applicative.
 */
class FixtBuildLeftValidatedKap<E, F>(@PublishedApi internal val _kap: Kap<Either<NonEmptyList<E>, F>>) : KapLike<Either<NonEmptyList<E>, F>>, FixtBuildLeftValueSlot {
    override val asKap: Kap<Either<NonEmptyList<E>, F>> get() = _kap
    override val value: FixtBuildLeftValueTag = FixtBuildLeftValueTag()

    companion object {
        val value: FixtBuildLeftValueTag = FixtBuildLeftValueTag()
    }
}

// ── Per-slot .withV / .thenV / .thenValueV operators ──

@kotlin.jvm.JvmName("withV_value")
inline infix fun <E> FixtBuildLeftValidatedKap<E, (FixtBuildLeftValue) -> kotlin.String>.withV(
    crossinline fa: suspend FixtBuildLeftValueSlot.() -> Either<NonEmptyList<E>, FixtBuildLeftValue>,
): Kap<Either<NonEmptyList<E>, kotlin.String>> {
    val self = this
    return self._kap.withV(Kap { self.fa() })
}

@kotlin.jvm.JvmName("thenV_value")
inline infix fun <E> FixtBuildLeftValidatedKap<E, (FixtBuildLeftValue) -> kotlin.String>.thenV(
    crossinline fa: suspend FixtBuildLeftValueSlot.() -> Either<NonEmptyList<E>, FixtBuildLeftValue>,
): Kap<Either<NonEmptyList<E>, kotlin.String>> {
    val self = this
    return self._kap.thenV(Kap { self.fa() })
}

@kotlin.jvm.JvmName("thenValueV_value")
inline infix fun <E> FixtBuildLeftValidatedKap<E, (FixtBuildLeftValue) -> kotlin.String>.thenValueV(
    crossinline fa: suspend FixtBuildLeftValueSlot.() -> Either<NonEmptyList<E>, FixtBuildLeftValue>,
): Kap<Either<NonEmptyList<E>, kotlin.String>> {
    val self = this
    return self._kap.thenValueV(Kap { self.fa() })
}

infix fun <E, A, B> FixtBuildLeftValidatedKap<E, (A) -> B>.withV(fa: Kap<Either<NonEmptyList<E>, A>>): FixtBuildLeftValidatedKap<E, B> =
    FixtBuildLeftValidatedKap(_kap.withV(fa))

infix fun <E, A, B> FixtBuildLeftValidatedKap<E, (A) -> B>.thenV(fa: Kap<Either<NonEmptyList<E>, A>>): FixtBuildLeftValidatedKap<E, B> =
    FixtBuildLeftValidatedKap(_kap.thenV(fa))

infix fun <E, A, B> FixtBuildLeftValidatedKap<E, (A) -> B>.thenValueV(fa: Kap<Either<NonEmptyList<E>, A>>): FixtBuildLeftValidatedKap<E, B> =
    FixtBuildLeftValidatedKap(_kap.thenValueV(fa))

infix fun <E> FixtBuildLeftValidatedKap<E, (FixtBuildLeftValue) -> kotlin.String>.withV(fa: Kap<Either<NonEmptyList<E>, FixtBuildLeftValue>>): Kap<Either<NonEmptyList<E>, kotlin.String>> =
    _kap.withV(fa)

infix fun <E> FixtBuildLeftValidatedKap<E, (FixtBuildLeftValue) -> kotlin.String>.thenV(fa: Kap<Either<NonEmptyList<E>, FixtBuildLeftValue>>): Kap<Either<NonEmptyList<E>, kotlin.String>> =
    _kap.thenV(fa)

infix fun <E> FixtBuildLeftValidatedKap<E, (FixtBuildLeftValue) -> kotlin.String>.thenValueV(fa: Kap<Either<NonEmptyList<E>, FixtBuildLeftValue>>): Kap<Either<NonEmptyList<E>, kotlin.String>> =
    _kap.thenValueV(fa)

suspend fun <E, A> FixtBuildLeftValidatedKap<E, A>.evalGraph(): Either<NonEmptyList<E>, A> = _kap.evalGraph()


/** Validated entry — `kapV(::C)` / `kapV<Double>(::C)` for generics. */
fun <E> kapVFixtBuildLeft(f: (kotlin.String) -> kotlin.String): FixtBuildLeftValidatedKap<E, (FixtBuildLeftValue) -> kotlin.String> {
    val fn: (FixtBuildLeftValue) -> kotlin.String = { p0: FixtBuildLeftValue -> f(p0.value) }
    val kap: Kap<Either<NonEmptyList<E>, (FixtBuildLeftValue) -> kotlin.String>> = Kap.of(Either.Right(fn))
    return FixtBuildLeftValidatedKap(kap)
}

