// AUTO-GENERATED by kap-ksp — do not edit
import arrow.core.Either
import arrow.core.NonEmptyList
import kap.Kap
import kap.KapLike
import kap.of
import kap.withV
import kap.thenV
import kap.thenValueV
import kap.evalGraph

// ── Validated infix `from` — maps Either<Nel<E>, FieldType> into tagged wrapper ──

infix fun <E> FixtAllSameTypeATag.from(value: Either<NonEmptyList<E>, kotlin.String>): Either<NonEmptyList<E>, FixtAllSameTypeA> =
    value.map(::FixtAllSameTypeA)

infix fun <E> FixtAllSameTypeBTag.from(value: Either<NonEmptyList<E>, kotlin.String>): Either<NonEmptyList<E>, FixtAllSameTypeB> =
    value.map(::FixtAllSameTypeB)

infix fun <E> FixtAllSameTypeCTag.from(value: Either<NonEmptyList<E>, kotlin.String>): Either<NonEmptyList<E>, FixtAllSameTypeC> =
    value.map(::FixtAllSameTypeC)

/** Validated scoped builder for @KapTypeSafe FixtAllSameType. Uses the same per-slot
 *  tag interfaces as FixtAllSameTypeKap — each `.withV { field from validateField() }`
 *  narrows the receiver to one slot, accumulating errors via Arrow's applicative.
 */
class FixtAllSameTypeValidatedKap<E, F>(@PublishedApi internal val _kap: Kap<Either<NonEmptyList<E>, F>>) : KapLike<Either<NonEmptyList<E>, F>>, FixtAllSameTypeASlot, FixtAllSameTypeBSlot, FixtAllSameTypeCSlot {
    override val asKap: Kap<Either<NonEmptyList<E>, F>> get() = _kap
    override val a: FixtAllSameTypeATag = FixtAllSameTypeATag()
    override val b: FixtAllSameTypeBTag = FixtAllSameTypeBTag()
    override val c: FixtAllSameTypeCTag = FixtAllSameTypeCTag()

    companion object {
        val a: FixtAllSameTypeATag = FixtAllSameTypeATag()
        val b: FixtAllSameTypeBTag = FixtAllSameTypeBTag()
        val c: FixtAllSameTypeCTag = FixtAllSameTypeCTag()
    }
}

// ── Per-slot .withV / .thenV / .thenValueV operators ──

@kotlin.jvm.JvmName("withV_a")
inline infix fun <E, Rest> FixtAllSameTypeValidatedKap<E, (FixtAllSameTypeA) -> Rest>.withV(
    crossinline fa: suspend FixtAllSameTypeASlot.() -> Either<NonEmptyList<E>, FixtAllSameTypeA>,
): FixtAllSameTypeValidatedKap<E, Rest> {
    val self = this
    return FixtAllSameTypeValidatedKap(self._kap.withV(Kap { self.fa() }))
}

@kotlin.jvm.JvmName("thenV_a")
inline infix fun <E, Rest> FixtAllSameTypeValidatedKap<E, (FixtAllSameTypeA) -> Rest>.thenV(
    crossinline fa: suspend FixtAllSameTypeASlot.() -> Either<NonEmptyList<E>, FixtAllSameTypeA>,
): FixtAllSameTypeValidatedKap<E, Rest> {
    val self = this
    return FixtAllSameTypeValidatedKap(self._kap.thenV(Kap { self.fa() }))
}

@kotlin.jvm.JvmName("thenValueV_a")
inline infix fun <E, Rest> FixtAllSameTypeValidatedKap<E, (FixtAllSameTypeA) -> Rest>.thenValueV(
    crossinline fa: suspend FixtAllSameTypeASlot.() -> Either<NonEmptyList<E>, FixtAllSameTypeA>,
): FixtAllSameTypeValidatedKap<E, Rest> {
    val self = this
    return FixtAllSameTypeValidatedKap(self._kap.thenValueV(Kap { self.fa() }))
}

@kotlin.jvm.JvmName("withV_b")
inline infix fun <E, Rest> FixtAllSameTypeValidatedKap<E, (FixtAllSameTypeB) -> Rest>.withV(
    crossinline fa: suspend FixtAllSameTypeBSlot.() -> Either<NonEmptyList<E>, FixtAllSameTypeB>,
): FixtAllSameTypeValidatedKap<E, Rest> {
    val self = this
    return FixtAllSameTypeValidatedKap(self._kap.withV(Kap { self.fa() }))
}

@kotlin.jvm.JvmName("thenV_b")
inline infix fun <E, Rest> FixtAllSameTypeValidatedKap<E, (FixtAllSameTypeB) -> Rest>.thenV(
    crossinline fa: suspend FixtAllSameTypeBSlot.() -> Either<NonEmptyList<E>, FixtAllSameTypeB>,
): FixtAllSameTypeValidatedKap<E, Rest> {
    val self = this
    return FixtAllSameTypeValidatedKap(self._kap.thenV(Kap { self.fa() }))
}

@kotlin.jvm.JvmName("thenValueV_b")
inline infix fun <E, Rest> FixtAllSameTypeValidatedKap<E, (FixtAllSameTypeB) -> Rest>.thenValueV(
    crossinline fa: suspend FixtAllSameTypeBSlot.() -> Either<NonEmptyList<E>, FixtAllSameTypeB>,
): FixtAllSameTypeValidatedKap<E, Rest> {
    val self = this
    return FixtAllSameTypeValidatedKap(self._kap.thenValueV(Kap { self.fa() }))
}

@kotlin.jvm.JvmName("withV_c")
inline infix fun <E> FixtAllSameTypeValidatedKap<E, (FixtAllSameTypeC) -> FixtAllSameType>.withV(
    crossinline fa: suspend FixtAllSameTypeCSlot.() -> Either<NonEmptyList<E>, FixtAllSameTypeC>,
): Kap<Either<NonEmptyList<E>, FixtAllSameType>> {
    val self = this
    return self._kap.withV(Kap { self.fa() })
}

@kotlin.jvm.JvmName("thenV_c")
inline infix fun <E> FixtAllSameTypeValidatedKap<E, (FixtAllSameTypeC) -> FixtAllSameType>.thenV(
    crossinline fa: suspend FixtAllSameTypeCSlot.() -> Either<NonEmptyList<E>, FixtAllSameTypeC>,
): Kap<Either<NonEmptyList<E>, FixtAllSameType>> {
    val self = this
    return self._kap.thenV(Kap { self.fa() })
}

@kotlin.jvm.JvmName("thenValueV_c")
inline infix fun <E> FixtAllSameTypeValidatedKap<E, (FixtAllSameTypeC) -> FixtAllSameType>.thenValueV(
    crossinline fa: suspend FixtAllSameTypeCSlot.() -> Either<NonEmptyList<E>, FixtAllSameTypeC>,
): Kap<Either<NonEmptyList<E>, FixtAllSameType>> {
    val self = this
    return self._kap.thenValueV(Kap { self.fa() })
}

infix fun <E, A, B> FixtAllSameTypeValidatedKap<E, (A) -> B>.withV(fa: Kap<Either<NonEmptyList<E>, A>>): FixtAllSameTypeValidatedKap<E, B> =
    FixtAllSameTypeValidatedKap(_kap.withV(fa))

infix fun <E, A, B> FixtAllSameTypeValidatedKap<E, (A) -> B>.thenV(fa: Kap<Either<NonEmptyList<E>, A>>): FixtAllSameTypeValidatedKap<E, B> =
    FixtAllSameTypeValidatedKap(_kap.thenV(fa))

infix fun <E, A, B> FixtAllSameTypeValidatedKap<E, (A) -> B>.thenValueV(fa: Kap<Either<NonEmptyList<E>, A>>): FixtAllSameTypeValidatedKap<E, B> =
    FixtAllSameTypeValidatedKap(_kap.thenValueV(fa))

infix fun <E> FixtAllSameTypeValidatedKap<E, (FixtAllSameTypeC) -> FixtAllSameType>.withV(fa: Kap<Either<NonEmptyList<E>, FixtAllSameTypeC>>): Kap<Either<NonEmptyList<E>, FixtAllSameType>> =
    _kap.withV(fa)

infix fun <E> FixtAllSameTypeValidatedKap<E, (FixtAllSameTypeC) -> FixtAllSameType>.thenV(fa: Kap<Either<NonEmptyList<E>, FixtAllSameTypeC>>): Kap<Either<NonEmptyList<E>, FixtAllSameType>> =
    _kap.thenV(fa)

infix fun <E> FixtAllSameTypeValidatedKap<E, (FixtAllSameTypeC) -> FixtAllSameType>.thenValueV(fa: Kap<Either<NonEmptyList<E>, FixtAllSameTypeC>>): Kap<Either<NonEmptyList<E>, FixtAllSameType>> =
    _kap.thenValueV(fa)

suspend fun <E, A> FixtAllSameTypeValidatedKap<E, A>.evalGraph(): Either<NonEmptyList<E>, A> = _kap.evalGraph()


/** Validated entry — `kapV(::C)` / `kapV<Double>(::C)` for generics. */
fun <E> kapV(f: (kotlin.String, kotlin.String, kotlin.String) -> FixtAllSameType): FixtAllSameTypeValidatedKap<E, (FixtAllSameTypeA) -> (FixtAllSameTypeB) -> (FixtAllSameTypeC) -> FixtAllSameType> {
    val fn: (FixtAllSameTypeA) -> (FixtAllSameTypeB) -> (FixtAllSameTypeC) -> FixtAllSameType = { p0: FixtAllSameTypeA -> { p1: FixtAllSameTypeB -> { p2: FixtAllSameTypeC -> f(p0.value, p1.value, p2.value) } } }
    val kap: Kap<Either<NonEmptyList<E>, (FixtAllSameTypeA) -> (FixtAllSameTypeB) -> (FixtAllSameTypeC) -> FixtAllSameType>> = Kap.of(Either.Right(fn))
    return FixtAllSameTypeValidatedKap(kap)
}

