// AUTO-GENERATED by kap-ksp — do not edit
import arrow.core.Either
import arrow.core.NonEmptyList
import kap.Kap
import kap.KapLike
import kap.of
import kap.withV
import kap.thenV
import kap.thenValueV
import kap.evalGraph

// ── Validated infix `from` — maps Either<Nel<E>, FieldType> into tagged wrapper ──

infix fun <E, T> FixtGenWrapInnerTag.from(value: Either<NonEmptyList<E>, T>): Either<NonEmptyList<E>, FixtGenWrapInner<T>> =
    value.map(::FixtGenWrapInner)

/** Validated scoped builder for @KapTypeSafe FixtGenWrap. Uses the same per-slot
 *  tag interfaces as FixtGenWrapKap — each `.withV { field from validateField() }`
 *  narrows the receiver to one slot, accumulating errors via Arrow's applicative.
 */
class FixtGenWrapValidatedKap<E, F>(@PublishedApi internal val _kap: Kap<Either<NonEmptyList<E>, F>>) : KapLike<Either<NonEmptyList<E>, F>>, FixtGenWrapInnerSlot {
    override val asKap: Kap<Either<NonEmptyList<E>, F>> get() = _kap
    override val inner: FixtGenWrapInnerTag = FixtGenWrapInnerTag()

    companion object {
        val inner: FixtGenWrapInnerTag = FixtGenWrapInnerTag()
    }
}

// ── Per-slot .withV / .thenV / .thenValueV operators ──

@kotlin.jvm.JvmName("withV_inner")
inline infix fun <E, T> FixtGenWrapValidatedKap<E, (FixtGenWrapInner<T>) -> FixtGenWrap<T>>.withV(
    crossinline fa: suspend FixtGenWrapInnerSlot.() -> Either<NonEmptyList<E>, FixtGenWrapInner<T>>,
): Kap<Either<NonEmptyList<E>, FixtGenWrap<T>>> {
    val self = this
    return self._kap.withV(Kap { self.fa() })
}

@kotlin.jvm.JvmName("thenV_inner")
inline infix fun <E, T> FixtGenWrapValidatedKap<E, (FixtGenWrapInner<T>) -> FixtGenWrap<T>>.thenV(
    crossinline fa: suspend FixtGenWrapInnerSlot.() -> Either<NonEmptyList<E>, FixtGenWrapInner<T>>,
): Kap<Either<NonEmptyList<E>, FixtGenWrap<T>>> {
    val self = this
    return self._kap.thenV(Kap { self.fa() })
}

@kotlin.jvm.JvmName("thenValueV_inner")
inline infix fun <E, T> FixtGenWrapValidatedKap<E, (FixtGenWrapInner<T>) -> FixtGenWrap<T>>.thenValueV(
    crossinline fa: suspend FixtGenWrapInnerSlot.() -> Either<NonEmptyList<E>, FixtGenWrapInner<T>>,
): Kap<Either<NonEmptyList<E>, FixtGenWrap<T>>> {
    val self = this
    return self._kap.thenValueV(Kap { self.fa() })
}

infix fun <E, A, B> FixtGenWrapValidatedKap<E, (A) -> B>.withV(fa: Kap<Either<NonEmptyList<E>, A>>): FixtGenWrapValidatedKap<E, B> =
    FixtGenWrapValidatedKap(_kap.withV(fa))

infix fun <E, A, B> FixtGenWrapValidatedKap<E, (A) -> B>.thenV(fa: Kap<Either<NonEmptyList<E>, A>>): FixtGenWrapValidatedKap<E, B> =
    FixtGenWrapValidatedKap(_kap.thenV(fa))

infix fun <E, A, B> FixtGenWrapValidatedKap<E, (A) -> B>.thenValueV(fa: Kap<Either<NonEmptyList<E>, A>>): FixtGenWrapValidatedKap<E, B> =
    FixtGenWrapValidatedKap(_kap.thenValueV(fa))

infix fun <E, T> FixtGenWrapValidatedKap<E, (FixtGenWrapInner<T>) -> FixtGenWrap<T>>.withV(fa: Kap<Either<NonEmptyList<E>, FixtGenWrapInner<T>>>): Kap<Either<NonEmptyList<E>, FixtGenWrap<T>>> =
    _kap.withV(fa)

infix fun <E, T> FixtGenWrapValidatedKap<E, (FixtGenWrapInner<T>) -> FixtGenWrap<T>>.thenV(fa: Kap<Either<NonEmptyList<E>, FixtGenWrapInner<T>>>): Kap<Either<NonEmptyList<E>, FixtGenWrap<T>>> =
    _kap.thenV(fa)

infix fun <E, T> FixtGenWrapValidatedKap<E, (FixtGenWrapInner<T>) -> FixtGenWrap<T>>.thenValueV(fa: Kap<Either<NonEmptyList<E>, FixtGenWrapInner<T>>>): Kap<Either<NonEmptyList<E>, FixtGenWrap<T>>> =
    _kap.thenValueV(fa)

suspend fun <E, A> FixtGenWrapValidatedKap<E, A>.evalGraph(): Either<NonEmptyList<E>, A> = _kap.evalGraph()


/** Validated entry — `kapV(::C)` / `kapV<Double>(::C)` for generics. */
fun <E, T> kapVFixtGenWrap(f: (T) -> FixtGenWrap<T>): FixtGenWrapValidatedKap<E, (FixtGenWrapInner<T>) -> FixtGenWrap<T>> {
    val fn: (FixtGenWrapInner<T>) -> FixtGenWrap<T> = { p0: FixtGenWrapInner<T> -> f(p0.value) }
    val kap: Kap<Either<NonEmptyList<E>, (FixtGenWrapInner<T>) -> FixtGenWrap<T>>> = Kap.of(Either.Right(fn))
    return FixtGenWrapValidatedKap(kap)
}

/** Generic zero-arg alternative — `kapVFixtGenWrap<Double>()`. */
fun <E, T> kapVFixtGenWrap(): FixtGenWrapValidatedKap<E, (FixtGenWrapInner<T>) -> FixtGenWrap<T>> {
    val fn: (FixtGenWrapInner<T>) -> FixtGenWrap<T> = { p0: FixtGenWrapInner<T> -> FixtGenWrap(p0.value) }
    val kap: Kap<Either<NonEmptyList<E>, (FixtGenWrapInner<T>) -> FixtGenWrap<T>>> = Kap.of(Either.Right(fn))
    return FixtGenWrapValidatedKap(kap)
}

