// AUTO-GENERATED by kap-ksp — do not edit
import kap.Kap
import kap.KapLike
import kap.of
import kap.with
import kap.then
import kap.thenValue
import kap.map
import kap.andThen
import kap.evalGraph

// ── Opaque wrappers — one per field ──

data class FixtParamEPayload<E>(val value: E)

data class FixtParamENote(val value: kotlin.String)

// ── Tag classes (receivers for infix `from`) ──

class FixtParamEPayloadTag internal constructor()
class FixtParamENoteTag internal constructor()

// ── Infix `from` — wraps raw value or Kap<T> into the tagged wrapper ──

infix fun <E> FixtParamEPayloadTag.from(value: E): FixtParamEPayload<E> = FixtParamEPayload(value)
infix fun <E> FixtParamEPayloadTag.from(kap: Kap<E>): Kap<FixtParamEPayload<E>> = kap.map(::FixtParamEPayload)

infix fun FixtParamENoteTag.from(value: kotlin.String): FixtParamENote = FixtParamENote(value)
infix fun FixtParamENoteTag.from(kap: Kap<kotlin.String>): Kap<FixtParamENote> = kap.map(::FixtParamENote)

// ── Per-slot interfaces (lambda receivers for `.with` / `.then`) ──

interface FixtParamEPayloadSlot { val payload: FixtParamEPayloadTag }
interface FixtParamENoteSlot { val note: FixtParamENoteTag }

/** Scoped builder for @KapTypeSafe FixtParamE. Implements every slot interface
 *  so each field is reachable as a member. The per-slot `.with` overloads
 *  below narrow the lambda receiver to a single tag — the IDE shows only the
 *  field expected at the current curry position when the body is empty.
 *
 *  The wrapper deliberately does NOT delegate to `Kap<F>`. If it did, the
 *  imported `Kap.with(suspend () -> A)` would compete with the slot-specific
 *  `.with { field from … }` and K2's overload resolution sometimes picks the
 *  generic one (before typechecking the lambda body), causing the slot's tag
 *  reference to fail with `Unresolved reference`.
 *
 *  The wrapper implements `KapLike<F>`, so kap-core operators (.map /
 *  .recover / .timeout / .settled / .memoize / .timed / .andThen /
 *  .evalGraph) are available directly on partial wrappers as well. For raw
 *  `Kap<F>` (e.g. an external API parameter), use `.asKap`.
 */
class FixtParamEKap<F>(@PublishedApi internal val _kap: Kap<F>) : KapLike<F>, FixtParamEPayloadSlot, FixtParamENoteSlot {
    override val asKap: Kap<F> get() = _kap
    override val payload: FixtParamEPayloadTag = FixtParamEPayloadTag()
    override val note: FixtParamENoteTag = FixtParamENoteTag()

    companion object {
        val payload: FixtParamEPayloadTag = FixtParamEPayloadTag()
        val note: FixtParamENoteTag = FixtParamENoteTag()
    }
}

// ── Per-slot operators — IDE shows exactly the field expected at this position ──

@kotlin.jvm.JvmName("with_payload")
inline infix fun <E, Rest> FixtParamEKap<(FixtParamEPayload<E>) -> Rest>.with(
    crossinline fa: suspend FixtParamEPayloadSlot.() -> FixtParamEPayload<E>,
): FixtParamEKap<Rest> {
    val self = this
    return FixtParamEKap(self._kap.with(suspend { self.fa() }))
}

@kotlin.jvm.JvmName("then_payload")
inline infix fun <E, Rest> FixtParamEKap<(FixtParamEPayload<E>) -> Rest>.then(
    crossinline fa: suspend FixtParamEPayloadSlot.() -> FixtParamEPayload<E>,
): FixtParamEKap<Rest> {
    val self = this
    return FixtParamEKap(self._kap.then(suspend { self.fa() }))
}

@kotlin.jvm.JvmName("thenValue_payload")
inline infix fun <E, Rest> FixtParamEKap<(FixtParamEPayload<E>) -> Rest>.thenValue(
    crossinline fa: suspend FixtParamEPayloadSlot.() -> FixtParamEPayload<E>,
): FixtParamEKap<Rest> {
    val self = this
    return FixtParamEKap(self._kap.thenValue(suspend { self.fa() }))
}

@kotlin.jvm.JvmName("with_note")
inline infix fun <E> FixtParamEKap<(FixtParamENote) -> FixtParamE<E>>.with(
    crossinline fa: suspend FixtParamENoteSlot.() -> FixtParamENote,
): Kap<FixtParamE<E>> {
    val self = this
    return self._kap.with(suspend { self.fa() })
}

@kotlin.jvm.JvmName("then_note")
inline infix fun <E> FixtParamEKap<(FixtParamENote) -> FixtParamE<E>>.then(
    crossinline fa: suspend FixtParamENoteSlot.() -> FixtParamENote,
): Kap<FixtParamE<E>> {
    val self = this
    return self._kap.then(suspend { self.fa() })
}

@kotlin.jvm.JvmName("thenValue_note")
inline infix fun <E> FixtParamEKap<(FixtParamENote) -> FixtParamE<E>>.thenValue(
    crossinline fa: suspend FixtParamENoteSlot.() -> FixtParamENote,
): Kap<FixtParamE<E>> {
    val self = this
    return self._kap.thenValue(suspend { self.fa() })
}

infix fun <A, B> FixtParamEKap<(A) -> B>.with(fa: Kap<A>): FixtParamEKap<B> =
    FixtParamEKap(_kap.with(fa))

infix fun <A, B> FixtParamEKap<(A) -> B>.then(fa: Kap<A>): FixtParamEKap<B> =
    FixtParamEKap(_kap.then(fa))

infix fun <A, B> FixtParamEKap<(A) -> B>.thenValue(fa: Kap<A>): FixtParamEKap<B> =
    FixtParamEKap(_kap.thenValue(fa))

infix fun <E> FixtParamEKap<(FixtParamENote) -> FixtParamE<E>>.with(fa: Kap<FixtParamENote>): Kap<FixtParamE<E>> =
    _kap.with(fa)

infix fun <E> FixtParamEKap<(FixtParamENote) -> FixtParamE<E>>.then(fa: Kap<FixtParamENote>): Kap<FixtParamE<E>> =
    _kap.then(fa)

infix fun <E> FixtParamEKap<(FixtParamENote) -> FixtParamE<E>>.thenValue(fa: Kap<FixtParamENote>): Kap<FixtParamE<E>> =
    _kap.thenValue(fa)

inline infix fun <A, B> FixtParamEKap<A>.andThen(
    crossinline f: (A) -> Kap<B>,
): Kap<B> = _kap.andThen(f)

suspend fun <A> FixtParamEKap<A>.evalGraph(): A = _kap.evalGraph()


/** Official entry point — returns FixtParamEKap so `.with { field from value }` works without imports. */
fun <E> kapFixtParamE(): FixtParamEKap<(FixtParamEPayload<E>) -> (FixtParamENote) -> FixtParamE<E>> =
    FixtParamEKap(Kap.of({ p0: FixtParamEPayload<E> -> { p1: FixtParamENote -> FixtParamE(p0.value, p1.value) } }))
