// AUTO-GENERATED by kap-ksp — do not edit
import kap.Kap
import kap.KapLike
import kap.of
import kap.with
import kap.then
import kap.thenValue
import kap.map
import kap.andThen
import kap.evalGraph

// ── Opaque wrappers — one per field ──

data class FixtMultiGenericFirst<A>(val value: A)

data class FixtMultiGenericSecond<B>(val value: B)

data class FixtMultiGenericNote(val value: kotlin.String)

// ── Tag classes (receivers for infix `from`) ──

class FixtMultiGenericFirstTag internal constructor()
class FixtMultiGenericSecondTag internal constructor()
class FixtMultiGenericNoteTag internal constructor()

// ── Infix `from` — wraps raw value or Kap<T> into the tagged wrapper ──

infix fun <A> FixtMultiGenericFirstTag.from(value: A): FixtMultiGenericFirst<A> = FixtMultiGenericFirst(value)
infix fun <A> FixtMultiGenericFirstTag.from(kap: Kap<A>): Kap<FixtMultiGenericFirst<A>> = kap.map(::FixtMultiGenericFirst)

infix fun <B> FixtMultiGenericSecondTag.from(value: B): FixtMultiGenericSecond<B> = FixtMultiGenericSecond(value)
infix fun <B> FixtMultiGenericSecondTag.from(kap: Kap<B>): Kap<FixtMultiGenericSecond<B>> = kap.map(::FixtMultiGenericSecond)

infix fun FixtMultiGenericNoteTag.from(value: kotlin.String): FixtMultiGenericNote = FixtMultiGenericNote(value)
infix fun FixtMultiGenericNoteTag.from(kap: Kap<kotlin.String>): Kap<FixtMultiGenericNote> = kap.map(::FixtMultiGenericNote)

// ── Per-slot interfaces (lambda receivers for `.with` / `.then`) ──

interface FixtMultiGenericFirstSlot { val first: FixtMultiGenericFirstTag }
interface FixtMultiGenericSecondSlot { val second: FixtMultiGenericSecondTag }
interface FixtMultiGenericNoteSlot { val note: FixtMultiGenericNoteTag }

/** Scoped builder for @KapTypeSafe FixtMultiGeneric. Implements every slot interface
 *  so each field is reachable as a member. The per-slot `.with` overloads
 *  below narrow the lambda receiver to a single tag — the IDE shows only the
 *  field expected at the current curry position when the body is empty.
 *
 *  The wrapper deliberately does NOT delegate to `Kap<F>`. If it did, the
 *  imported `Kap.with(suspend () -> A)` would compete with the slot-specific
 *  `.with { field from … }` and K2's overload resolution sometimes picks the
 *  generic one (before typechecking the lambda body), causing the slot's tag
 *  reference to fail with `Unresolved reference`.
 *
 *  The wrapper implements `KapLike<F>`, so kap-core operators (.map /
 *  .recover / .timeout / .settled / .memoize / .timed / .andThen /
 *  .evalGraph) are available directly on partial wrappers as well. For raw
 *  `Kap<F>` (e.g. an external API parameter), use `.asKap`.
 */
class FixtMultiGenericKap<F>(@PublishedApi internal val _kap: Kap<F>) : KapLike<F>, FixtMultiGenericFirstSlot, FixtMultiGenericSecondSlot, FixtMultiGenericNoteSlot {
    override val asKap: Kap<F> get() = _kap
    override val first: FixtMultiGenericFirstTag = FixtMultiGenericFirstTag()
    override val second: FixtMultiGenericSecondTag = FixtMultiGenericSecondTag()
    override val note: FixtMultiGenericNoteTag = FixtMultiGenericNoteTag()

    companion object {
        val first: FixtMultiGenericFirstTag = FixtMultiGenericFirstTag()
        val second: FixtMultiGenericSecondTag = FixtMultiGenericSecondTag()
        val note: FixtMultiGenericNoteTag = FixtMultiGenericNoteTag()
    }
}

// ── Per-slot operators — IDE shows exactly the field expected at this position ──

@kotlin.jvm.JvmName("with_first")
inline infix fun <A, Rest> FixtMultiGenericKap<(FixtMultiGenericFirst<A>) -> Rest>.with(
    crossinline fa: suspend FixtMultiGenericFirstSlot.() -> FixtMultiGenericFirst<A>,
): FixtMultiGenericKap<Rest> {
    val self = this
    return FixtMultiGenericKap(self._kap.with(suspend { self.fa() }))
}

@kotlin.jvm.JvmName("then_first")
inline infix fun <A, Rest> FixtMultiGenericKap<(FixtMultiGenericFirst<A>) -> Rest>.then(
    crossinline fa: suspend FixtMultiGenericFirstSlot.() -> FixtMultiGenericFirst<A>,
): FixtMultiGenericKap<Rest> {
    val self = this
    return FixtMultiGenericKap(self._kap.then(suspend { self.fa() }))
}

@kotlin.jvm.JvmName("thenValue_first")
inline infix fun <A, Rest> FixtMultiGenericKap<(FixtMultiGenericFirst<A>) -> Rest>.thenValue(
    crossinline fa: suspend FixtMultiGenericFirstSlot.() -> FixtMultiGenericFirst<A>,
): FixtMultiGenericKap<Rest> {
    val self = this
    return FixtMultiGenericKap(self._kap.thenValue(suspend { self.fa() }))
}

@kotlin.jvm.JvmName("with_second")
inline infix fun <B, Rest> FixtMultiGenericKap<(FixtMultiGenericSecond<B>) -> Rest>.with(
    crossinline fa: suspend FixtMultiGenericSecondSlot.() -> FixtMultiGenericSecond<B>,
): FixtMultiGenericKap<Rest> {
    val self = this
    return FixtMultiGenericKap(self._kap.with(suspend { self.fa() }))
}

@kotlin.jvm.JvmName("then_second")
inline infix fun <B, Rest> FixtMultiGenericKap<(FixtMultiGenericSecond<B>) -> Rest>.then(
    crossinline fa: suspend FixtMultiGenericSecondSlot.() -> FixtMultiGenericSecond<B>,
): FixtMultiGenericKap<Rest> {
    val self = this
    return FixtMultiGenericKap(self._kap.then(suspend { self.fa() }))
}

@kotlin.jvm.JvmName("thenValue_second")
inline infix fun <B, Rest> FixtMultiGenericKap<(FixtMultiGenericSecond<B>) -> Rest>.thenValue(
    crossinline fa: suspend FixtMultiGenericSecondSlot.() -> FixtMultiGenericSecond<B>,
): FixtMultiGenericKap<Rest> {
    val self = this
    return FixtMultiGenericKap(self._kap.thenValue(suspend { self.fa() }))
}

@kotlin.jvm.JvmName("with_note")
inline infix fun <A, B> FixtMultiGenericKap<(FixtMultiGenericNote) -> FixtMultiGeneric<A, B>>.with(
    crossinline fa: suspend FixtMultiGenericNoteSlot.() -> FixtMultiGenericNote,
): Kap<FixtMultiGeneric<A, B>> {
    val self = this
    return self._kap.with(suspend { self.fa() })
}

@kotlin.jvm.JvmName("then_note")
inline infix fun <A, B> FixtMultiGenericKap<(FixtMultiGenericNote) -> FixtMultiGeneric<A, B>>.then(
    crossinline fa: suspend FixtMultiGenericNoteSlot.() -> FixtMultiGenericNote,
): Kap<FixtMultiGeneric<A, B>> {
    val self = this
    return self._kap.then(suspend { self.fa() })
}

@kotlin.jvm.JvmName("thenValue_note")
inline infix fun <A, B> FixtMultiGenericKap<(FixtMultiGenericNote) -> FixtMultiGeneric<A, B>>.thenValue(
    crossinline fa: suspend FixtMultiGenericNoteSlot.() -> FixtMultiGenericNote,
): Kap<FixtMultiGeneric<A, B>> {
    val self = this
    return self._kap.thenValue(suspend { self.fa() })
}

infix fun <A, B> FixtMultiGenericKap<(A) -> B>.with(fa: Kap<A>): FixtMultiGenericKap<B> =
    FixtMultiGenericKap(_kap.with(fa))

infix fun <A, B> FixtMultiGenericKap<(A) -> B>.then(fa: Kap<A>): FixtMultiGenericKap<B> =
    FixtMultiGenericKap(_kap.then(fa))

infix fun <A, B> FixtMultiGenericKap<(A) -> B>.thenValue(fa: Kap<A>): FixtMultiGenericKap<B> =
    FixtMultiGenericKap(_kap.thenValue(fa))

infix fun <A, B> FixtMultiGenericKap<(FixtMultiGenericNote) -> FixtMultiGeneric<A, B>>.with(fa: Kap<FixtMultiGenericNote>): Kap<FixtMultiGeneric<A, B>> =
    _kap.with(fa)

infix fun <A, B> FixtMultiGenericKap<(FixtMultiGenericNote) -> FixtMultiGeneric<A, B>>.then(fa: Kap<FixtMultiGenericNote>): Kap<FixtMultiGeneric<A, B>> =
    _kap.then(fa)

infix fun <A, B> FixtMultiGenericKap<(FixtMultiGenericNote) -> FixtMultiGeneric<A, B>>.thenValue(fa: Kap<FixtMultiGenericNote>): Kap<FixtMultiGeneric<A, B>> =
    _kap.thenValue(fa)

inline infix fun <A, B> FixtMultiGenericKap<A>.andThen(
    crossinline f: (A) -> Kap<B>,
): Kap<B> = _kap.andThen(f)

suspend fun <A> FixtMultiGenericKap<A>.evalGraph(): A = _kap.evalGraph()


/** Official entry — `kap(::C)` plain, `kap<Double>(::C)` for generics. */
fun <A, B> kap(f: (A, B, kotlin.String) -> FixtMultiGeneric<A, B>): FixtMultiGenericKap<(FixtMultiGenericFirst<A>) -> (FixtMultiGenericSecond<B>) -> (FixtMultiGenericNote) -> FixtMultiGeneric<A, B>> =
    FixtMultiGenericKap(Kap.of({ p0: FixtMultiGenericFirst<A> -> { p1: FixtMultiGenericSecond<B> -> { p2: FixtMultiGenericNote -> f(p0.value, p1.value, p2.value) } } }))

/** Generic zero-arg alternative — `kapFixtMultiGeneric<Double>()`. */
fun <A, B> kapFixtMultiGeneric(): FixtMultiGenericKap<(FixtMultiGenericFirst<A>) -> (FixtMultiGenericSecond<B>) -> (FixtMultiGenericNote) -> FixtMultiGeneric<A, B>> =
    FixtMultiGenericKap(Kap.of({ p0: FixtMultiGenericFirst<A> -> { p1: FixtMultiGenericSecond<B> -> { p2: FixtMultiGenericNote -> FixtMultiGeneric(p0.value, p1.value, p2.value) } } }))

