// AUTO-GENERATED by kap-ksp — do not edit
import kap.Kap
import kap.KapLike
import kap.of
import kap.with
import kap.then
import kap.thenValue
import kap.map
import kap.andThen
import kap.evalGraph

// ── Opaque wrappers — one per field ──

data class FixtUniqueA(val value: kotlin.Int)

data class FixtUniqueB(val value: kotlin.Boolean)

// ── Tag classes (receivers for infix `from`) ──

class FixtUniqueATag internal constructor()
class FixtUniqueBTag internal constructor()

// ── Infix `from` — wraps raw value or Kap<T> into the tagged wrapper ──

infix fun FixtUniqueATag.from(value: kotlin.Int): FixtUniqueA = FixtUniqueA(value)
infix fun FixtUniqueATag.from(kap: Kap<kotlin.Int>): Kap<FixtUniqueA> = kap.map(::FixtUniqueA)

infix fun FixtUniqueBTag.from(value: kotlin.Boolean): FixtUniqueB = FixtUniqueB(value)
infix fun FixtUniqueBTag.from(kap: Kap<kotlin.Boolean>): Kap<FixtUniqueB> = kap.map(::FixtUniqueB)

// ── Per-slot interfaces (lambda receivers for `.with` / `.then`) ──

interface FixtUniqueASlot { val a: FixtUniqueATag }
interface FixtUniqueBSlot { val b: FixtUniqueBTag }

/** Scoped builder for @KapTypeSafe FixtUnique. Implements every slot interface
 *  so each field is reachable as a member. The per-slot `.with` overloads
 *  below narrow the lambda receiver to a single tag — the IDE shows only the
 *  field expected at the current curry position when the body is empty.
 *
 *  The wrapper deliberately does NOT delegate to `Kap<F>`. If it did, the
 *  imported `Kap.with(suspend () -> A)` would compete with the slot-specific
 *  `.with { field from … }` and K2's overload resolution sometimes picks the
 *  generic one (before typechecking the lambda body), causing the slot's tag
 *  reference to fail with `Unresolved reference`.
 *
 *  The wrapper implements `KapLike<F>`, so kap-core operators (.map /
 *  .recover / .timeout / .settled / .memoize / .timed / .andThen /
 *  .evalGraph) are available directly on partial wrappers as well. For raw
 *  `Kap<F>` (e.g. an external API parameter), use `.asKap`.
 */
class FixtUniqueKap<F>(@PublishedApi internal val _kap: Kap<F>) : KapLike<F>, FixtUniqueASlot, FixtUniqueBSlot {
    override val asKap: Kap<F> get() = _kap
    override val a: FixtUniqueATag = FixtUniqueATag()
    override val b: FixtUniqueBTag = FixtUniqueBTag()

    companion object {
        val a: FixtUniqueATag = FixtUniqueATag()
        val b: FixtUniqueBTag = FixtUniqueBTag()
    }
}

// ── Per-slot operators — IDE shows exactly the field expected at this position ──

@kotlin.jvm.JvmName("with_a")
inline infix fun <Rest> FixtUniqueKap<(FixtUniqueA) -> Rest>.with(
    crossinline fa: suspend FixtUniqueASlot.() -> FixtUniqueA,
): FixtUniqueKap<Rest> {
    val self = this
    return FixtUniqueKap(self._kap.with(suspend { self.fa() }))
}

@kotlin.jvm.JvmName("then_a")
inline infix fun <Rest> FixtUniqueKap<(FixtUniqueA) -> Rest>.then(
    crossinline fa: suspend FixtUniqueASlot.() -> FixtUniqueA,
): FixtUniqueKap<Rest> {
    val self = this
    return FixtUniqueKap(self._kap.then(suspend { self.fa() }))
}

@kotlin.jvm.JvmName("thenValue_a")
inline infix fun <Rest> FixtUniqueKap<(FixtUniqueA) -> Rest>.thenValue(
    crossinline fa: suspend FixtUniqueASlot.() -> FixtUniqueA,
): FixtUniqueKap<Rest> {
    val self = this
    return FixtUniqueKap(self._kap.thenValue(suspend { self.fa() }))
}

@kotlin.jvm.JvmName("with_b")
inline infix fun FixtUniqueKap<(FixtUniqueB) -> kotlin.String>.with(
    crossinline fa: suspend FixtUniqueBSlot.() -> FixtUniqueB,
): Kap<kotlin.String> {
    val self = this
    return self._kap.with(suspend { self.fa() })
}

@kotlin.jvm.JvmName("then_b")
inline infix fun FixtUniqueKap<(FixtUniqueB) -> kotlin.String>.then(
    crossinline fa: suspend FixtUniqueBSlot.() -> FixtUniqueB,
): Kap<kotlin.String> {
    val self = this
    return self._kap.then(suspend { self.fa() })
}

@kotlin.jvm.JvmName("thenValue_b")
inline infix fun FixtUniqueKap<(FixtUniqueB) -> kotlin.String>.thenValue(
    crossinline fa: suspend FixtUniqueBSlot.() -> FixtUniqueB,
): Kap<kotlin.String> {
    val self = this
    return self._kap.thenValue(suspend { self.fa() })
}

infix fun <A, B> FixtUniqueKap<(A) -> B>.with(fa: Kap<A>): FixtUniqueKap<B> =
    FixtUniqueKap(_kap.with(fa))

infix fun <A, B> FixtUniqueKap<(A) -> B>.then(fa: Kap<A>): FixtUniqueKap<B> =
    FixtUniqueKap(_kap.then(fa))

infix fun <A, B> FixtUniqueKap<(A) -> B>.thenValue(fa: Kap<A>): FixtUniqueKap<B> =
    FixtUniqueKap(_kap.thenValue(fa))

infix fun FixtUniqueKap<(FixtUniqueB) -> kotlin.String>.with(fa: Kap<FixtUniqueB>): Kap<kotlin.String> =
    _kap.with(fa)

infix fun FixtUniqueKap<(FixtUniqueB) -> kotlin.String>.then(fa: Kap<FixtUniqueB>): Kap<kotlin.String> =
    _kap.then(fa)

infix fun FixtUniqueKap<(FixtUniqueB) -> kotlin.String>.thenValue(fa: Kap<FixtUniqueB>): Kap<kotlin.String> =
    _kap.thenValue(fa)

inline infix fun <A, B> FixtUniqueKap<A>.andThen(
    crossinline f: (A) -> Kap<B>,
): Kap<B> = _kap.andThen(f)

suspend fun <A> FixtUniqueKap<A>.evalGraph(): A = _kap.evalGraph()


/** Official entry point — returns FixtUniqueKap so `.with { field from value }` works without imports. */
fun kap(f: (kotlin.Int, kotlin.Boolean) -> kotlin.String): FixtUniqueKap<(FixtUniqueA) -> (FixtUniqueB) -> kotlin.String> =
    FixtUniqueKap(Kap.of({ p0: FixtUniqueA -> { p1: FixtUniqueB -> f(p0.value, p1.value) } }))

/** Extension property — enables `(::myFn).kap` and `kap((::myFn)::kap)` forms. */
val ((kotlin.Int, kotlin.Boolean) -> kotlin.String).kap: FixtUniqueKap<(FixtUniqueA) -> (FixtUniqueB) -> kotlin.String>
    get() = FixtUniqueKap(Kap.of({ p0: FixtUniqueA -> { p1: FixtUniqueB -> this(p0.value, p1.value) } }))
