// AUTO-GENERATED by kap-ksp — do not edit
import kap.Kap
import kap.KapLike
import kap.of
import kap.with
import kap.then
import kap.thenValue
import kap.map
import kap.andThen
import kap.evalGraph

// ── Opaque wrappers — one per field ──

data class FixtWithNullableId(val value: kotlin.Long)

data class FixtWithNullableName(val value: kotlin.String?)

data class FixtWithNullableCount(val value: kotlin.Int?)

// ── Tag classes (receivers for infix `from`) ──

class FixtWithNullableIdTag internal constructor()
class FixtWithNullableNameTag internal constructor()
class FixtWithNullableCountTag internal constructor()

// ── Infix `from` — wraps raw value or Kap<T> into the tagged wrapper ──

infix fun FixtWithNullableIdTag.from(value: kotlin.Long): FixtWithNullableId = FixtWithNullableId(value)
infix fun FixtWithNullableIdTag.from(kap: Kap<kotlin.Long>): Kap<FixtWithNullableId> = kap.map(::FixtWithNullableId)

infix fun FixtWithNullableNameTag.from(value: kotlin.String?): FixtWithNullableName = FixtWithNullableName(value)
infix fun FixtWithNullableNameTag.from(kap: Kap<kotlin.String?>): Kap<FixtWithNullableName> = kap.map(::FixtWithNullableName)

infix fun FixtWithNullableCountTag.from(value: kotlin.Int?): FixtWithNullableCount = FixtWithNullableCount(value)
infix fun FixtWithNullableCountTag.from(kap: Kap<kotlin.Int?>): Kap<FixtWithNullableCount> = kap.map(::FixtWithNullableCount)

// ── Per-slot interfaces (lambda receivers for `.with` / `.then`) ──

interface FixtWithNullableIdSlot { val id: FixtWithNullableIdTag }
interface FixtWithNullableNameSlot { val name: FixtWithNullableNameTag }
interface FixtWithNullableCountSlot { val count: FixtWithNullableCountTag }

/** Scoped builder for @KapTypeSafe FixtWithNullable. Implements every slot interface
 *  so each field is reachable as a member. The per-slot `.with` overloads
 *  below narrow the lambda receiver to a single tag — the IDE shows only the
 *  field expected at the current curry position when the body is empty.
 *
 *  The wrapper deliberately does NOT delegate to `Kap<F>`. If it did, the
 *  imported `Kap.with(suspend () -> A)` would compete with the slot-specific
 *  `.with { field from … }` and K2's overload resolution sometimes picks the
 *  generic one (before typechecking the lambda body), causing the slot's tag
 *  reference to fail with `Unresolved reference`.
 *
 *  The wrapper implements `KapLike<F>`, so kap-core operators (.map /
 *  .recover / .timeout / .settled / .memoize / .timed / .andThen /
 *  .evalGraph) are available directly on partial wrappers as well. For raw
 *  `Kap<F>` (e.g. an external API parameter), use `.asKap`.
 */
class FixtWithNullableKap<F>(@PublishedApi internal val _kap: Kap<F>) : KapLike<F>, FixtWithNullableIdSlot, FixtWithNullableNameSlot, FixtWithNullableCountSlot {
    override val asKap: Kap<F> get() = _kap
    override val id: FixtWithNullableIdTag = FixtWithNullableIdTag()
    override val name: FixtWithNullableNameTag = FixtWithNullableNameTag()
    override val count: FixtWithNullableCountTag = FixtWithNullableCountTag()

    companion object {
        val id: FixtWithNullableIdTag = FixtWithNullableIdTag()
        val name: FixtWithNullableNameTag = FixtWithNullableNameTag()
        val count: FixtWithNullableCountTag = FixtWithNullableCountTag()
    }
}

// ── Per-slot operators — IDE shows exactly the field expected at this position ──

@kotlin.jvm.JvmName("with_id")
inline infix fun <Rest> FixtWithNullableKap<(FixtWithNullableId) -> Rest>.with(
    crossinline fa: suspend FixtWithNullableIdSlot.() -> FixtWithNullableId,
): FixtWithNullableKap<Rest> {
    val self = this
    return FixtWithNullableKap(self._kap.with(suspend { self.fa() }))
}

@kotlin.jvm.JvmName("then_id")
inline infix fun <Rest> FixtWithNullableKap<(FixtWithNullableId) -> Rest>.then(
    crossinline fa: suspend FixtWithNullableIdSlot.() -> FixtWithNullableId,
): FixtWithNullableKap<Rest> {
    val self = this
    return FixtWithNullableKap(self._kap.then(suspend { self.fa() }))
}

@kotlin.jvm.JvmName("thenValue_id")
inline infix fun <Rest> FixtWithNullableKap<(FixtWithNullableId) -> Rest>.thenValue(
    crossinline fa: suspend FixtWithNullableIdSlot.() -> FixtWithNullableId,
): FixtWithNullableKap<Rest> {
    val self = this
    return FixtWithNullableKap(self._kap.thenValue(suspend { self.fa() }))
}

@kotlin.jvm.JvmName("with_name")
inline infix fun <Rest> FixtWithNullableKap<(FixtWithNullableName) -> Rest>.with(
    crossinline fa: suspend FixtWithNullableNameSlot.() -> FixtWithNullableName,
): FixtWithNullableKap<Rest> {
    val self = this
    return FixtWithNullableKap(self._kap.with(suspend { self.fa() }))
}

@kotlin.jvm.JvmName("then_name")
inline infix fun <Rest> FixtWithNullableKap<(FixtWithNullableName) -> Rest>.then(
    crossinline fa: suspend FixtWithNullableNameSlot.() -> FixtWithNullableName,
): FixtWithNullableKap<Rest> {
    val self = this
    return FixtWithNullableKap(self._kap.then(suspend { self.fa() }))
}

@kotlin.jvm.JvmName("thenValue_name")
inline infix fun <Rest> FixtWithNullableKap<(FixtWithNullableName) -> Rest>.thenValue(
    crossinline fa: suspend FixtWithNullableNameSlot.() -> FixtWithNullableName,
): FixtWithNullableKap<Rest> {
    val self = this
    return FixtWithNullableKap(self._kap.thenValue(suspend { self.fa() }))
}

@kotlin.jvm.JvmName("with_count")
inline infix fun FixtWithNullableKap<(FixtWithNullableCount) -> FixtWithNullable>.with(
    crossinline fa: suspend FixtWithNullableCountSlot.() -> FixtWithNullableCount,
): Kap<FixtWithNullable> {
    val self = this
    return self._kap.with(suspend { self.fa() })
}

@kotlin.jvm.JvmName("then_count")
inline infix fun FixtWithNullableKap<(FixtWithNullableCount) -> FixtWithNullable>.then(
    crossinline fa: suspend FixtWithNullableCountSlot.() -> FixtWithNullableCount,
): Kap<FixtWithNullable> {
    val self = this
    return self._kap.then(suspend { self.fa() })
}

@kotlin.jvm.JvmName("thenValue_count")
inline infix fun FixtWithNullableKap<(FixtWithNullableCount) -> FixtWithNullable>.thenValue(
    crossinline fa: suspend FixtWithNullableCountSlot.() -> FixtWithNullableCount,
): Kap<FixtWithNullable> {
    val self = this
    return self._kap.thenValue(suspend { self.fa() })
}

infix fun <A, B> FixtWithNullableKap<(A) -> B>.with(fa: Kap<A>): FixtWithNullableKap<B> =
    FixtWithNullableKap(_kap.with(fa))

infix fun <A, B> FixtWithNullableKap<(A) -> B>.then(fa: Kap<A>): FixtWithNullableKap<B> =
    FixtWithNullableKap(_kap.then(fa))

infix fun <A, B> FixtWithNullableKap<(A) -> B>.thenValue(fa: Kap<A>): FixtWithNullableKap<B> =
    FixtWithNullableKap(_kap.thenValue(fa))

infix fun FixtWithNullableKap<(FixtWithNullableCount) -> FixtWithNullable>.with(fa: Kap<FixtWithNullableCount>): Kap<FixtWithNullable> =
    _kap.with(fa)

infix fun FixtWithNullableKap<(FixtWithNullableCount) -> FixtWithNullable>.then(fa: Kap<FixtWithNullableCount>): Kap<FixtWithNullable> =
    _kap.then(fa)

infix fun FixtWithNullableKap<(FixtWithNullableCount) -> FixtWithNullable>.thenValue(fa: Kap<FixtWithNullableCount>): Kap<FixtWithNullable> =
    _kap.thenValue(fa)

inline infix fun <A, B> FixtWithNullableKap<A>.andThen(
    crossinline f: (A) -> Kap<B>,
): Kap<B> = _kap.andThen(f)

suspend fun <A> FixtWithNullableKap<A>.evalGraph(): A = _kap.evalGraph()


/** Official entry point — returns FixtWithNullableKap so `.with { field from value }` works without imports. */
fun kap(f: (kotlin.Long, kotlin.String?, kotlin.Int?) -> FixtWithNullable): FixtWithNullableKap<(FixtWithNullableId) -> (FixtWithNullableName) -> (FixtWithNullableCount) -> FixtWithNullable> =
    FixtWithNullableKap(Kap.of({ p0: FixtWithNullableId -> { p1: FixtWithNullableName -> { p2: FixtWithNullableCount -> f(p0.value, p1.value, p2.value) } } }))
