// AUTO-GENERATED by kap-ksp — do not edit
import kap.Kap
import kap.KapLike
import kap.of
import kap.with
import kap.then
import kap.thenValue
import kap.map
import kap.andThen
import kap.evalGraph

// ── Opaque wrappers — one per field ──

data class FixtWithGenericItems(val value: kotlin.collections.List<kotlin.String>)

data class FixtWithGenericCounts(val value: kotlin.collections.Map<kotlin.String, kotlin.Int>)

data class FixtWithGenericCount(val value: kotlin.Int)

// ── Tag classes (receivers for infix `from`) ──

class FixtWithGenericItemsTag internal constructor()
class FixtWithGenericCountsTag internal constructor()
class FixtWithGenericCountTag internal constructor()

// ── Infix `from` — wraps raw value or Kap<T> into the tagged wrapper ──

infix fun FixtWithGenericItemsTag.from(value: kotlin.collections.List<kotlin.String>): FixtWithGenericItems = FixtWithGenericItems(value)
infix fun FixtWithGenericItemsTag.from(kap: Kap<kotlin.collections.List<kotlin.String>>): Kap<FixtWithGenericItems> = kap.map(::FixtWithGenericItems)

infix fun FixtWithGenericCountsTag.from(value: kotlin.collections.Map<kotlin.String, kotlin.Int>): FixtWithGenericCounts = FixtWithGenericCounts(value)
infix fun FixtWithGenericCountsTag.from(kap: Kap<kotlin.collections.Map<kotlin.String, kotlin.Int>>): Kap<FixtWithGenericCounts> = kap.map(::FixtWithGenericCounts)

infix fun FixtWithGenericCountTag.from(value: kotlin.Int): FixtWithGenericCount = FixtWithGenericCount(value)
infix fun FixtWithGenericCountTag.from(kap: Kap<kotlin.Int>): Kap<FixtWithGenericCount> = kap.map(::FixtWithGenericCount)

// ── Per-slot interfaces (lambda receivers for `.with` / `.then`) ──

interface FixtWithGenericItemsSlot { val items: FixtWithGenericItemsTag }
interface FixtWithGenericCountsSlot { val counts: FixtWithGenericCountsTag }
interface FixtWithGenericCountSlot { val count: FixtWithGenericCountTag }

/** Scoped builder for @KapTypeSafe FixtWithGeneric. Implements every slot interface
 *  so each field is reachable as a member. The per-slot `.with` overloads
 *  below narrow the lambda receiver to a single tag — the IDE shows only the
 *  field expected at the current curry position when the body is empty.
 *
 *  The wrapper deliberately does NOT delegate to `Kap<F>`. If it did, the
 *  imported `Kap.with(suspend () -> A)` would compete with the slot-specific
 *  `.with { field from … }` and K2's overload resolution sometimes picks the
 *  generic one (before typechecking the lambda body), causing the slot's tag
 *  reference to fail with `Unresolved reference`.
 *
 *  The wrapper implements `KapLike<F>`, so kap-core operators (.map /
 *  .recover / .timeout / .settled / .memoize / .timed / .andThen /
 *  .evalGraph) are available directly on partial wrappers as well. For raw
 *  `Kap<F>` (e.g. an external API parameter), use `.asKap`.
 */
class FixtWithGenericKap<F>(@PublishedApi internal val _kap: Kap<F>) : KapLike<F>, FixtWithGenericItemsSlot, FixtWithGenericCountsSlot, FixtWithGenericCountSlot {
    override val asKap: Kap<F> get() = _kap
    override val items: FixtWithGenericItemsTag = FixtWithGenericItemsTag()
    override val counts: FixtWithGenericCountsTag = FixtWithGenericCountsTag()
    override val count: FixtWithGenericCountTag = FixtWithGenericCountTag()

    companion object {
        val items: FixtWithGenericItemsTag = FixtWithGenericItemsTag()
        val counts: FixtWithGenericCountsTag = FixtWithGenericCountsTag()
        val count: FixtWithGenericCountTag = FixtWithGenericCountTag()
    }
}

// ── Per-slot operators — IDE shows exactly the field expected at this position ──

@kotlin.jvm.JvmName("with_items")
inline infix fun <Rest> FixtWithGenericKap<(FixtWithGenericItems) -> Rest>.with(
    crossinline fa: suspend FixtWithGenericItemsSlot.() -> FixtWithGenericItems,
): FixtWithGenericKap<Rest> {
    val self = this
    return FixtWithGenericKap(self._kap.with(suspend { self.fa() }))
}

@kotlin.jvm.JvmName("then_items")
inline infix fun <Rest> FixtWithGenericKap<(FixtWithGenericItems) -> Rest>.then(
    crossinline fa: suspend FixtWithGenericItemsSlot.() -> FixtWithGenericItems,
): FixtWithGenericKap<Rest> {
    val self = this
    return FixtWithGenericKap(self._kap.then(suspend { self.fa() }))
}

@kotlin.jvm.JvmName("thenValue_items")
inline infix fun <Rest> FixtWithGenericKap<(FixtWithGenericItems) -> Rest>.thenValue(
    crossinline fa: suspend FixtWithGenericItemsSlot.() -> FixtWithGenericItems,
): FixtWithGenericKap<Rest> {
    val self = this
    return FixtWithGenericKap(self._kap.thenValue(suspend { self.fa() }))
}

@kotlin.jvm.JvmName("with_counts")
inline infix fun <Rest> FixtWithGenericKap<(FixtWithGenericCounts) -> Rest>.with(
    crossinline fa: suspend FixtWithGenericCountsSlot.() -> FixtWithGenericCounts,
): FixtWithGenericKap<Rest> {
    val self = this
    return FixtWithGenericKap(self._kap.with(suspend { self.fa() }))
}

@kotlin.jvm.JvmName("then_counts")
inline infix fun <Rest> FixtWithGenericKap<(FixtWithGenericCounts) -> Rest>.then(
    crossinline fa: suspend FixtWithGenericCountsSlot.() -> FixtWithGenericCounts,
): FixtWithGenericKap<Rest> {
    val self = this
    return FixtWithGenericKap(self._kap.then(suspend { self.fa() }))
}

@kotlin.jvm.JvmName("thenValue_counts")
inline infix fun <Rest> FixtWithGenericKap<(FixtWithGenericCounts) -> Rest>.thenValue(
    crossinline fa: suspend FixtWithGenericCountsSlot.() -> FixtWithGenericCounts,
): FixtWithGenericKap<Rest> {
    val self = this
    return FixtWithGenericKap(self._kap.thenValue(suspend { self.fa() }))
}

@kotlin.jvm.JvmName("with_count")
inline infix fun FixtWithGenericKap<(FixtWithGenericCount) -> FixtWithGeneric>.with(
    crossinline fa: suspend FixtWithGenericCountSlot.() -> FixtWithGenericCount,
): Kap<FixtWithGeneric> {
    val self = this
    return self._kap.with(suspend { self.fa() })
}

@kotlin.jvm.JvmName("then_count")
inline infix fun FixtWithGenericKap<(FixtWithGenericCount) -> FixtWithGeneric>.then(
    crossinline fa: suspend FixtWithGenericCountSlot.() -> FixtWithGenericCount,
): Kap<FixtWithGeneric> {
    val self = this
    return self._kap.then(suspend { self.fa() })
}

@kotlin.jvm.JvmName("thenValue_count")
inline infix fun FixtWithGenericKap<(FixtWithGenericCount) -> FixtWithGeneric>.thenValue(
    crossinline fa: suspend FixtWithGenericCountSlot.() -> FixtWithGenericCount,
): Kap<FixtWithGeneric> {
    val self = this
    return self._kap.thenValue(suspend { self.fa() })
}

infix fun <A, B> FixtWithGenericKap<(A) -> B>.with(fa: Kap<A>): FixtWithGenericKap<B> =
    FixtWithGenericKap(_kap.with(fa))

infix fun <A, B> FixtWithGenericKap<(A) -> B>.then(fa: Kap<A>): FixtWithGenericKap<B> =
    FixtWithGenericKap(_kap.then(fa))

infix fun <A, B> FixtWithGenericKap<(A) -> B>.thenValue(fa: Kap<A>): FixtWithGenericKap<B> =
    FixtWithGenericKap(_kap.thenValue(fa))

infix fun FixtWithGenericKap<(FixtWithGenericCount) -> FixtWithGeneric>.with(fa: Kap<FixtWithGenericCount>): Kap<FixtWithGeneric> =
    _kap.with(fa)

infix fun FixtWithGenericKap<(FixtWithGenericCount) -> FixtWithGeneric>.then(fa: Kap<FixtWithGenericCount>): Kap<FixtWithGeneric> =
    _kap.then(fa)

infix fun FixtWithGenericKap<(FixtWithGenericCount) -> FixtWithGeneric>.thenValue(fa: Kap<FixtWithGenericCount>): Kap<FixtWithGeneric> =
    _kap.thenValue(fa)

inline infix fun <A, B> FixtWithGenericKap<A>.andThen(
    crossinline f: (A) -> Kap<B>,
): Kap<B> = _kap.andThen(f)

suspend fun <A> FixtWithGenericKap<A>.evalGraph(): A = _kap.evalGraph()


/** Official entry point — returns FixtWithGenericKap so `.with { field from value }` works without imports. */
fun kap(f: (kotlin.collections.List<kotlin.String>, kotlin.collections.Map<kotlin.String, kotlin.Int>, kotlin.Int) -> FixtWithGeneric): FixtWithGenericKap<(FixtWithGenericItems) -> (FixtWithGenericCounts) -> (FixtWithGenericCount) -> FixtWithGeneric> =
    FixtWithGenericKap(Kap.of({ p0: FixtWithGenericItems -> { p1: FixtWithGenericCounts -> { p2: FixtWithGenericCount -> f(p0.value, p1.value, p2.value) } } }))
