// AUTO-GENERATED by kap-ksp — do not edit
import arrow.core.Either
import arrow.core.NonEmptyList
import kap.Kap
import kap.KapLike
import kap.of
import kap.withV
import kap.thenV
import kap.thenValueV
import kap.evalGraph

// ── Validated infix `from` — maps Either<Nel<E>, FieldType> into tagged wrapper ──

infix fun <E, T> FixtGenWrapFnInnerTag.from(value: Either<NonEmptyList<E>, T>): Either<NonEmptyList<E>, FixtGenWrapFnInner<T>> =
    value.map(::FixtGenWrapFnInner)

/** Validated scoped builder for @KapTypeSafe FixtGenWrapFn. Uses the same per-slot
 *  tag interfaces as FixtGenWrapFnKap — each `.withV { field from validateField() }`
 *  narrows the receiver to one slot, accumulating errors via Arrow's applicative.
 */
class FixtGenWrapFnValidatedKap<E, F>(@PublishedApi internal val _kap: Kap<Either<NonEmptyList<E>, F>>) : KapLike<Either<NonEmptyList<E>, F>>, FixtGenWrapFnInnerSlot {
    override val asKap: Kap<Either<NonEmptyList<E>, F>> get() = _kap
    override val inner: FixtGenWrapFnInnerTag = FixtGenWrapFnInnerTag()

    companion object {
        val inner: FixtGenWrapFnInnerTag = FixtGenWrapFnInnerTag()
    }
}

// ── Per-slot .withV / .thenV / .thenValueV operators ──

@kotlin.jvm.JvmName("withV_inner")
inline infix fun <E, T> FixtGenWrapFnValidatedKap<E, (FixtGenWrapFnInner<T>) -> FixtGenWrap<T>>.withV(
    crossinline fa: suspend FixtGenWrapFnInnerSlot.() -> Either<NonEmptyList<E>, FixtGenWrapFnInner<T>>,
): Kap<Either<NonEmptyList<E>, FixtGenWrap<T>>> {
    val self = this
    return self._kap.withV(Kap { self.fa() })
}

@kotlin.jvm.JvmName("thenV_inner")
inline infix fun <E, T> FixtGenWrapFnValidatedKap<E, (FixtGenWrapFnInner<T>) -> FixtGenWrap<T>>.thenV(
    crossinline fa: suspend FixtGenWrapFnInnerSlot.() -> Either<NonEmptyList<E>, FixtGenWrapFnInner<T>>,
): Kap<Either<NonEmptyList<E>, FixtGenWrap<T>>> {
    val self = this
    return self._kap.thenV(Kap { self.fa() })
}

@kotlin.jvm.JvmName("thenValueV_inner")
inline infix fun <E, T> FixtGenWrapFnValidatedKap<E, (FixtGenWrapFnInner<T>) -> FixtGenWrap<T>>.thenValueV(
    crossinline fa: suspend FixtGenWrapFnInnerSlot.() -> Either<NonEmptyList<E>, FixtGenWrapFnInner<T>>,
): Kap<Either<NonEmptyList<E>, FixtGenWrap<T>>> {
    val self = this
    return self._kap.thenValueV(Kap { self.fa() })
}

infix fun <E, A, B> FixtGenWrapFnValidatedKap<E, (A) -> B>.withV(fa: Kap<Either<NonEmptyList<E>, A>>): FixtGenWrapFnValidatedKap<E, B> =
    FixtGenWrapFnValidatedKap(_kap.withV(fa))

infix fun <E, A, B> FixtGenWrapFnValidatedKap<E, (A) -> B>.thenV(fa: Kap<Either<NonEmptyList<E>, A>>): FixtGenWrapFnValidatedKap<E, B> =
    FixtGenWrapFnValidatedKap(_kap.thenV(fa))

infix fun <E, A, B> FixtGenWrapFnValidatedKap<E, (A) -> B>.thenValueV(fa: Kap<Either<NonEmptyList<E>, A>>): FixtGenWrapFnValidatedKap<E, B> =
    FixtGenWrapFnValidatedKap(_kap.thenValueV(fa))

infix fun <E, T> FixtGenWrapFnValidatedKap<E, (FixtGenWrapFnInner<T>) -> FixtGenWrap<T>>.withV(fa: Kap<Either<NonEmptyList<E>, FixtGenWrapFnInner<T>>>): Kap<Either<NonEmptyList<E>, FixtGenWrap<T>>> =
    _kap.withV(fa)

infix fun <E, T> FixtGenWrapFnValidatedKap<E, (FixtGenWrapFnInner<T>) -> FixtGenWrap<T>>.thenV(fa: Kap<Either<NonEmptyList<E>, FixtGenWrapFnInner<T>>>): Kap<Either<NonEmptyList<E>, FixtGenWrap<T>>> =
    _kap.thenV(fa)

infix fun <E, T> FixtGenWrapFnValidatedKap<E, (FixtGenWrapFnInner<T>) -> FixtGenWrap<T>>.thenValueV(fa: Kap<Either<NonEmptyList<E>, FixtGenWrapFnInner<T>>>): Kap<Either<NonEmptyList<E>, FixtGenWrap<T>>> =
    _kap.thenValueV(fa)

suspend fun <E, A> FixtGenWrapFnValidatedKap<E, A>.evalGraph(): Either<NonEmptyList<E>, A> = _kap.evalGraph()


/** Validated entry — `kapV(::C)` / `kapV<Double>(::C)` for generics. */
fun <E, T> kapVFixtGenWrapFn(f: (T) -> FixtGenWrap<T>): FixtGenWrapFnValidatedKap<E, (FixtGenWrapFnInner<T>) -> FixtGenWrap<T>> {
    val fn: (FixtGenWrapFnInner<T>) -> FixtGenWrap<T> = { p0: FixtGenWrapFnInner<T> -> f(p0.value) }
    val kap: Kap<Either<NonEmptyList<E>, (FixtGenWrapFnInner<T>) -> FixtGenWrap<T>>> = Kap.of(Either.Right(fn))
    return FixtGenWrapFnValidatedKap(kap)
}

/** Generic zero-arg alternative — `kapVFixtGenWrapFn<Double>()`. */
fun <E, T> kapVFixtGenWrapFn(): FixtGenWrapFnValidatedKap<E, (FixtGenWrapFnInner<T>) -> FixtGenWrap<T>> {
    val fn: (FixtGenWrapFnInner<T>) -> FixtGenWrap<T> = { p0: FixtGenWrapFnInner<T> -> fixtGenWrapFn(p0.value) }
    val kap: Kap<Either<NonEmptyList<E>, (FixtGenWrapFnInner<T>) -> FixtGenWrap<T>>> = Kap.of(Either.Right(fn))
    return FixtGenWrapFnValidatedKap(kap)
}

