// AUTO-GENERATED by kap-ksp — do not edit
import arrow.core.Either
import arrow.core.NonEmptyList
import kap.Kap
import kap.KapLike
import kap.of
import kap.withV
import kap.thenV
import kap.thenValueV
import kap.evalGraph

// ── Validated infix `from` — maps Either<Nel<E>, FieldType> into tagged wrapper ──

infix fun <E> FixtUniqueATag.from(value: Either<NonEmptyList<E>, kotlin.Int>): Either<NonEmptyList<E>, FixtUniqueA> =
    value.map(::FixtUniqueA)

infix fun <E> FixtUniqueBTag.from(value: Either<NonEmptyList<E>, kotlin.Boolean>): Either<NonEmptyList<E>, FixtUniqueB> =
    value.map(::FixtUniqueB)

/** Validated scoped builder for @KapTypeSafe FixtUnique. Uses the same per-slot
 *  tag interfaces as FixtUniqueKap — each `.withV { field from validateField() }`
 *  narrows the receiver to one slot, accumulating errors via Arrow's applicative.
 */
class FixtUniqueValidatedKap<E, F>(@PublishedApi internal val _kap: Kap<Either<NonEmptyList<E>, F>>) : KapLike<Either<NonEmptyList<E>, F>>, FixtUniqueASlot, FixtUniqueBSlot {
    override val asKap: Kap<Either<NonEmptyList<E>, F>> get() = _kap
    override val a: FixtUniqueATag = FixtUniqueATag()
    override val b: FixtUniqueBTag = FixtUniqueBTag()

    companion object {
        val a: FixtUniqueATag = FixtUniqueATag()
        val b: FixtUniqueBTag = FixtUniqueBTag()
    }
}

// ── Per-slot .withV / .thenV / .thenValueV operators ──

@kotlin.jvm.JvmName("withV_a")
inline infix fun <E, Rest> FixtUniqueValidatedKap<E, (FixtUniqueA) -> Rest>.withV(
    crossinline fa: suspend FixtUniqueASlot.() -> Either<NonEmptyList<E>, FixtUniqueA>,
): FixtUniqueValidatedKap<E, Rest> {
    val self = this
    return FixtUniqueValidatedKap(self._kap.withV(Kap { self.fa() }))
}

@kotlin.jvm.JvmName("thenV_a")
inline infix fun <E, Rest> FixtUniqueValidatedKap<E, (FixtUniqueA) -> Rest>.thenV(
    crossinline fa: suspend FixtUniqueASlot.() -> Either<NonEmptyList<E>, FixtUniqueA>,
): FixtUniqueValidatedKap<E, Rest> {
    val self = this
    return FixtUniqueValidatedKap(self._kap.thenV(Kap { self.fa() }))
}

@kotlin.jvm.JvmName("thenValueV_a")
inline infix fun <E, Rest> FixtUniqueValidatedKap<E, (FixtUniqueA) -> Rest>.thenValueV(
    crossinline fa: suspend FixtUniqueASlot.() -> Either<NonEmptyList<E>, FixtUniqueA>,
): FixtUniqueValidatedKap<E, Rest> {
    val self = this
    return FixtUniqueValidatedKap(self._kap.thenValueV(Kap { self.fa() }))
}

@kotlin.jvm.JvmName("withV_b")
inline infix fun <E> FixtUniqueValidatedKap<E, (FixtUniqueB) -> kotlin.String>.withV(
    crossinline fa: suspend FixtUniqueBSlot.() -> Either<NonEmptyList<E>, FixtUniqueB>,
): Kap<Either<NonEmptyList<E>, kotlin.String>> {
    val self = this
    return self._kap.withV(Kap { self.fa() })
}

@kotlin.jvm.JvmName("thenV_b")
inline infix fun <E> FixtUniqueValidatedKap<E, (FixtUniqueB) -> kotlin.String>.thenV(
    crossinline fa: suspend FixtUniqueBSlot.() -> Either<NonEmptyList<E>, FixtUniqueB>,
): Kap<Either<NonEmptyList<E>, kotlin.String>> {
    val self = this
    return self._kap.thenV(Kap { self.fa() })
}

@kotlin.jvm.JvmName("thenValueV_b")
inline infix fun <E> FixtUniqueValidatedKap<E, (FixtUniqueB) -> kotlin.String>.thenValueV(
    crossinline fa: suspend FixtUniqueBSlot.() -> Either<NonEmptyList<E>, FixtUniqueB>,
): Kap<Either<NonEmptyList<E>, kotlin.String>> {
    val self = this
    return self._kap.thenValueV(Kap { self.fa() })
}

infix fun <E, A, B> FixtUniqueValidatedKap<E, (A) -> B>.withV(fa: Kap<Either<NonEmptyList<E>, A>>): FixtUniqueValidatedKap<E, B> =
    FixtUniqueValidatedKap(_kap.withV(fa))

infix fun <E, A, B> FixtUniqueValidatedKap<E, (A) -> B>.thenV(fa: Kap<Either<NonEmptyList<E>, A>>): FixtUniqueValidatedKap<E, B> =
    FixtUniqueValidatedKap(_kap.thenV(fa))

infix fun <E, A, B> FixtUniqueValidatedKap<E, (A) -> B>.thenValueV(fa: Kap<Either<NonEmptyList<E>, A>>): FixtUniqueValidatedKap<E, B> =
    FixtUniqueValidatedKap(_kap.thenValueV(fa))

infix fun <E> FixtUniqueValidatedKap<E, (FixtUniqueB) -> kotlin.String>.withV(fa: Kap<Either<NonEmptyList<E>, FixtUniqueB>>): Kap<Either<NonEmptyList<E>, kotlin.String>> =
    _kap.withV(fa)

infix fun <E> FixtUniqueValidatedKap<E, (FixtUniqueB) -> kotlin.String>.thenV(fa: Kap<Either<NonEmptyList<E>, FixtUniqueB>>): Kap<Either<NonEmptyList<E>, kotlin.String>> =
    _kap.thenV(fa)

infix fun <E> FixtUniqueValidatedKap<E, (FixtUniqueB) -> kotlin.String>.thenValueV(fa: Kap<Either<NonEmptyList<E>, FixtUniqueB>>): Kap<Either<NonEmptyList<E>, kotlin.String>> =
    _kap.thenValueV(fa)

suspend fun <E, A> FixtUniqueValidatedKap<E, A>.evalGraph(): Either<NonEmptyList<E>, A> = _kap.evalGraph()


/** Validated entry — returns FixtUniqueValidatedKap so `.withV { field from validate() }` works without imports. */
fun <E> kapV(f: (kotlin.Int, kotlin.Boolean) -> kotlin.String): FixtUniqueValidatedKap<E, (FixtUniqueA) -> (FixtUniqueB) -> kotlin.String> {
    val fn: (FixtUniqueA) -> (FixtUniqueB) -> kotlin.String = { p0: FixtUniqueA -> { p1: FixtUniqueB -> f(p0.value, p1.value) } }
    val kap: Kap<Either<NonEmptyList<E>, (FixtUniqueA) -> (FixtUniqueB) -> kotlin.String>> = Kap.of(Either.Right(fn))
    return FixtUniqueValidatedKap(kap)
}
