// AUTO-GENERATED by kap-ksp — do not edit
import kap.Kap
import kap.KapLike
import kap.of
import kap.with
import kap.then
import kap.thenValue
import kap.map
import kap.andThen
import kap.evalGraph

// ── Opaque wrappers — one per field ──

data class FixtGenericLabel(val value: kotlin.String)

data class FixtGenericAmount<T>(val value: T)

// ── Tag classes (receivers for infix `from`) ──

class FixtGenericLabelTag internal constructor()
class FixtGenericAmountTag internal constructor()

// ── Infix `from` — wraps raw value or Kap<T> into the tagged wrapper ──

infix fun FixtGenericLabelTag.from(value: kotlin.String): FixtGenericLabel = FixtGenericLabel(value)
infix fun FixtGenericLabelTag.from(kap: Kap<kotlin.String>): Kap<FixtGenericLabel> = kap.map(::FixtGenericLabel)

infix fun <T> FixtGenericAmountTag.from(value: T): FixtGenericAmount<T> = FixtGenericAmount(value)
infix fun <T> FixtGenericAmountTag.from(kap: Kap<T>): Kap<FixtGenericAmount<T>> = kap.map(::FixtGenericAmount)

// ── Per-slot interfaces (lambda receivers for `.with` / `.then`) ──

interface FixtGenericLabelSlot { val label: FixtGenericLabelTag }
interface FixtGenericAmountSlot { val amount: FixtGenericAmountTag }

/** Scoped builder for @KapTypeSafe FixtGeneric. Implements every slot interface
 *  so each field is reachable as a member. The per-slot `.with` overloads
 *  below narrow the lambda receiver to a single tag — the IDE shows only the
 *  field expected at the current curry position when the body is empty.
 *
 *  The wrapper deliberately does NOT delegate to `Kap<F>`. If it did, the
 *  imported `Kap.with(suspend () -> A)` would compete with the slot-specific
 *  `.with { field from … }` and K2's overload resolution sometimes picks the
 *  generic one (before typechecking the lambda body), causing the slot's tag
 *  reference to fail with `Unresolved reference`.
 *
 *  The wrapper implements `KapLike<F>`, so kap-core operators (.map /
 *  .recover / .timeout / .settled / .memoize / .timed / .andThen /
 *  .evalGraph) are available directly on partial wrappers as well. For raw
 *  `Kap<F>` (e.g. an external API parameter), use `.asKap`.
 */
class FixtGenericKap<F>(@PublishedApi internal val _kap: Kap<F>) : KapLike<F>, FixtGenericLabelSlot, FixtGenericAmountSlot {
    override val asKap: Kap<F> get() = _kap
    override val label: FixtGenericLabelTag = FixtGenericLabelTag()
    override val amount: FixtGenericAmountTag = FixtGenericAmountTag()

    companion object {
        val label: FixtGenericLabelTag = FixtGenericLabelTag()
        val amount: FixtGenericAmountTag = FixtGenericAmountTag()
    }
}

// ── Per-slot operators — IDE shows exactly the field expected at this position ──

@kotlin.jvm.JvmName("with_label")
inline infix fun <Rest> FixtGenericKap<(FixtGenericLabel) -> Rest>.with(
    crossinline fa: suspend FixtGenericLabelSlot.() -> FixtGenericLabel,
): FixtGenericKap<Rest> {
    val self = this
    return FixtGenericKap(self._kap.with(suspend { self.fa() }))
}

@kotlin.jvm.JvmName("then_label")
inline infix fun <Rest> FixtGenericKap<(FixtGenericLabel) -> Rest>.then(
    crossinline fa: suspend FixtGenericLabelSlot.() -> FixtGenericLabel,
): FixtGenericKap<Rest> {
    val self = this
    return FixtGenericKap(self._kap.then(suspend { self.fa() }))
}

@kotlin.jvm.JvmName("thenValue_label")
inline infix fun <Rest> FixtGenericKap<(FixtGenericLabel) -> Rest>.thenValue(
    crossinline fa: suspend FixtGenericLabelSlot.() -> FixtGenericLabel,
): FixtGenericKap<Rest> {
    val self = this
    return FixtGenericKap(self._kap.thenValue(suspend { self.fa() }))
}

@kotlin.jvm.JvmName("with_amount")
inline infix fun <T> FixtGenericKap<(FixtGenericAmount<T>) -> FixtGeneric<T>>.with(
    crossinline fa: suspend FixtGenericAmountSlot.() -> FixtGenericAmount<T>,
): Kap<FixtGeneric<T>> {
    val self = this
    return self._kap.with(suspend { self.fa() })
}

@kotlin.jvm.JvmName("then_amount")
inline infix fun <T> FixtGenericKap<(FixtGenericAmount<T>) -> FixtGeneric<T>>.then(
    crossinline fa: suspend FixtGenericAmountSlot.() -> FixtGenericAmount<T>,
): Kap<FixtGeneric<T>> {
    val self = this
    return self._kap.then(suspend { self.fa() })
}

@kotlin.jvm.JvmName("thenValue_amount")
inline infix fun <T> FixtGenericKap<(FixtGenericAmount<T>) -> FixtGeneric<T>>.thenValue(
    crossinline fa: suspend FixtGenericAmountSlot.() -> FixtGenericAmount<T>,
): Kap<FixtGeneric<T>> {
    val self = this
    return self._kap.thenValue(suspend { self.fa() })
}

infix fun <A, B> FixtGenericKap<(A) -> B>.with(fa: Kap<A>): FixtGenericKap<B> =
    FixtGenericKap(_kap.with(fa))

infix fun <A, B> FixtGenericKap<(A) -> B>.then(fa: Kap<A>): FixtGenericKap<B> =
    FixtGenericKap(_kap.then(fa))

infix fun <A, B> FixtGenericKap<(A) -> B>.thenValue(fa: Kap<A>): FixtGenericKap<B> =
    FixtGenericKap(_kap.thenValue(fa))

infix fun <T> FixtGenericKap<(FixtGenericAmount<T>) -> FixtGeneric<T>>.with(fa: Kap<FixtGenericAmount<T>>): Kap<FixtGeneric<T>> =
    _kap.with(fa)

infix fun <T> FixtGenericKap<(FixtGenericAmount<T>) -> FixtGeneric<T>>.then(fa: Kap<FixtGenericAmount<T>>): Kap<FixtGeneric<T>> =
    _kap.then(fa)

infix fun <T> FixtGenericKap<(FixtGenericAmount<T>) -> FixtGeneric<T>>.thenValue(fa: Kap<FixtGenericAmount<T>>): Kap<FixtGeneric<T>> =
    _kap.thenValue(fa)

inline infix fun <A, B> FixtGenericKap<A>.andThen(
    crossinline f: (A) -> Kap<B>,
): Kap<B> = _kap.andThen(f)

suspend fun <A> FixtGenericKap<A>.evalGraph(): A = _kap.evalGraph()


/** Official entry — `kap(::C)` plain, `kap<Double>(::C)` for generics. */
fun <T> kap(f: (kotlin.String, T) -> FixtGeneric<T>): FixtGenericKap<(FixtGenericLabel) -> (FixtGenericAmount<T>) -> FixtGeneric<T>> =
    FixtGenericKap(Kap.of({ p0: FixtGenericLabel -> { p1: FixtGenericAmount<T> -> f(p0.value, p1.value) } }))

/** Generic zero-arg alternative — `kapFixtGeneric<Double>()`. */
fun <T> kapFixtGeneric(): FixtGenericKap<(FixtGenericLabel) -> (FixtGenericAmount<T>) -> FixtGeneric<T>> =
    FixtGenericKap(Kap.of({ p0: FixtGenericLabel -> { p1: FixtGenericAmount<T> -> FixtGeneric(p0.value, p1.value) } }))

