// AUTO-GENERATED by kap-ksp — do not edit
import kap.Kap
import kap.KapLike
import kap.of
import kap.with
import kap.then
import kap.thenValue
import kap.map
import kap.andThen
import kap.evalGraph

// ── Opaque wrappers — one per field ──

data class FixtGenWrapInner<T>(val value: T)

// ── Tag classes (receivers for infix `from`) ──

class FixtGenWrapInnerTag internal constructor()

// ── Infix `from` — wraps raw value or Kap<T> into the tagged wrapper ──

infix fun <T> FixtGenWrapInnerTag.from(value: T): FixtGenWrapInner<T> = FixtGenWrapInner(value)
infix fun <T> FixtGenWrapInnerTag.from(kap: Kap<T>): Kap<FixtGenWrapInner<T>> = kap.map(::FixtGenWrapInner)

// ── Per-slot interfaces (lambda receivers for `.with` / `.then`) ──

interface FixtGenWrapInnerSlot { val inner: FixtGenWrapInnerTag }

/** Scoped builder for @KapTypeSafe FixtGenWrap. Implements every slot interface
 *  so each field is reachable as a member. The per-slot `.with` overloads
 *  below narrow the lambda receiver to a single tag — the IDE shows only the
 *  field expected at the current curry position when the body is empty.
 *
 *  The wrapper deliberately does NOT delegate to `Kap<F>`. If it did, the
 *  imported `Kap.with(suspend () -> A)` would compete with the slot-specific
 *  `.with { field from … }` and K2's overload resolution sometimes picks the
 *  generic one (before typechecking the lambda body), causing the slot's tag
 *  reference to fail with `Unresolved reference`.
 *
 *  The wrapper implements `KapLike<F>`, so kap-core operators (.map /
 *  .recover / .timeout / .settled / .memoize / .timed / .andThen /
 *  .evalGraph) are available directly on partial wrappers as well. For raw
 *  `Kap<F>` (e.g. an external API parameter), use `.asKap`.
 */
class FixtGenWrapKap<F>(@PublishedApi internal val _kap: Kap<F>) : KapLike<F>, FixtGenWrapInnerSlot {
    override val asKap: Kap<F> get() = _kap
    override val inner: FixtGenWrapInnerTag = FixtGenWrapInnerTag()

    companion object {
        val inner: FixtGenWrapInnerTag = FixtGenWrapInnerTag()
    }
}

// ── Per-slot operators — IDE shows exactly the field expected at this position ──

@kotlin.jvm.JvmName("with_inner")
inline infix fun <T> FixtGenWrapKap<(FixtGenWrapInner<T>) -> FixtGenWrap<T>>.with(
    crossinline fa: suspend FixtGenWrapInnerSlot.() -> FixtGenWrapInner<T>,
): Kap<FixtGenWrap<T>> {
    val self = this
    return self._kap.with(suspend { self.fa() })
}

@kotlin.jvm.JvmName("then_inner")
inline infix fun <T> FixtGenWrapKap<(FixtGenWrapInner<T>) -> FixtGenWrap<T>>.then(
    crossinline fa: suspend FixtGenWrapInnerSlot.() -> FixtGenWrapInner<T>,
): Kap<FixtGenWrap<T>> {
    val self = this
    return self._kap.then(suspend { self.fa() })
}

@kotlin.jvm.JvmName("thenValue_inner")
inline infix fun <T> FixtGenWrapKap<(FixtGenWrapInner<T>) -> FixtGenWrap<T>>.thenValue(
    crossinline fa: suspend FixtGenWrapInnerSlot.() -> FixtGenWrapInner<T>,
): Kap<FixtGenWrap<T>> {
    val self = this
    return self._kap.thenValue(suspend { self.fa() })
}

infix fun <A, B> FixtGenWrapKap<(A) -> B>.with(fa: Kap<A>): FixtGenWrapKap<B> =
    FixtGenWrapKap(_kap.with(fa))

infix fun <A, B> FixtGenWrapKap<(A) -> B>.then(fa: Kap<A>): FixtGenWrapKap<B> =
    FixtGenWrapKap(_kap.then(fa))

infix fun <A, B> FixtGenWrapKap<(A) -> B>.thenValue(fa: Kap<A>): FixtGenWrapKap<B> =
    FixtGenWrapKap(_kap.thenValue(fa))

infix fun <T> FixtGenWrapKap<(FixtGenWrapInner<T>) -> FixtGenWrap<T>>.with(fa: Kap<FixtGenWrapInner<T>>): Kap<FixtGenWrap<T>> =
    _kap.with(fa)

infix fun <T> FixtGenWrapKap<(FixtGenWrapInner<T>) -> FixtGenWrap<T>>.then(fa: Kap<FixtGenWrapInner<T>>): Kap<FixtGenWrap<T>> =
    _kap.then(fa)

infix fun <T> FixtGenWrapKap<(FixtGenWrapInner<T>) -> FixtGenWrap<T>>.thenValue(fa: Kap<FixtGenWrapInner<T>>): Kap<FixtGenWrap<T>> =
    _kap.thenValue(fa)

inline infix fun <A, B> FixtGenWrapKap<A>.andThen(
    crossinline f: (A) -> Kap<B>,
): Kap<B> = _kap.andThen(f)

suspend fun <A> FixtGenWrapKap<A>.evalGraph(): A = _kap.evalGraph()


/** Official entry — `kap(::C)` plain, `kap<Double>(::C)` for generics. */
fun <T> kapFixtGenWrap(f: (T) -> FixtGenWrap<T>): FixtGenWrapKap<(FixtGenWrapInner<T>) -> FixtGenWrap<T>> =
    FixtGenWrapKap(Kap.of({ p0: FixtGenWrapInner<T> -> f(p0.value) }))

/** Generic zero-arg alternative — `kapFixtGenWrap<Double>()`. */
fun <T> kapFixtGenWrap(): FixtGenWrapKap<(FixtGenWrapInner<T>) -> FixtGenWrap<T>> =
    FixtGenWrapKap(Kap.of({ p0: FixtGenWrapInner<T> -> FixtGenWrap(p0.value) }))

