// AUTO-GENERATED by kap-ksp — do not edit
import arrow.core.Either
import arrow.core.NonEmptyList
import kap.Kap
import kap.KapLike
import kap.of
import kap.withV
import kap.thenV
import kap.thenValueV
import kap.evalGraph

// ── Validated infix `from` — maps Either<Nel<E>, FieldType> into tagged wrapper ──

infix fun <E> FixtGenericLabelTag.from(value: Either<NonEmptyList<E>, kotlin.String>): Either<NonEmptyList<E>, FixtGenericLabel> =
    value.map(::FixtGenericLabel)

infix fun <E, T> FixtGenericAmountTag.from(value: Either<NonEmptyList<E>, T>): Either<NonEmptyList<E>, FixtGenericAmount<T>> =
    value.map(::FixtGenericAmount)

/** Validated scoped builder for @KapTypeSafe FixtGeneric. Uses the same per-slot
 *  tag interfaces as FixtGenericKap — each `.withV { field from validateField() }`
 *  narrows the receiver to one slot, accumulating errors via Arrow's applicative.
 */
class FixtGenericValidatedKap<E, F>(@PublishedApi internal val _kap: Kap<Either<NonEmptyList<E>, F>>) : KapLike<Either<NonEmptyList<E>, F>>, FixtGenericLabelSlot, FixtGenericAmountSlot {
    override val asKap: Kap<Either<NonEmptyList<E>, F>> get() = _kap
    override val label: FixtGenericLabelTag = FixtGenericLabelTag()
    override val amount: FixtGenericAmountTag = FixtGenericAmountTag()

    companion object {
        val label: FixtGenericLabelTag = FixtGenericLabelTag()
        val amount: FixtGenericAmountTag = FixtGenericAmountTag()
    }
}

// ── Per-slot .withV / .thenV / .thenValueV operators ──

@kotlin.jvm.JvmName("withV_label")
inline infix fun <E, Rest> FixtGenericValidatedKap<E, (FixtGenericLabel) -> Rest>.withV(
    crossinline fa: suspend FixtGenericLabelSlot.() -> Either<NonEmptyList<E>, FixtGenericLabel>,
): FixtGenericValidatedKap<E, Rest> {
    val self = this
    return FixtGenericValidatedKap(self._kap.withV(Kap { self.fa() }))
}

@kotlin.jvm.JvmName("thenV_label")
inline infix fun <E, Rest> FixtGenericValidatedKap<E, (FixtGenericLabel) -> Rest>.thenV(
    crossinline fa: suspend FixtGenericLabelSlot.() -> Either<NonEmptyList<E>, FixtGenericLabel>,
): FixtGenericValidatedKap<E, Rest> {
    val self = this
    return FixtGenericValidatedKap(self._kap.thenV(Kap { self.fa() }))
}

@kotlin.jvm.JvmName("thenValueV_label")
inline infix fun <E, Rest> FixtGenericValidatedKap<E, (FixtGenericLabel) -> Rest>.thenValueV(
    crossinline fa: suspend FixtGenericLabelSlot.() -> Either<NonEmptyList<E>, FixtGenericLabel>,
): FixtGenericValidatedKap<E, Rest> {
    val self = this
    return FixtGenericValidatedKap(self._kap.thenValueV(Kap { self.fa() }))
}

@kotlin.jvm.JvmName("withV_amount")
inline infix fun <E, T> FixtGenericValidatedKap<E, (FixtGenericAmount<T>) -> FixtGeneric<T>>.withV(
    crossinline fa: suspend FixtGenericAmountSlot.() -> Either<NonEmptyList<E>, FixtGenericAmount<T>>,
): Kap<Either<NonEmptyList<E>, FixtGeneric<T>>> {
    val self = this
    return self._kap.withV(Kap { self.fa() })
}

@kotlin.jvm.JvmName("thenV_amount")
inline infix fun <E, T> FixtGenericValidatedKap<E, (FixtGenericAmount<T>) -> FixtGeneric<T>>.thenV(
    crossinline fa: suspend FixtGenericAmountSlot.() -> Either<NonEmptyList<E>, FixtGenericAmount<T>>,
): Kap<Either<NonEmptyList<E>, FixtGeneric<T>>> {
    val self = this
    return self._kap.thenV(Kap { self.fa() })
}

@kotlin.jvm.JvmName("thenValueV_amount")
inline infix fun <E, T> FixtGenericValidatedKap<E, (FixtGenericAmount<T>) -> FixtGeneric<T>>.thenValueV(
    crossinline fa: suspend FixtGenericAmountSlot.() -> Either<NonEmptyList<E>, FixtGenericAmount<T>>,
): Kap<Either<NonEmptyList<E>, FixtGeneric<T>>> {
    val self = this
    return self._kap.thenValueV(Kap { self.fa() })
}

infix fun <E, A, B> FixtGenericValidatedKap<E, (A) -> B>.withV(fa: Kap<Either<NonEmptyList<E>, A>>): FixtGenericValidatedKap<E, B> =
    FixtGenericValidatedKap(_kap.withV(fa))

infix fun <E, A, B> FixtGenericValidatedKap<E, (A) -> B>.thenV(fa: Kap<Either<NonEmptyList<E>, A>>): FixtGenericValidatedKap<E, B> =
    FixtGenericValidatedKap(_kap.thenV(fa))

infix fun <E, A, B> FixtGenericValidatedKap<E, (A) -> B>.thenValueV(fa: Kap<Either<NonEmptyList<E>, A>>): FixtGenericValidatedKap<E, B> =
    FixtGenericValidatedKap(_kap.thenValueV(fa))

infix fun <E, T> FixtGenericValidatedKap<E, (FixtGenericAmount<T>) -> FixtGeneric<T>>.withV(fa: Kap<Either<NonEmptyList<E>, FixtGenericAmount<T>>>): Kap<Either<NonEmptyList<E>, FixtGeneric<T>>> =
    _kap.withV(fa)

infix fun <E, T> FixtGenericValidatedKap<E, (FixtGenericAmount<T>) -> FixtGeneric<T>>.thenV(fa: Kap<Either<NonEmptyList<E>, FixtGenericAmount<T>>>): Kap<Either<NonEmptyList<E>, FixtGeneric<T>>> =
    _kap.thenV(fa)

infix fun <E, T> FixtGenericValidatedKap<E, (FixtGenericAmount<T>) -> FixtGeneric<T>>.thenValueV(fa: Kap<Either<NonEmptyList<E>, FixtGenericAmount<T>>>): Kap<Either<NonEmptyList<E>, FixtGeneric<T>>> =
    _kap.thenValueV(fa)

suspend fun <E, A> FixtGenericValidatedKap<E, A>.evalGraph(): Either<NonEmptyList<E>, A> = _kap.evalGraph()


/** Validated entry — returns FixtGenericValidatedKap so `.withV { field from validate() }` works without imports. */
fun <E, T> kapVFixtGeneric(): FixtGenericValidatedKap<E, (FixtGenericLabel) -> (FixtGenericAmount<T>) -> FixtGeneric<T>> {
    val fn: (FixtGenericLabel) -> (FixtGenericAmount<T>) -> FixtGeneric<T> = { p0: FixtGenericLabel -> { p1: FixtGenericAmount<T> -> FixtGeneric(p0.value, p1.value) } }
    val kap: Kap<Either<NonEmptyList<E>, (FixtGenericLabel) -> (FixtGenericAmount<T>) -> FixtGeneric<T>>> = Kap.of(Either.Right(fn))
    return FixtGenericValidatedKap(kap)
}
