// AUTO-GENERATED by kap-ksp — do not edit
import kap.Kap
import kap.KapLike
import kap.of
import kap.with
import kap.then
import kap.thenValue
import kap.map
import kap.andThen
import kap.evalGraph

// ── Opaque wrappers — one per field ──

data class FixtAllSameTypeA(val value: kotlin.String)

data class FixtAllSameTypeB(val value: kotlin.String)

data class FixtAllSameTypeC(val value: kotlin.String)

// ── Tag classes (receivers for infix `from`) ──

class FixtAllSameTypeATag internal constructor()
class FixtAllSameTypeBTag internal constructor()
class FixtAllSameTypeCTag internal constructor()

// ── Infix `from` — wraps raw value or Kap<T> into the tagged wrapper ──

infix fun FixtAllSameTypeATag.from(value: kotlin.String): FixtAllSameTypeA = FixtAllSameTypeA(value)
infix fun FixtAllSameTypeATag.from(kap: Kap<kotlin.String>): Kap<FixtAllSameTypeA> = kap.map(::FixtAllSameTypeA)

infix fun FixtAllSameTypeBTag.from(value: kotlin.String): FixtAllSameTypeB = FixtAllSameTypeB(value)
infix fun FixtAllSameTypeBTag.from(kap: Kap<kotlin.String>): Kap<FixtAllSameTypeB> = kap.map(::FixtAllSameTypeB)

infix fun FixtAllSameTypeCTag.from(value: kotlin.String): FixtAllSameTypeC = FixtAllSameTypeC(value)
infix fun FixtAllSameTypeCTag.from(kap: Kap<kotlin.String>): Kap<FixtAllSameTypeC> = kap.map(::FixtAllSameTypeC)

// ── Per-slot interfaces (lambda receivers for `.with` / `.then`) ──

interface FixtAllSameTypeASlot { val a: FixtAllSameTypeATag }
interface FixtAllSameTypeBSlot { val b: FixtAllSameTypeBTag }
interface FixtAllSameTypeCSlot { val c: FixtAllSameTypeCTag }

/** Scoped builder for @KapTypeSafe FixtAllSameType. Implements every slot interface
 *  so each field is reachable as a member. The per-slot `.with` overloads
 *  below narrow the lambda receiver to a single tag — the IDE shows only the
 *  field expected at the current curry position when the body is empty.
 *
 *  The wrapper deliberately does NOT delegate to `Kap<F>`. If it did, the
 *  imported `Kap.with(suspend () -> A)` would compete with the slot-specific
 *  `.with { field from … }` and K2's overload resolution sometimes picks the
 *  generic one (before typechecking the lambda body), causing the slot's tag
 *  reference to fail with `Unresolved reference`.
 *
 *  The wrapper implements `KapLike<F>`, so kap-core operators (.map /
 *  .recover / .timeout / .settled / .memoize / .timed / .andThen /
 *  .evalGraph) are available directly on partial wrappers as well. For raw
 *  `Kap<F>` (e.g. an external API parameter), use `.asKap`.
 */
class FixtAllSameTypeKap<F>(@PublishedApi internal val _kap: Kap<F>) : KapLike<F>, FixtAllSameTypeASlot, FixtAllSameTypeBSlot, FixtAllSameTypeCSlot {
    override val asKap: Kap<F> get() = _kap
    override val a: FixtAllSameTypeATag = FixtAllSameTypeATag()
    override val b: FixtAllSameTypeBTag = FixtAllSameTypeBTag()
    override val c: FixtAllSameTypeCTag = FixtAllSameTypeCTag()

    companion object {
        val a: FixtAllSameTypeATag = FixtAllSameTypeATag()
        val b: FixtAllSameTypeBTag = FixtAllSameTypeBTag()
        val c: FixtAllSameTypeCTag = FixtAllSameTypeCTag()
    }
}

// ── Per-slot operators — IDE shows exactly the field expected at this position ──

@kotlin.jvm.JvmName("with_a")
inline infix fun <Rest> FixtAllSameTypeKap<(FixtAllSameTypeA) -> Rest>.with(
    crossinline fa: suspend FixtAllSameTypeASlot.() -> FixtAllSameTypeA,
): FixtAllSameTypeKap<Rest> {
    val self = this
    return FixtAllSameTypeKap(self._kap.with(suspend { self.fa() }))
}

@kotlin.jvm.JvmName("then_a")
inline infix fun <Rest> FixtAllSameTypeKap<(FixtAllSameTypeA) -> Rest>.then(
    crossinline fa: suspend FixtAllSameTypeASlot.() -> FixtAllSameTypeA,
): FixtAllSameTypeKap<Rest> {
    val self = this
    return FixtAllSameTypeKap(self._kap.then(suspend { self.fa() }))
}

@kotlin.jvm.JvmName("thenValue_a")
inline infix fun <Rest> FixtAllSameTypeKap<(FixtAllSameTypeA) -> Rest>.thenValue(
    crossinline fa: suspend FixtAllSameTypeASlot.() -> FixtAllSameTypeA,
): FixtAllSameTypeKap<Rest> {
    val self = this
    return FixtAllSameTypeKap(self._kap.thenValue(suspend { self.fa() }))
}

@kotlin.jvm.JvmName("with_b")
inline infix fun <Rest> FixtAllSameTypeKap<(FixtAllSameTypeB) -> Rest>.with(
    crossinline fa: suspend FixtAllSameTypeBSlot.() -> FixtAllSameTypeB,
): FixtAllSameTypeKap<Rest> {
    val self = this
    return FixtAllSameTypeKap(self._kap.with(suspend { self.fa() }))
}

@kotlin.jvm.JvmName("then_b")
inline infix fun <Rest> FixtAllSameTypeKap<(FixtAllSameTypeB) -> Rest>.then(
    crossinline fa: suspend FixtAllSameTypeBSlot.() -> FixtAllSameTypeB,
): FixtAllSameTypeKap<Rest> {
    val self = this
    return FixtAllSameTypeKap(self._kap.then(suspend { self.fa() }))
}

@kotlin.jvm.JvmName("thenValue_b")
inline infix fun <Rest> FixtAllSameTypeKap<(FixtAllSameTypeB) -> Rest>.thenValue(
    crossinline fa: suspend FixtAllSameTypeBSlot.() -> FixtAllSameTypeB,
): FixtAllSameTypeKap<Rest> {
    val self = this
    return FixtAllSameTypeKap(self._kap.thenValue(suspend { self.fa() }))
}

@kotlin.jvm.JvmName("with_c")
inline infix fun FixtAllSameTypeKap<(FixtAllSameTypeC) -> FixtAllSameType>.with(
    crossinline fa: suspend FixtAllSameTypeCSlot.() -> FixtAllSameTypeC,
): Kap<FixtAllSameType> {
    val self = this
    return self._kap.with(suspend { self.fa() })
}

@kotlin.jvm.JvmName("then_c")
inline infix fun FixtAllSameTypeKap<(FixtAllSameTypeC) -> FixtAllSameType>.then(
    crossinline fa: suspend FixtAllSameTypeCSlot.() -> FixtAllSameTypeC,
): Kap<FixtAllSameType> {
    val self = this
    return self._kap.then(suspend { self.fa() })
}

@kotlin.jvm.JvmName("thenValue_c")
inline infix fun FixtAllSameTypeKap<(FixtAllSameTypeC) -> FixtAllSameType>.thenValue(
    crossinline fa: suspend FixtAllSameTypeCSlot.() -> FixtAllSameTypeC,
): Kap<FixtAllSameType> {
    val self = this
    return self._kap.thenValue(suspend { self.fa() })
}

infix fun <A, B> FixtAllSameTypeKap<(A) -> B>.with(fa: Kap<A>): FixtAllSameTypeKap<B> =
    FixtAllSameTypeKap(_kap.with(fa))

infix fun <A, B> FixtAllSameTypeKap<(A) -> B>.then(fa: Kap<A>): FixtAllSameTypeKap<B> =
    FixtAllSameTypeKap(_kap.then(fa))

infix fun <A, B> FixtAllSameTypeKap<(A) -> B>.thenValue(fa: Kap<A>): FixtAllSameTypeKap<B> =
    FixtAllSameTypeKap(_kap.thenValue(fa))

infix fun FixtAllSameTypeKap<(FixtAllSameTypeC) -> FixtAllSameType>.with(fa: Kap<FixtAllSameTypeC>): Kap<FixtAllSameType> =
    _kap.with(fa)

infix fun FixtAllSameTypeKap<(FixtAllSameTypeC) -> FixtAllSameType>.then(fa: Kap<FixtAllSameTypeC>): Kap<FixtAllSameType> =
    _kap.then(fa)

infix fun FixtAllSameTypeKap<(FixtAllSameTypeC) -> FixtAllSameType>.thenValue(fa: Kap<FixtAllSameTypeC>): Kap<FixtAllSameType> =
    _kap.thenValue(fa)

inline infix fun <A, B> FixtAllSameTypeKap<A>.andThen(
    crossinline f: (A) -> Kap<B>,
): Kap<B> = _kap.andThen(f)

suspend fun <A> FixtAllSameTypeKap<A>.evalGraph(): A = _kap.evalGraph()


/** Official entry point — returns FixtAllSameTypeKap so `.with { field from value }` works without imports. */
fun kap(f: (kotlin.String, kotlin.String, kotlin.String) -> FixtAllSameType): FixtAllSameTypeKap<(FixtAllSameTypeA) -> (FixtAllSameTypeB) -> (FixtAllSameTypeC) -> FixtAllSameType> =
    FixtAllSameTypeKap(Kap.of({ p0: FixtAllSameTypeA -> { p1: FixtAllSameTypeB -> { p2: FixtAllSameTypeC -> f(p0.value, p1.value, p2.value) } } }))
