// AUTO-GENERATED by kap-ksp — do not edit
import arrow.core.Either
import arrow.core.NonEmptyList
import kap.Kap
import kap.KapLike
import kap.of
import kap.withV
import kap.thenV
import kap.thenValueV
import kap.evalGraph

// ── Validated infix `from` — maps Either<Nel<E>, FieldType> into tagged wrapper ──

infix fun <E> FixtBuildRightValueTag.from(value: Either<NonEmptyList<E>, kotlin.String>): Either<NonEmptyList<E>, FixtBuildRightValue> =
    value.map(::FixtBuildRightValue)

/** Validated scoped builder for @KapTypeSafe FixtBuildRight. Uses the same per-slot
 *  tag interfaces as FixtBuildRightKap — each `.withV { field from validateField() }`
 *  narrows the receiver to one slot, accumulating errors via Arrow's applicative.
 */
class FixtBuildRightValidatedKap<E, F>(@PublishedApi internal val _kap: Kap<Either<NonEmptyList<E>, F>>) : KapLike<Either<NonEmptyList<E>, F>>, FixtBuildRightValueSlot {
    override val asKap: Kap<Either<NonEmptyList<E>, F>> get() = _kap
    override val value: FixtBuildRightValueTag = FixtBuildRightValueTag()

    companion object {
        val value: FixtBuildRightValueTag = FixtBuildRightValueTag()
    }
}

// ── Per-slot .withV / .thenV / .thenValueV operators ──

@kotlin.jvm.JvmName("withV_value")
inline infix fun <E> FixtBuildRightValidatedKap<E, (FixtBuildRightValue) -> kotlin.String>.withV(
    crossinline fa: suspend FixtBuildRightValueSlot.() -> Either<NonEmptyList<E>, FixtBuildRightValue>,
): Kap<Either<NonEmptyList<E>, kotlin.String>> {
    val self = this
    return self._kap.withV(Kap { self.fa() })
}

@kotlin.jvm.JvmName("thenV_value")
inline infix fun <E> FixtBuildRightValidatedKap<E, (FixtBuildRightValue) -> kotlin.String>.thenV(
    crossinline fa: suspend FixtBuildRightValueSlot.() -> Either<NonEmptyList<E>, FixtBuildRightValue>,
): Kap<Either<NonEmptyList<E>, kotlin.String>> {
    val self = this
    return self._kap.thenV(Kap { self.fa() })
}

@kotlin.jvm.JvmName("thenValueV_value")
inline infix fun <E> FixtBuildRightValidatedKap<E, (FixtBuildRightValue) -> kotlin.String>.thenValueV(
    crossinline fa: suspend FixtBuildRightValueSlot.() -> Either<NonEmptyList<E>, FixtBuildRightValue>,
): Kap<Either<NonEmptyList<E>, kotlin.String>> {
    val self = this
    return self._kap.thenValueV(Kap { self.fa() })
}

infix fun <E, A, B> FixtBuildRightValidatedKap<E, (A) -> B>.withV(fa: Kap<Either<NonEmptyList<E>, A>>): FixtBuildRightValidatedKap<E, B> =
    FixtBuildRightValidatedKap(_kap.withV(fa))

infix fun <E, A, B> FixtBuildRightValidatedKap<E, (A) -> B>.thenV(fa: Kap<Either<NonEmptyList<E>, A>>): FixtBuildRightValidatedKap<E, B> =
    FixtBuildRightValidatedKap(_kap.thenV(fa))

infix fun <E, A, B> FixtBuildRightValidatedKap<E, (A) -> B>.thenValueV(fa: Kap<Either<NonEmptyList<E>, A>>): FixtBuildRightValidatedKap<E, B> =
    FixtBuildRightValidatedKap(_kap.thenValueV(fa))

infix fun <E> FixtBuildRightValidatedKap<E, (FixtBuildRightValue) -> kotlin.String>.withV(fa: Kap<Either<NonEmptyList<E>, FixtBuildRightValue>>): Kap<Either<NonEmptyList<E>, kotlin.String>> =
    _kap.withV(fa)

infix fun <E> FixtBuildRightValidatedKap<E, (FixtBuildRightValue) -> kotlin.String>.thenV(fa: Kap<Either<NonEmptyList<E>, FixtBuildRightValue>>): Kap<Either<NonEmptyList<E>, kotlin.String>> =
    _kap.thenV(fa)

infix fun <E> FixtBuildRightValidatedKap<E, (FixtBuildRightValue) -> kotlin.String>.thenValueV(fa: Kap<Either<NonEmptyList<E>, FixtBuildRightValue>>): Kap<Either<NonEmptyList<E>, kotlin.String>> =
    _kap.thenValueV(fa)

suspend fun <E, A> FixtBuildRightValidatedKap<E, A>.evalGraph(): Either<NonEmptyList<E>, A> = _kap.evalGraph()


/** Validated entry — returns FixtBuildRightValidatedKap so `.withV { field from validate() }` works without imports. */
fun <E> kapVFixtBuildRight(f: (kotlin.String) -> kotlin.String): FixtBuildRightValidatedKap<E, (FixtBuildRightValue) -> kotlin.String> {
    val fn: (FixtBuildRightValue) -> kotlin.String = { p0: FixtBuildRightValue -> f(p0.value) }
    val kap: Kap<Either<NonEmptyList<E>, (FixtBuildRightValue) -> kotlin.String>> = Kap.of(Either.Right(fn))
    return FixtBuildRightValidatedKap(kap)
}
