// AUTO-GENERATED by kap-ksp — do not edit
import arrow.core.Either
import arrow.core.NonEmptyList
import kap.Kap
import kap.KapLike
import kap.of
import kap.withV
import kap.thenV
import kap.thenValueV
import kap.evalGraph

// ── Validated infix `from` — maps Either<Nel<E>, FieldType> into tagged wrapper ──

infix fun <E, T> FixtGenericFnSeedTag.from(value: Either<NonEmptyList<E>, T>): Either<NonEmptyList<E>, FixtGenericFnSeed<T>> =
    value.map(::FixtGenericFnSeed)

infix fun <E> FixtGenericFnNTag.from(value: Either<NonEmptyList<E>, kotlin.Int>): Either<NonEmptyList<E>, FixtGenericFnN> =
    value.map(::FixtGenericFnN)

/** Validated scoped builder for @KapTypeSafe FixtGenericFn. Uses the same per-slot
 *  tag interfaces as FixtGenericFnKap — each `.withV { field from validateField() }`
 *  narrows the receiver to one slot, accumulating errors via Arrow's applicative.
 */
class FixtGenericFnValidatedKap<E, F>(@PublishedApi internal val _kap: Kap<Either<NonEmptyList<E>, F>>) : KapLike<Either<NonEmptyList<E>, F>>, FixtGenericFnSeedSlot, FixtGenericFnNSlot {
    override val asKap: Kap<Either<NonEmptyList<E>, F>> get() = _kap
    override val seed: FixtGenericFnSeedTag = FixtGenericFnSeedTag()
    override val n: FixtGenericFnNTag = FixtGenericFnNTag()

    companion object {
        val seed: FixtGenericFnSeedTag = FixtGenericFnSeedTag()
        val n: FixtGenericFnNTag = FixtGenericFnNTag()
    }
}

// ── Per-slot .withV / .thenV / .thenValueV operators ──

@kotlin.jvm.JvmName("withV_seed")
inline infix fun <E, T, Rest> FixtGenericFnValidatedKap<E, (FixtGenericFnSeed<T>) -> Rest>.withV(
    crossinline fa: suspend FixtGenericFnSeedSlot.() -> Either<NonEmptyList<E>, FixtGenericFnSeed<T>>,
): FixtGenericFnValidatedKap<E, Rest> {
    val self = this
    return FixtGenericFnValidatedKap(self._kap.withV(Kap { self.fa() }))
}

@kotlin.jvm.JvmName("thenV_seed")
inline infix fun <E, T, Rest> FixtGenericFnValidatedKap<E, (FixtGenericFnSeed<T>) -> Rest>.thenV(
    crossinline fa: suspend FixtGenericFnSeedSlot.() -> Either<NonEmptyList<E>, FixtGenericFnSeed<T>>,
): FixtGenericFnValidatedKap<E, Rest> {
    val self = this
    return FixtGenericFnValidatedKap(self._kap.thenV(Kap { self.fa() }))
}

@kotlin.jvm.JvmName("thenValueV_seed")
inline infix fun <E, T, Rest> FixtGenericFnValidatedKap<E, (FixtGenericFnSeed<T>) -> Rest>.thenValueV(
    crossinline fa: suspend FixtGenericFnSeedSlot.() -> Either<NonEmptyList<E>, FixtGenericFnSeed<T>>,
): FixtGenericFnValidatedKap<E, Rest> {
    val self = this
    return FixtGenericFnValidatedKap(self._kap.thenValueV(Kap { self.fa() }))
}

@kotlin.jvm.JvmName("withV_n")
inline infix fun <E, T> FixtGenericFnValidatedKap<E, (FixtGenericFnN) -> kotlin.Pair<T, kotlin.Int>>.withV(
    crossinline fa: suspend FixtGenericFnNSlot.() -> Either<NonEmptyList<E>, FixtGenericFnN>,
): Kap<Either<NonEmptyList<E>, kotlin.Pair<T, kotlin.Int>>> {
    val self = this
    return self._kap.withV(Kap { self.fa() })
}

@kotlin.jvm.JvmName("thenV_n")
inline infix fun <E, T> FixtGenericFnValidatedKap<E, (FixtGenericFnN) -> kotlin.Pair<T, kotlin.Int>>.thenV(
    crossinline fa: suspend FixtGenericFnNSlot.() -> Either<NonEmptyList<E>, FixtGenericFnN>,
): Kap<Either<NonEmptyList<E>, kotlin.Pair<T, kotlin.Int>>> {
    val self = this
    return self._kap.thenV(Kap { self.fa() })
}

@kotlin.jvm.JvmName("thenValueV_n")
inline infix fun <E, T> FixtGenericFnValidatedKap<E, (FixtGenericFnN) -> kotlin.Pair<T, kotlin.Int>>.thenValueV(
    crossinline fa: suspend FixtGenericFnNSlot.() -> Either<NonEmptyList<E>, FixtGenericFnN>,
): Kap<Either<NonEmptyList<E>, kotlin.Pair<T, kotlin.Int>>> {
    val self = this
    return self._kap.thenValueV(Kap { self.fa() })
}

infix fun <E, A, B> FixtGenericFnValidatedKap<E, (A) -> B>.withV(fa: Kap<Either<NonEmptyList<E>, A>>): FixtGenericFnValidatedKap<E, B> =
    FixtGenericFnValidatedKap(_kap.withV(fa))

infix fun <E, A, B> FixtGenericFnValidatedKap<E, (A) -> B>.thenV(fa: Kap<Either<NonEmptyList<E>, A>>): FixtGenericFnValidatedKap<E, B> =
    FixtGenericFnValidatedKap(_kap.thenV(fa))

infix fun <E, A, B> FixtGenericFnValidatedKap<E, (A) -> B>.thenValueV(fa: Kap<Either<NonEmptyList<E>, A>>): FixtGenericFnValidatedKap<E, B> =
    FixtGenericFnValidatedKap(_kap.thenValueV(fa))

infix fun <E, T> FixtGenericFnValidatedKap<E, (FixtGenericFnN) -> kotlin.Pair<T, kotlin.Int>>.withV(fa: Kap<Either<NonEmptyList<E>, FixtGenericFnN>>): Kap<Either<NonEmptyList<E>, kotlin.Pair<T, kotlin.Int>>> =
    _kap.withV(fa)

infix fun <E, T> FixtGenericFnValidatedKap<E, (FixtGenericFnN) -> kotlin.Pair<T, kotlin.Int>>.thenV(fa: Kap<Either<NonEmptyList<E>, FixtGenericFnN>>): Kap<Either<NonEmptyList<E>, kotlin.Pair<T, kotlin.Int>>> =
    _kap.thenV(fa)

infix fun <E, T> FixtGenericFnValidatedKap<E, (FixtGenericFnN) -> kotlin.Pair<T, kotlin.Int>>.thenValueV(fa: Kap<Either<NonEmptyList<E>, FixtGenericFnN>>): Kap<Either<NonEmptyList<E>, kotlin.Pair<T, kotlin.Int>>> =
    _kap.thenValueV(fa)

suspend fun <E, A> FixtGenericFnValidatedKap<E, A>.evalGraph(): Either<NonEmptyList<E>, A> = _kap.evalGraph()


/** Validated entry — `kapV(::C)` / `kapV<Double>(::C)` for generics. */
fun <E, T> kapV(f: (T, kotlin.Int) -> kotlin.Pair<T, kotlin.Int>): FixtGenericFnValidatedKap<E, (FixtGenericFnSeed<T>) -> (FixtGenericFnN) -> kotlin.Pair<T, kotlin.Int>> {
    val fn: (FixtGenericFnSeed<T>) -> (FixtGenericFnN) -> kotlin.Pair<T, kotlin.Int> = { p0: FixtGenericFnSeed<T> -> { p1: FixtGenericFnN -> f(p0.value, p1.value) } }
    val kap: Kap<Either<NonEmptyList<E>, (FixtGenericFnSeed<T>) -> (FixtGenericFnN) -> kotlin.Pair<T, kotlin.Int>>> = Kap.of(Either.Right(fn))
    return FixtGenericFnValidatedKap(kap)
}

/** Generic zero-arg alternative — `kapVFixtGenericFn<Double>()`. */
fun <E, T> kapVFixtGenericFn(): FixtGenericFnValidatedKap<E, (FixtGenericFnSeed<T>) -> (FixtGenericFnN) -> kotlin.Pair<T, kotlin.Int>> {
    val fn: (FixtGenericFnSeed<T>) -> (FixtGenericFnN) -> kotlin.Pair<T, kotlin.Int> = { p0: FixtGenericFnSeed<T> -> { p1: FixtGenericFnN -> fixtGenericFn(p0.value, p1.value) } }
    val kap: Kap<Either<NonEmptyList<E>, (FixtGenericFnSeed<T>) -> (FixtGenericFnN) -> kotlin.Pair<T, kotlin.Int>>> = Kap.of(Either.Right(fn))
    return FixtGenericFnValidatedKap(kap)
}

