// AUTO-GENERATED by kap-ksp — do not edit
import kap.Kap
import kap.KapLike
import kap.of
import kap.with
import kap.then
import kap.thenValue
import kap.map
import kap.andThen
import kap.evalGraph

// ── Opaque wrappers — one per field ──

data class FixtSimpleOnly(val value: kotlin.String)

// ── Tag classes (receivers for infix `from`) ──

class FixtSimpleOnlyTag internal constructor()

// ── Infix `from` — wraps raw value or Kap<T> into the tagged wrapper ──

infix fun FixtSimpleOnlyTag.from(value: kotlin.String): FixtSimpleOnly = FixtSimpleOnly(value)
infix fun FixtSimpleOnlyTag.from(kap: Kap<kotlin.String>): Kap<FixtSimpleOnly> = kap.map(::FixtSimpleOnly)

// ── Per-slot interfaces (lambda receivers for `.with` / `.then`) ──

interface FixtSimpleOnlySlot { val only: FixtSimpleOnlyTag }

/** Scoped builder for @KapTypeSafe FixtSimple. Implements every slot interface
 *  so each field is reachable as a member. The per-slot `.with` overloads
 *  below narrow the lambda receiver to a single tag — the IDE shows only the
 *  field expected at the current curry position when the body is empty.
 *
 *  The wrapper deliberately does NOT delegate to `Kap<F>`. If it did, the
 *  imported `Kap.with(suspend () -> A)` would compete with the slot-specific
 *  `.with { field from … }` and K2's overload resolution sometimes picks the
 *  generic one (before typechecking the lambda body), causing the slot's tag
 *  reference to fail with `Unresolved reference`.
 *
 *  The wrapper implements `KapLike<F>`, so kap-core operators (.map /
 *  .recover / .timeout / .settled / .memoize / .timed / .andThen /
 *  .evalGraph) are available directly on partial wrappers as well. For raw
 *  `Kap<F>` (e.g. an external API parameter), use `.asKap`.
 */
class FixtSimpleKap<F>(@PublishedApi internal val _kap: Kap<F>) : KapLike<F>, FixtSimpleOnlySlot {
    override val asKap: Kap<F> get() = _kap
    override val only: FixtSimpleOnlyTag = FixtSimpleOnlyTag()

    companion object {
        val only: FixtSimpleOnlyTag = FixtSimpleOnlyTag()
    }
}

// ── Per-slot operators — IDE shows exactly the field expected at this position ──

@kotlin.jvm.JvmName("with_only")
inline infix fun FixtSimpleKap<(FixtSimpleOnly) -> FixtSimple>.with(
    crossinline fa: suspend FixtSimpleOnlySlot.() -> FixtSimpleOnly,
): Kap<FixtSimple> {
    val self = this
    return self._kap.with(suspend { self.fa() })
}

@kotlin.jvm.JvmName("then_only")
inline infix fun FixtSimpleKap<(FixtSimpleOnly) -> FixtSimple>.then(
    crossinline fa: suspend FixtSimpleOnlySlot.() -> FixtSimpleOnly,
): Kap<FixtSimple> {
    val self = this
    return self._kap.then(suspend { self.fa() })
}

@kotlin.jvm.JvmName("thenValue_only")
inline infix fun FixtSimpleKap<(FixtSimpleOnly) -> FixtSimple>.thenValue(
    crossinline fa: suspend FixtSimpleOnlySlot.() -> FixtSimpleOnly,
): Kap<FixtSimple> {
    val self = this
    return self._kap.thenValue(suspend { self.fa() })
}

infix fun <A, B> FixtSimpleKap<(A) -> B>.with(fa: Kap<A>): FixtSimpleKap<B> =
    FixtSimpleKap(_kap.with(fa))

infix fun <A, B> FixtSimpleKap<(A) -> B>.then(fa: Kap<A>): FixtSimpleKap<B> =
    FixtSimpleKap(_kap.then(fa))

infix fun <A, B> FixtSimpleKap<(A) -> B>.thenValue(fa: Kap<A>): FixtSimpleKap<B> =
    FixtSimpleKap(_kap.thenValue(fa))

infix fun FixtSimpleKap<(FixtSimpleOnly) -> FixtSimple>.with(fa: Kap<FixtSimpleOnly>): Kap<FixtSimple> =
    _kap.with(fa)

infix fun FixtSimpleKap<(FixtSimpleOnly) -> FixtSimple>.then(fa: Kap<FixtSimpleOnly>): Kap<FixtSimple> =
    _kap.then(fa)

infix fun FixtSimpleKap<(FixtSimpleOnly) -> FixtSimple>.thenValue(fa: Kap<FixtSimpleOnly>): Kap<FixtSimple> =
    _kap.thenValue(fa)

inline infix fun <A, B> FixtSimpleKap<A>.andThen(
    crossinline f: (A) -> Kap<B>,
): Kap<B> = _kap.andThen(f)

suspend fun <A> FixtSimpleKap<A>.evalGraph(): A = _kap.evalGraph()


/** Official entry point — returns FixtSimpleKap so `.with { field from value }` works without imports. */
fun kap(f: (kotlin.String) -> FixtSimple): FixtSimpleKap<(FixtSimpleOnly) -> FixtSimple> =
    FixtSimpleKap(Kap.of({ p0: FixtSimpleOnly -> f(p0.value) }))
