// AUTO-GENERATED by kap-ksp — do not edit
import arrow.core.Either
import arrow.core.NonEmptyList
import kap.Kap
import kap.KapLike
import kap.of
import kap.withV
import kap.thenV
import kap.thenValueV
import kap.evalGraph

// ── Validated infix `from` — maps Either<Nel<E>, FieldType> into tagged wrapper ──

infix fun <E> FixtWithGenericItemsTag.from(value: Either<NonEmptyList<E>, kotlin.collections.List<kotlin.String>>): Either<NonEmptyList<E>, FixtWithGenericItems> =
    value.map(::FixtWithGenericItems)

infix fun <E> FixtWithGenericCountsTag.from(value: Either<NonEmptyList<E>, kotlin.collections.Map<kotlin.String, kotlin.Int>>): Either<NonEmptyList<E>, FixtWithGenericCounts> =
    value.map(::FixtWithGenericCounts)

infix fun <E> FixtWithGenericCountTag.from(value: Either<NonEmptyList<E>, kotlin.Int>): Either<NonEmptyList<E>, FixtWithGenericCount> =
    value.map(::FixtWithGenericCount)

/** Validated scoped builder for @KapTypeSafe FixtWithGeneric. Uses the same per-slot
 *  tag interfaces as FixtWithGenericKap — each `.withV { field from validateField() }`
 *  narrows the receiver to one slot, accumulating errors via Arrow's applicative.
 */
class FixtWithGenericValidatedKap<E, F>(@PublishedApi internal val _kap: Kap<Either<NonEmptyList<E>, F>>) : KapLike<Either<NonEmptyList<E>, F>>, FixtWithGenericItemsSlot, FixtWithGenericCountsSlot, FixtWithGenericCountSlot {
    override val asKap: Kap<Either<NonEmptyList<E>, F>> get() = _kap
    override val items: FixtWithGenericItemsTag = FixtWithGenericItemsTag()
    override val counts: FixtWithGenericCountsTag = FixtWithGenericCountsTag()
    override val count: FixtWithGenericCountTag = FixtWithGenericCountTag()

    companion object {
        val items: FixtWithGenericItemsTag = FixtWithGenericItemsTag()
        val counts: FixtWithGenericCountsTag = FixtWithGenericCountsTag()
        val count: FixtWithGenericCountTag = FixtWithGenericCountTag()
    }
}

// ── Per-slot .withV / .thenV / .thenValueV operators ──

@kotlin.jvm.JvmName("withV_items")
inline infix fun <E, Rest> FixtWithGenericValidatedKap<E, (FixtWithGenericItems) -> Rest>.withV(
    crossinline fa: suspend FixtWithGenericItemsSlot.() -> Either<NonEmptyList<E>, FixtWithGenericItems>,
): FixtWithGenericValidatedKap<E, Rest> {
    val self = this
    return FixtWithGenericValidatedKap(self._kap.withV(Kap { self.fa() }))
}

@kotlin.jvm.JvmName("thenV_items")
inline infix fun <E, Rest> FixtWithGenericValidatedKap<E, (FixtWithGenericItems) -> Rest>.thenV(
    crossinline fa: suspend FixtWithGenericItemsSlot.() -> Either<NonEmptyList<E>, FixtWithGenericItems>,
): FixtWithGenericValidatedKap<E, Rest> {
    val self = this
    return FixtWithGenericValidatedKap(self._kap.thenV(Kap { self.fa() }))
}

@kotlin.jvm.JvmName("thenValueV_items")
inline infix fun <E, Rest> FixtWithGenericValidatedKap<E, (FixtWithGenericItems) -> Rest>.thenValueV(
    crossinline fa: suspend FixtWithGenericItemsSlot.() -> Either<NonEmptyList<E>, FixtWithGenericItems>,
): FixtWithGenericValidatedKap<E, Rest> {
    val self = this
    return FixtWithGenericValidatedKap(self._kap.thenValueV(Kap { self.fa() }))
}

@kotlin.jvm.JvmName("withV_counts")
inline infix fun <E, Rest> FixtWithGenericValidatedKap<E, (FixtWithGenericCounts) -> Rest>.withV(
    crossinline fa: suspend FixtWithGenericCountsSlot.() -> Either<NonEmptyList<E>, FixtWithGenericCounts>,
): FixtWithGenericValidatedKap<E, Rest> {
    val self = this
    return FixtWithGenericValidatedKap(self._kap.withV(Kap { self.fa() }))
}

@kotlin.jvm.JvmName("thenV_counts")
inline infix fun <E, Rest> FixtWithGenericValidatedKap<E, (FixtWithGenericCounts) -> Rest>.thenV(
    crossinline fa: suspend FixtWithGenericCountsSlot.() -> Either<NonEmptyList<E>, FixtWithGenericCounts>,
): FixtWithGenericValidatedKap<E, Rest> {
    val self = this
    return FixtWithGenericValidatedKap(self._kap.thenV(Kap { self.fa() }))
}

@kotlin.jvm.JvmName("thenValueV_counts")
inline infix fun <E, Rest> FixtWithGenericValidatedKap<E, (FixtWithGenericCounts) -> Rest>.thenValueV(
    crossinline fa: suspend FixtWithGenericCountsSlot.() -> Either<NonEmptyList<E>, FixtWithGenericCounts>,
): FixtWithGenericValidatedKap<E, Rest> {
    val self = this
    return FixtWithGenericValidatedKap(self._kap.thenValueV(Kap { self.fa() }))
}

@kotlin.jvm.JvmName("withV_count")
inline infix fun <E> FixtWithGenericValidatedKap<E, (FixtWithGenericCount) -> FixtWithGeneric>.withV(
    crossinline fa: suspend FixtWithGenericCountSlot.() -> Either<NonEmptyList<E>, FixtWithGenericCount>,
): Kap<Either<NonEmptyList<E>, FixtWithGeneric>> {
    val self = this
    return self._kap.withV(Kap { self.fa() })
}

@kotlin.jvm.JvmName("thenV_count")
inline infix fun <E> FixtWithGenericValidatedKap<E, (FixtWithGenericCount) -> FixtWithGeneric>.thenV(
    crossinline fa: suspend FixtWithGenericCountSlot.() -> Either<NonEmptyList<E>, FixtWithGenericCount>,
): Kap<Either<NonEmptyList<E>, FixtWithGeneric>> {
    val self = this
    return self._kap.thenV(Kap { self.fa() })
}

@kotlin.jvm.JvmName("thenValueV_count")
inline infix fun <E> FixtWithGenericValidatedKap<E, (FixtWithGenericCount) -> FixtWithGeneric>.thenValueV(
    crossinline fa: suspend FixtWithGenericCountSlot.() -> Either<NonEmptyList<E>, FixtWithGenericCount>,
): Kap<Either<NonEmptyList<E>, FixtWithGeneric>> {
    val self = this
    return self._kap.thenValueV(Kap { self.fa() })
}

infix fun <E, A, B> FixtWithGenericValidatedKap<E, (A) -> B>.withV(fa: Kap<Either<NonEmptyList<E>, A>>): FixtWithGenericValidatedKap<E, B> =
    FixtWithGenericValidatedKap(_kap.withV(fa))

infix fun <E, A, B> FixtWithGenericValidatedKap<E, (A) -> B>.thenV(fa: Kap<Either<NonEmptyList<E>, A>>): FixtWithGenericValidatedKap<E, B> =
    FixtWithGenericValidatedKap(_kap.thenV(fa))

infix fun <E, A, B> FixtWithGenericValidatedKap<E, (A) -> B>.thenValueV(fa: Kap<Either<NonEmptyList<E>, A>>): FixtWithGenericValidatedKap<E, B> =
    FixtWithGenericValidatedKap(_kap.thenValueV(fa))

infix fun <E> FixtWithGenericValidatedKap<E, (FixtWithGenericCount) -> FixtWithGeneric>.withV(fa: Kap<Either<NonEmptyList<E>, FixtWithGenericCount>>): Kap<Either<NonEmptyList<E>, FixtWithGeneric>> =
    _kap.withV(fa)

infix fun <E> FixtWithGenericValidatedKap<E, (FixtWithGenericCount) -> FixtWithGeneric>.thenV(fa: Kap<Either<NonEmptyList<E>, FixtWithGenericCount>>): Kap<Either<NonEmptyList<E>, FixtWithGeneric>> =
    _kap.thenV(fa)

infix fun <E> FixtWithGenericValidatedKap<E, (FixtWithGenericCount) -> FixtWithGeneric>.thenValueV(fa: Kap<Either<NonEmptyList<E>, FixtWithGenericCount>>): Kap<Either<NonEmptyList<E>, FixtWithGeneric>> =
    _kap.thenValueV(fa)

suspend fun <E, A> FixtWithGenericValidatedKap<E, A>.evalGraph(): Either<NonEmptyList<E>, A> = _kap.evalGraph()


/** Validated entry — `kapV(::C)` / `kapV<Double>(::C)` for generics. */
fun <E> kapV(f: (kotlin.collections.List<kotlin.String>, kotlin.collections.Map<kotlin.String, kotlin.Int>, kotlin.Int) -> FixtWithGeneric): FixtWithGenericValidatedKap<E, (FixtWithGenericItems) -> (FixtWithGenericCounts) -> (FixtWithGenericCount) -> FixtWithGeneric> {
    val fn: (FixtWithGenericItems) -> (FixtWithGenericCounts) -> (FixtWithGenericCount) -> FixtWithGeneric = { p0: FixtWithGenericItems -> { p1: FixtWithGenericCounts -> { p2: FixtWithGenericCount -> f(p0.value, p1.value, p2.value) } } }
    val kap: Kap<Either<NonEmptyList<E>, (FixtWithGenericItems) -> (FixtWithGenericCounts) -> (FixtWithGenericCount) -> FixtWithGeneric>> = Kap.of(Either.Right(fn))
    return FixtWithGenericValidatedKap(kap)
}

