// AUTO-GENERATED by kap-ksp — do not edit
import arrow.core.Either
import arrow.core.NonEmptyList
import kap.Kap
import kap.KapLike
import kap.of
import kap.withV
import kap.thenV
import kap.thenValueV
import kap.evalGraph

// ── Validated infix `from` — maps Either<Nel<E>, FieldType> into tagged wrapper ──

infix fun <E> FixtSimpleOnlyTag.from(value: Either<NonEmptyList<E>, kotlin.String>): Either<NonEmptyList<E>, FixtSimpleOnly> =
    value.map(::FixtSimpleOnly)

/** Validated scoped builder for @KapTypeSafe FixtSimple. Uses the same per-slot
 *  tag interfaces as FixtSimpleKap — each `.withV { field from validateField() }`
 *  narrows the receiver to one slot, accumulating errors via Arrow's applicative.
 */
class FixtSimpleValidatedKap<E, F>(@PublishedApi internal val _kap: Kap<Either<NonEmptyList<E>, F>>) : KapLike<Either<NonEmptyList<E>, F>>, FixtSimpleOnlySlot {
    override val asKap: Kap<Either<NonEmptyList<E>, F>> get() = _kap
    override val only: FixtSimpleOnlyTag = FixtSimpleOnlyTag()

    companion object {
        val only: FixtSimpleOnlyTag = FixtSimpleOnlyTag()
    }
}

// ── Per-slot .withV / .thenV / .thenValueV operators ──

@kotlin.jvm.JvmName("withV_only")
inline infix fun <E> FixtSimpleValidatedKap<E, (FixtSimpleOnly) -> FixtSimple>.withV(
    crossinline fa: suspend FixtSimpleOnlySlot.() -> Either<NonEmptyList<E>, FixtSimpleOnly>,
): Kap<Either<NonEmptyList<E>, FixtSimple>> {
    val self = this
    return self._kap.withV(Kap { self.fa() })
}

@kotlin.jvm.JvmName("thenV_only")
inline infix fun <E> FixtSimpleValidatedKap<E, (FixtSimpleOnly) -> FixtSimple>.thenV(
    crossinline fa: suspend FixtSimpleOnlySlot.() -> Either<NonEmptyList<E>, FixtSimpleOnly>,
): Kap<Either<NonEmptyList<E>, FixtSimple>> {
    val self = this
    return self._kap.thenV(Kap { self.fa() })
}

@kotlin.jvm.JvmName("thenValueV_only")
inline infix fun <E> FixtSimpleValidatedKap<E, (FixtSimpleOnly) -> FixtSimple>.thenValueV(
    crossinline fa: suspend FixtSimpleOnlySlot.() -> Either<NonEmptyList<E>, FixtSimpleOnly>,
): Kap<Either<NonEmptyList<E>, FixtSimple>> {
    val self = this
    return self._kap.thenValueV(Kap { self.fa() })
}

infix fun <E, A, B> FixtSimpleValidatedKap<E, (A) -> B>.withV(fa: Kap<Either<NonEmptyList<E>, A>>): FixtSimpleValidatedKap<E, B> =
    FixtSimpleValidatedKap(_kap.withV(fa))

infix fun <E, A, B> FixtSimpleValidatedKap<E, (A) -> B>.thenV(fa: Kap<Either<NonEmptyList<E>, A>>): FixtSimpleValidatedKap<E, B> =
    FixtSimpleValidatedKap(_kap.thenV(fa))

infix fun <E, A, B> FixtSimpleValidatedKap<E, (A) -> B>.thenValueV(fa: Kap<Either<NonEmptyList<E>, A>>): FixtSimpleValidatedKap<E, B> =
    FixtSimpleValidatedKap(_kap.thenValueV(fa))

infix fun <E> FixtSimpleValidatedKap<E, (FixtSimpleOnly) -> FixtSimple>.withV(fa: Kap<Either<NonEmptyList<E>, FixtSimpleOnly>>): Kap<Either<NonEmptyList<E>, FixtSimple>> =
    _kap.withV(fa)

infix fun <E> FixtSimpleValidatedKap<E, (FixtSimpleOnly) -> FixtSimple>.thenV(fa: Kap<Either<NonEmptyList<E>, FixtSimpleOnly>>): Kap<Either<NonEmptyList<E>, FixtSimple>> =
    _kap.thenV(fa)

infix fun <E> FixtSimpleValidatedKap<E, (FixtSimpleOnly) -> FixtSimple>.thenValueV(fa: Kap<Either<NonEmptyList<E>, FixtSimpleOnly>>): Kap<Either<NonEmptyList<E>, FixtSimple>> =
    _kap.thenValueV(fa)

suspend fun <E, A> FixtSimpleValidatedKap<E, A>.evalGraph(): Either<NonEmptyList<E>, A> = _kap.evalGraph()


/** Validated entry — `kapV(::C)` / `kapV<Double>(::C)` for generics. */
fun <E> kapV(f: (kotlin.String) -> FixtSimple): FixtSimpleValidatedKap<E, (FixtSimpleOnly) -> FixtSimple> {
    val fn: (FixtSimpleOnly) -> FixtSimple = { p0: FixtSimpleOnly -> f(p0.value) }
    val kap: Kap<Either<NonEmptyList<E>, (FixtSimpleOnly) -> FixtSimple>> = Kap.of(Either.Right(fn))
    return FixtSimpleValidatedKap(kap)
}

