// AUTO-GENERATED by kap-ksp — do not edit
import kap.Kap
import kap.KapLike
import kap.of
import kap.with
import kap.then
import kap.thenValue
import kap.map
import kap.andThen
import kap.evalGraph

// ── Opaque wrappers — one per field ──

data class FixtBridgedLabel(val value: kotlin.String)

data class FixtBridgedAmount(val value: kotlin.Int)

// ── Tag classes (receivers for infix `from`) ──

class FixtBridgedLabelTag internal constructor()
class FixtBridgedAmountTag internal constructor()

// ── Infix `from` — wraps raw value or Kap<T> into the tagged wrapper ──

infix fun FixtBridgedLabelTag.from(value: kotlin.String): FixtBridgedLabel = FixtBridgedLabel(value)
infix fun FixtBridgedLabelTag.from(kap: Kap<kotlin.String>): Kap<FixtBridgedLabel> = kap.map(::FixtBridgedLabel)

infix fun FixtBridgedAmountTag.from(value: kotlin.Int): FixtBridgedAmount = FixtBridgedAmount(value)
infix fun FixtBridgedAmountTag.from(kap: Kap<kotlin.Int>): Kap<FixtBridgedAmount> = kap.map(::FixtBridgedAmount)

// ── Per-slot interfaces (lambda receivers for `.with` / `.then`) ──

interface FixtBridgedLabelSlot { val label: FixtBridgedLabelTag }
interface FixtBridgedAmountSlot { val amount: FixtBridgedAmountTag }

/** Scoped builder for @KapTypeSafe FixtBridged. Implements every slot interface
 *  so each field is reachable as a member. The per-slot `.with` overloads
 *  below narrow the lambda receiver to a single tag — the IDE shows only the
 *  field expected at the current curry position when the body is empty.
 *
 *  The wrapper deliberately does NOT delegate to `Kap<F>`. If it did, the
 *  imported `Kap.with(suspend () -> A)` would compete with the slot-specific
 *  `.with { field from … }` and K2's overload resolution sometimes picks the
 *  generic one (before typechecking the lambda body), causing the slot's tag
 *  reference to fail with `Unresolved reference`.
 *
 *  The wrapper implements `KapLike<F>`, so kap-core operators (.map /
 *  .recover / .timeout / .settled / .memoize / .timed / .andThen /
 *  .evalGraph) are available directly on partial wrappers as well. For raw
 *  `Kap<F>` (e.g. an external API parameter), use `.asKap`.
 */
class FixtBridgedKap<F>(@PublishedApi internal val _kap: Kap<F>) : KapLike<F>, FixtBridgedLabelSlot, FixtBridgedAmountSlot {
    override val asKap: Kap<F> get() = _kap
    override val label: FixtBridgedLabelTag = FixtBridgedLabelTag()
    override val amount: FixtBridgedAmountTag = FixtBridgedAmountTag()

    companion object {
        val label: FixtBridgedLabelTag = FixtBridgedLabelTag()
        val amount: FixtBridgedAmountTag = FixtBridgedAmountTag()
    }
}

// ── Per-slot operators — IDE shows exactly the field expected at this position ──

@kotlin.jvm.JvmName("with_label")
inline infix fun <Rest> FixtBridgedKap<(FixtBridgedLabel) -> Rest>.with(
    crossinline fa: suspend FixtBridgedLabelSlot.() -> FixtBridgedLabel,
): FixtBridgedKap<Rest> {
    val self = this
    return FixtBridgedKap(self._kap.with(suspend { self.fa() }))
}

@kotlin.jvm.JvmName("then_label")
inline infix fun <Rest> FixtBridgedKap<(FixtBridgedLabel) -> Rest>.then(
    crossinline fa: suspend FixtBridgedLabelSlot.() -> FixtBridgedLabel,
): FixtBridgedKap<Rest> {
    val self = this
    return FixtBridgedKap(self._kap.then(suspend { self.fa() }))
}

@kotlin.jvm.JvmName("thenValue_label")
inline infix fun <Rest> FixtBridgedKap<(FixtBridgedLabel) -> Rest>.thenValue(
    crossinline fa: suspend FixtBridgedLabelSlot.() -> FixtBridgedLabel,
): FixtBridgedKap<Rest> {
    val self = this
    return FixtBridgedKap(self._kap.thenValue(suspend { self.fa() }))
}

@kotlin.jvm.JvmName("with_amount")
inline infix fun FixtBridgedKap<(FixtBridgedAmount) -> FixtBridged>.with(
    crossinline fa: suspend FixtBridgedAmountSlot.() -> FixtBridgedAmount,
): Kap<FixtBridged> {
    val self = this
    return self._kap.with(suspend { self.fa() })
}

@kotlin.jvm.JvmName("then_amount")
inline infix fun FixtBridgedKap<(FixtBridgedAmount) -> FixtBridged>.then(
    crossinline fa: suspend FixtBridgedAmountSlot.() -> FixtBridgedAmount,
): Kap<FixtBridged> {
    val self = this
    return self._kap.then(suspend { self.fa() })
}

@kotlin.jvm.JvmName("thenValue_amount")
inline infix fun FixtBridgedKap<(FixtBridgedAmount) -> FixtBridged>.thenValue(
    crossinline fa: suspend FixtBridgedAmountSlot.() -> FixtBridgedAmount,
): Kap<FixtBridged> {
    val self = this
    return self._kap.thenValue(suspend { self.fa() })
}

infix fun <A, B> FixtBridgedKap<(A) -> B>.with(fa: Kap<A>): FixtBridgedKap<B> =
    FixtBridgedKap(_kap.with(fa))

infix fun <A, B> FixtBridgedKap<(A) -> B>.then(fa: Kap<A>): FixtBridgedKap<B> =
    FixtBridgedKap(_kap.then(fa))

infix fun <A, B> FixtBridgedKap<(A) -> B>.thenValue(fa: Kap<A>): FixtBridgedKap<B> =
    FixtBridgedKap(_kap.thenValue(fa))

infix fun FixtBridgedKap<(FixtBridgedAmount) -> FixtBridged>.with(fa: Kap<FixtBridgedAmount>): Kap<FixtBridged> =
    _kap.with(fa)

infix fun FixtBridgedKap<(FixtBridgedAmount) -> FixtBridged>.then(fa: Kap<FixtBridgedAmount>): Kap<FixtBridged> =
    _kap.then(fa)

infix fun FixtBridgedKap<(FixtBridgedAmount) -> FixtBridged>.thenValue(fa: Kap<FixtBridgedAmount>): Kap<FixtBridged> =
    _kap.thenValue(fa)

inline infix fun <A, B> FixtBridgedKap<A>.andThen(
    crossinline f: (A) -> Kap<B>,
): Kap<B> = _kap.andThen(f)

suspend fun <A> FixtBridgedKap<A>.evalGraph(): A = _kap.evalGraph()


/** Official entry — `kap(::C)` plain, `kap<Double>(::C)` for generics. */
fun kap(f: (kotlin.String, kotlin.Int) -> FixtBridged): FixtBridgedKap<(FixtBridgedLabel) -> (FixtBridgedAmount) -> FixtBridged> =
    FixtBridgedKap(Kap.of({ p0: FixtBridgedLabel -> { p1: FixtBridgedAmount -> f(p0.value, p1.value) } }))

