// AUTO-GENERATED by kap-ksp — do not edit
import arrow.core.Either
import arrow.core.NonEmptyList
import kap.Kap
import kap.KapLike
import kap.of
import kap.withV
import kap.thenV
import kap.thenValueV
import kap.evalGraph

// ── Validated infix `from` — maps Either<Nel<E>, FieldType> into tagged wrapper ──

infix fun <E> FixtWithNullableIdTag.from(value: Either<NonEmptyList<E>, kotlin.Long>): Either<NonEmptyList<E>, FixtWithNullableId> =
    value.map(::FixtWithNullableId)

infix fun <E> FixtWithNullableNameTag.from(value: Either<NonEmptyList<E>, kotlin.String?>): Either<NonEmptyList<E>, FixtWithNullableName> =
    value.map(::FixtWithNullableName)

infix fun <E> FixtWithNullableCountTag.from(value: Either<NonEmptyList<E>, kotlin.Int?>): Either<NonEmptyList<E>, FixtWithNullableCount> =
    value.map(::FixtWithNullableCount)

/** Validated scoped builder for @KapTypeSafe FixtWithNullable. Uses the same per-slot
 *  tag interfaces as FixtWithNullableKap — each `.withV { field from validateField() }`
 *  narrows the receiver to one slot, accumulating errors via Arrow's applicative.
 */
class FixtWithNullableValidatedKap<E, F>(@PublishedApi internal val _kap: Kap<Either<NonEmptyList<E>, F>>) : KapLike<Either<NonEmptyList<E>, F>>, FixtWithNullableIdSlot, FixtWithNullableNameSlot, FixtWithNullableCountSlot {
    override val asKap: Kap<Either<NonEmptyList<E>, F>> get() = _kap
    override val id: FixtWithNullableIdTag = FixtWithNullableIdTag()
    override val name: FixtWithNullableNameTag = FixtWithNullableNameTag()
    override val count: FixtWithNullableCountTag = FixtWithNullableCountTag()

    companion object {
        val id: FixtWithNullableIdTag = FixtWithNullableIdTag()
        val name: FixtWithNullableNameTag = FixtWithNullableNameTag()
        val count: FixtWithNullableCountTag = FixtWithNullableCountTag()
    }
}

// ── Per-slot .withV / .thenV / .thenValueV operators ──

@kotlin.jvm.JvmName("withV_id")
inline infix fun <E, Rest> FixtWithNullableValidatedKap<E, (FixtWithNullableId) -> Rest>.withV(
    crossinline fa: suspend FixtWithNullableIdSlot.() -> Either<NonEmptyList<E>, FixtWithNullableId>,
): FixtWithNullableValidatedKap<E, Rest> {
    val self = this
    return FixtWithNullableValidatedKap(self._kap.withV(Kap { self.fa() }))
}

@kotlin.jvm.JvmName("thenV_id")
inline infix fun <E, Rest> FixtWithNullableValidatedKap<E, (FixtWithNullableId) -> Rest>.thenV(
    crossinline fa: suspend FixtWithNullableIdSlot.() -> Either<NonEmptyList<E>, FixtWithNullableId>,
): FixtWithNullableValidatedKap<E, Rest> {
    val self = this
    return FixtWithNullableValidatedKap(self._kap.thenV(Kap { self.fa() }))
}

@kotlin.jvm.JvmName("thenValueV_id")
inline infix fun <E, Rest> FixtWithNullableValidatedKap<E, (FixtWithNullableId) -> Rest>.thenValueV(
    crossinline fa: suspend FixtWithNullableIdSlot.() -> Either<NonEmptyList<E>, FixtWithNullableId>,
): FixtWithNullableValidatedKap<E, Rest> {
    val self = this
    return FixtWithNullableValidatedKap(self._kap.thenValueV(Kap { self.fa() }))
}

@kotlin.jvm.JvmName("withV_name")
inline infix fun <E, Rest> FixtWithNullableValidatedKap<E, (FixtWithNullableName) -> Rest>.withV(
    crossinline fa: suspend FixtWithNullableNameSlot.() -> Either<NonEmptyList<E>, FixtWithNullableName>,
): FixtWithNullableValidatedKap<E, Rest> {
    val self = this
    return FixtWithNullableValidatedKap(self._kap.withV(Kap { self.fa() }))
}

@kotlin.jvm.JvmName("thenV_name")
inline infix fun <E, Rest> FixtWithNullableValidatedKap<E, (FixtWithNullableName) -> Rest>.thenV(
    crossinline fa: suspend FixtWithNullableNameSlot.() -> Either<NonEmptyList<E>, FixtWithNullableName>,
): FixtWithNullableValidatedKap<E, Rest> {
    val self = this
    return FixtWithNullableValidatedKap(self._kap.thenV(Kap { self.fa() }))
}

@kotlin.jvm.JvmName("thenValueV_name")
inline infix fun <E, Rest> FixtWithNullableValidatedKap<E, (FixtWithNullableName) -> Rest>.thenValueV(
    crossinline fa: suspend FixtWithNullableNameSlot.() -> Either<NonEmptyList<E>, FixtWithNullableName>,
): FixtWithNullableValidatedKap<E, Rest> {
    val self = this
    return FixtWithNullableValidatedKap(self._kap.thenValueV(Kap { self.fa() }))
}

@kotlin.jvm.JvmName("withV_count")
inline infix fun <E> FixtWithNullableValidatedKap<E, (FixtWithNullableCount) -> FixtWithNullable>.withV(
    crossinline fa: suspend FixtWithNullableCountSlot.() -> Either<NonEmptyList<E>, FixtWithNullableCount>,
): Kap<Either<NonEmptyList<E>, FixtWithNullable>> {
    val self = this
    return self._kap.withV(Kap { self.fa() })
}

@kotlin.jvm.JvmName("thenV_count")
inline infix fun <E> FixtWithNullableValidatedKap<E, (FixtWithNullableCount) -> FixtWithNullable>.thenV(
    crossinline fa: suspend FixtWithNullableCountSlot.() -> Either<NonEmptyList<E>, FixtWithNullableCount>,
): Kap<Either<NonEmptyList<E>, FixtWithNullable>> {
    val self = this
    return self._kap.thenV(Kap { self.fa() })
}

@kotlin.jvm.JvmName("thenValueV_count")
inline infix fun <E> FixtWithNullableValidatedKap<E, (FixtWithNullableCount) -> FixtWithNullable>.thenValueV(
    crossinline fa: suspend FixtWithNullableCountSlot.() -> Either<NonEmptyList<E>, FixtWithNullableCount>,
): Kap<Either<NonEmptyList<E>, FixtWithNullable>> {
    val self = this
    return self._kap.thenValueV(Kap { self.fa() })
}

infix fun <E, A, B> FixtWithNullableValidatedKap<E, (A) -> B>.withV(fa: Kap<Either<NonEmptyList<E>, A>>): FixtWithNullableValidatedKap<E, B> =
    FixtWithNullableValidatedKap(_kap.withV(fa))

infix fun <E, A, B> FixtWithNullableValidatedKap<E, (A) -> B>.thenV(fa: Kap<Either<NonEmptyList<E>, A>>): FixtWithNullableValidatedKap<E, B> =
    FixtWithNullableValidatedKap(_kap.thenV(fa))

infix fun <E, A, B> FixtWithNullableValidatedKap<E, (A) -> B>.thenValueV(fa: Kap<Either<NonEmptyList<E>, A>>): FixtWithNullableValidatedKap<E, B> =
    FixtWithNullableValidatedKap(_kap.thenValueV(fa))

infix fun <E> FixtWithNullableValidatedKap<E, (FixtWithNullableCount) -> FixtWithNullable>.withV(fa: Kap<Either<NonEmptyList<E>, FixtWithNullableCount>>): Kap<Either<NonEmptyList<E>, FixtWithNullable>> =
    _kap.withV(fa)

infix fun <E> FixtWithNullableValidatedKap<E, (FixtWithNullableCount) -> FixtWithNullable>.thenV(fa: Kap<Either<NonEmptyList<E>, FixtWithNullableCount>>): Kap<Either<NonEmptyList<E>, FixtWithNullable>> =
    _kap.thenV(fa)

infix fun <E> FixtWithNullableValidatedKap<E, (FixtWithNullableCount) -> FixtWithNullable>.thenValueV(fa: Kap<Either<NonEmptyList<E>, FixtWithNullableCount>>): Kap<Either<NonEmptyList<E>, FixtWithNullable>> =
    _kap.thenValueV(fa)

suspend fun <E, A> FixtWithNullableValidatedKap<E, A>.evalGraph(): Either<NonEmptyList<E>, A> = _kap.evalGraph()


/** Validated entry — `kapV(::C)` / `kapV<Double>(::C)` for generics. */
fun <E> kapV(f: (kotlin.Long, kotlin.String?, kotlin.Int?) -> FixtWithNullable): FixtWithNullableValidatedKap<E, (FixtWithNullableId) -> (FixtWithNullableName) -> (FixtWithNullableCount) -> FixtWithNullable> {
    val fn: (FixtWithNullableId) -> (FixtWithNullableName) -> (FixtWithNullableCount) -> FixtWithNullable = { p0: FixtWithNullableId -> { p1: FixtWithNullableName -> { p2: FixtWithNullableCount -> f(p0.value, p1.value, p2.value) } } }
    val kap: Kap<Either<NonEmptyList<E>, (FixtWithNullableId) -> (FixtWithNullableName) -> (FixtWithNullableCount) -> FixtWithNullable>> = Kap.of(Either.Right(fn))
    return FixtWithNullableValidatedKap(kap)
}

