// AUTO-GENERATED by kap-ksp — do not edit
import kap.Kap
import kap.KapLike
import kap.of
import kap.with
import kap.then
import kap.thenValue
import kap.map
import kap.andThen
import kap.evalGraph

// ── Opaque wrappers — one per field ──

data class FixtFiveUser(val value: kotlin.String)

data class FixtFiveCart(val value: kotlin.String)

data class FixtFiveStock(val value: kotlin.Boolean)

data class FixtFiveShipping(val value: kotlin.Double)

data class FixtFiveTax(val value: kotlin.Double)

// ── Tag classes (receivers for infix `from`) ──

class FixtFiveUserTag internal constructor()
class FixtFiveCartTag internal constructor()
class FixtFiveStockTag internal constructor()
class FixtFiveShippingTag internal constructor()
class FixtFiveTaxTag internal constructor()

// ── Infix `from` — wraps raw value or Kap<T> into the tagged wrapper ──

infix fun FixtFiveUserTag.from(value: kotlin.String): FixtFiveUser = FixtFiveUser(value)
infix fun FixtFiveUserTag.from(kap: Kap<kotlin.String>): Kap<FixtFiveUser> = kap.map(::FixtFiveUser)

infix fun FixtFiveCartTag.from(value: kotlin.String): FixtFiveCart = FixtFiveCart(value)
infix fun FixtFiveCartTag.from(kap: Kap<kotlin.String>): Kap<FixtFiveCart> = kap.map(::FixtFiveCart)

infix fun FixtFiveStockTag.from(value: kotlin.Boolean): FixtFiveStock = FixtFiveStock(value)
infix fun FixtFiveStockTag.from(kap: Kap<kotlin.Boolean>): Kap<FixtFiveStock> = kap.map(::FixtFiveStock)

infix fun FixtFiveShippingTag.from(value: kotlin.Double): FixtFiveShipping = FixtFiveShipping(value)
infix fun FixtFiveShippingTag.from(kap: Kap<kotlin.Double>): Kap<FixtFiveShipping> = kap.map(::FixtFiveShipping)

infix fun FixtFiveTaxTag.from(value: kotlin.Double): FixtFiveTax = FixtFiveTax(value)
infix fun FixtFiveTaxTag.from(kap: Kap<kotlin.Double>): Kap<FixtFiveTax> = kap.map(::FixtFiveTax)

// ── Per-slot interfaces (lambda receivers for `.with` / `.then`) ──

interface FixtFiveUserSlot { val user: FixtFiveUserTag }
interface FixtFiveCartSlot { val cart: FixtFiveCartTag }
interface FixtFiveStockSlot { val stock: FixtFiveStockTag }
interface FixtFiveShippingSlot { val shipping: FixtFiveShippingTag }
interface FixtFiveTaxSlot { val tax: FixtFiveTaxTag }

/** Scoped builder for @KapTypeSafe FixtFive. Implements every slot interface
 *  so each field is reachable as a member. The per-slot `.with` overloads
 *  below narrow the lambda receiver to a single tag — the IDE shows only the
 *  field expected at the current curry position when the body is empty.
 *
 *  The wrapper deliberately does NOT delegate to `Kap<F>`. If it did, the
 *  imported `Kap.with(suspend () -> A)` would compete with the slot-specific
 *  `.with { field from … }` and K2's overload resolution sometimes picks the
 *  generic one (before typechecking the lambda body), causing the slot's tag
 *  reference to fail with `Unresolved reference`.
 *
 *  The wrapper implements `KapLike<F>`, so kap-core operators (.map /
 *  .recover / .timeout / .settled / .memoize / .timed / .andThen /
 *  .evalGraph) are available directly on partial wrappers as well. For raw
 *  `Kap<F>` (e.g. an external API parameter), use `.asKap`.
 */
class FixtFiveKap<F>(@PublishedApi internal val _kap: Kap<F>) : KapLike<F>, FixtFiveUserSlot, FixtFiveCartSlot, FixtFiveStockSlot, FixtFiveShippingSlot, FixtFiveTaxSlot {
    override val asKap: Kap<F> get() = _kap
    override val user: FixtFiveUserTag = FixtFiveUserTag()
    override val cart: FixtFiveCartTag = FixtFiveCartTag()
    override val stock: FixtFiveStockTag = FixtFiveStockTag()
    override val shipping: FixtFiveShippingTag = FixtFiveShippingTag()
    override val tax: FixtFiveTaxTag = FixtFiveTaxTag()

    companion object {
        val user: FixtFiveUserTag = FixtFiveUserTag()
        val cart: FixtFiveCartTag = FixtFiveCartTag()
        val stock: FixtFiveStockTag = FixtFiveStockTag()
        val shipping: FixtFiveShippingTag = FixtFiveShippingTag()
        val tax: FixtFiveTaxTag = FixtFiveTaxTag()
    }
}

// ── Per-slot operators — IDE shows exactly the field expected at this position ──

@kotlin.jvm.JvmName("with_user")
inline infix fun <Rest> FixtFiveKap<(FixtFiveUser) -> Rest>.with(
    crossinline fa: suspend FixtFiveUserSlot.() -> FixtFiveUser,
): FixtFiveKap<Rest> {
    val self = this
    return FixtFiveKap(self._kap.with(suspend { self.fa() }))
}

@kotlin.jvm.JvmName("then_user")
inline infix fun <Rest> FixtFiveKap<(FixtFiveUser) -> Rest>.then(
    crossinline fa: suspend FixtFiveUserSlot.() -> FixtFiveUser,
): FixtFiveKap<Rest> {
    val self = this
    return FixtFiveKap(self._kap.then(suspend { self.fa() }))
}

@kotlin.jvm.JvmName("thenValue_user")
inline infix fun <Rest> FixtFiveKap<(FixtFiveUser) -> Rest>.thenValue(
    crossinline fa: suspend FixtFiveUserSlot.() -> FixtFiveUser,
): FixtFiveKap<Rest> {
    val self = this
    return FixtFiveKap(self._kap.thenValue(suspend { self.fa() }))
}

@kotlin.jvm.JvmName("with_cart")
inline infix fun <Rest> FixtFiveKap<(FixtFiveCart) -> Rest>.with(
    crossinline fa: suspend FixtFiveCartSlot.() -> FixtFiveCart,
): FixtFiveKap<Rest> {
    val self = this
    return FixtFiveKap(self._kap.with(suspend { self.fa() }))
}

@kotlin.jvm.JvmName("then_cart")
inline infix fun <Rest> FixtFiveKap<(FixtFiveCart) -> Rest>.then(
    crossinline fa: suspend FixtFiveCartSlot.() -> FixtFiveCart,
): FixtFiveKap<Rest> {
    val self = this
    return FixtFiveKap(self._kap.then(suspend { self.fa() }))
}

@kotlin.jvm.JvmName("thenValue_cart")
inline infix fun <Rest> FixtFiveKap<(FixtFiveCart) -> Rest>.thenValue(
    crossinline fa: suspend FixtFiveCartSlot.() -> FixtFiveCart,
): FixtFiveKap<Rest> {
    val self = this
    return FixtFiveKap(self._kap.thenValue(suspend { self.fa() }))
}

@kotlin.jvm.JvmName("with_stock")
inline infix fun <Rest> FixtFiveKap<(FixtFiveStock) -> Rest>.with(
    crossinline fa: suspend FixtFiveStockSlot.() -> FixtFiveStock,
): FixtFiveKap<Rest> {
    val self = this
    return FixtFiveKap(self._kap.with(suspend { self.fa() }))
}

@kotlin.jvm.JvmName("then_stock")
inline infix fun <Rest> FixtFiveKap<(FixtFiveStock) -> Rest>.then(
    crossinline fa: suspend FixtFiveStockSlot.() -> FixtFiveStock,
): FixtFiveKap<Rest> {
    val self = this
    return FixtFiveKap(self._kap.then(suspend { self.fa() }))
}

@kotlin.jvm.JvmName("thenValue_stock")
inline infix fun <Rest> FixtFiveKap<(FixtFiveStock) -> Rest>.thenValue(
    crossinline fa: suspend FixtFiveStockSlot.() -> FixtFiveStock,
): FixtFiveKap<Rest> {
    val self = this
    return FixtFiveKap(self._kap.thenValue(suspend { self.fa() }))
}

@kotlin.jvm.JvmName("with_shipping")
inline infix fun <Rest> FixtFiveKap<(FixtFiveShipping) -> Rest>.with(
    crossinline fa: suspend FixtFiveShippingSlot.() -> FixtFiveShipping,
): FixtFiveKap<Rest> {
    val self = this
    return FixtFiveKap(self._kap.with(suspend { self.fa() }))
}

@kotlin.jvm.JvmName("then_shipping")
inline infix fun <Rest> FixtFiveKap<(FixtFiveShipping) -> Rest>.then(
    crossinline fa: suspend FixtFiveShippingSlot.() -> FixtFiveShipping,
): FixtFiveKap<Rest> {
    val self = this
    return FixtFiveKap(self._kap.then(suspend { self.fa() }))
}

@kotlin.jvm.JvmName("thenValue_shipping")
inline infix fun <Rest> FixtFiveKap<(FixtFiveShipping) -> Rest>.thenValue(
    crossinline fa: suspend FixtFiveShippingSlot.() -> FixtFiveShipping,
): FixtFiveKap<Rest> {
    val self = this
    return FixtFiveKap(self._kap.thenValue(suspend { self.fa() }))
}

@kotlin.jvm.JvmName("with_tax")
inline infix fun FixtFiveKap<(FixtFiveTax) -> FixtFive>.with(
    crossinline fa: suspend FixtFiveTaxSlot.() -> FixtFiveTax,
): Kap<FixtFive> {
    val self = this
    return self._kap.with(suspend { self.fa() })
}

@kotlin.jvm.JvmName("then_tax")
inline infix fun FixtFiveKap<(FixtFiveTax) -> FixtFive>.then(
    crossinline fa: suspend FixtFiveTaxSlot.() -> FixtFiveTax,
): Kap<FixtFive> {
    val self = this
    return self._kap.then(suspend { self.fa() })
}

@kotlin.jvm.JvmName("thenValue_tax")
inline infix fun FixtFiveKap<(FixtFiveTax) -> FixtFive>.thenValue(
    crossinline fa: suspend FixtFiveTaxSlot.() -> FixtFiveTax,
): Kap<FixtFive> {
    val self = this
    return self._kap.thenValue(suspend { self.fa() })
}

infix fun <A, B> FixtFiveKap<(A) -> B>.with(fa: Kap<A>): FixtFiveKap<B> =
    FixtFiveKap(_kap.with(fa))

infix fun <A, B> FixtFiveKap<(A) -> B>.then(fa: Kap<A>): FixtFiveKap<B> =
    FixtFiveKap(_kap.then(fa))

infix fun <A, B> FixtFiveKap<(A) -> B>.thenValue(fa: Kap<A>): FixtFiveKap<B> =
    FixtFiveKap(_kap.thenValue(fa))

infix fun FixtFiveKap<(FixtFiveTax) -> FixtFive>.with(fa: Kap<FixtFiveTax>): Kap<FixtFive> =
    _kap.with(fa)

infix fun FixtFiveKap<(FixtFiveTax) -> FixtFive>.then(fa: Kap<FixtFiveTax>): Kap<FixtFive> =
    _kap.then(fa)

infix fun FixtFiveKap<(FixtFiveTax) -> FixtFive>.thenValue(fa: Kap<FixtFiveTax>): Kap<FixtFive> =
    _kap.thenValue(fa)

inline infix fun <A, B> FixtFiveKap<A>.andThen(
    crossinline f: (A) -> Kap<B>,
): Kap<B> = _kap.andThen(f)

suspend fun <A> FixtFiveKap<A>.evalGraph(): A = _kap.evalGraph()


/** Official entry — `kap(::C)` plain, `kap<Double>(::C)` for generics. */
fun kap(f: (kotlin.String, kotlin.String, kotlin.Boolean, kotlin.Double, kotlin.Double) -> FixtFive): FixtFiveKap<(FixtFiveUser) -> (FixtFiveCart) -> (FixtFiveStock) -> (FixtFiveShipping) -> (FixtFiveTax) -> FixtFive> =
    FixtFiveKap(Kap.of({ p0: FixtFiveUser -> { p1: FixtFiveCart -> { p2: FixtFiveStock -> { p3: FixtFiveShipping -> { p4: FixtFiveTax -> f(p0.value, p1.value, p2.value, p3.value, p4.value) } } } } }))

