// AUTO-GENERATED by kap-ksp — do not edit
import kap.Kap
import kap.KapLike
import kap.of
import kap.with
import kap.then
import kap.thenValue
import kap.map
import kap.andThen
import kap.evalGraph

// ── Opaque wrappers — one per field ──

data class FixtGenericFnSeed<T>(val value: T)

data class FixtGenericFnN(val value: kotlin.Int)

// ── Tag classes (receivers for infix `from`) ──

class FixtGenericFnSeedTag internal constructor()
class FixtGenericFnNTag internal constructor()

// ── Infix `from` — wraps raw value or Kap<T> into the tagged wrapper ──

infix fun <T> FixtGenericFnSeedTag.from(value: T): FixtGenericFnSeed<T> = FixtGenericFnSeed(value)
infix fun <T> FixtGenericFnSeedTag.from(kap: Kap<T>): Kap<FixtGenericFnSeed<T>> = kap.map(::FixtGenericFnSeed)

infix fun FixtGenericFnNTag.from(value: kotlin.Int): FixtGenericFnN = FixtGenericFnN(value)
infix fun FixtGenericFnNTag.from(kap: Kap<kotlin.Int>): Kap<FixtGenericFnN> = kap.map(::FixtGenericFnN)

// ── Per-slot interfaces (lambda receivers for `.with` / `.then`) ──

interface FixtGenericFnSeedSlot { val seed: FixtGenericFnSeedTag }
interface FixtGenericFnNSlot { val n: FixtGenericFnNTag }

/** Scoped builder for @KapTypeSafe FixtGenericFn. Implements every slot interface
 *  so each field is reachable as a member. The per-slot `.with` overloads
 *  below narrow the lambda receiver to a single tag — the IDE shows only the
 *  field expected at the current curry position when the body is empty.
 *
 *  The wrapper deliberately does NOT delegate to `Kap<F>`. If it did, the
 *  imported `Kap.with(suspend () -> A)` would compete with the slot-specific
 *  `.with { field from … }` and K2's overload resolution sometimes picks the
 *  generic one (before typechecking the lambda body), causing the slot's tag
 *  reference to fail with `Unresolved reference`.
 *
 *  The wrapper implements `KapLike<F>`, so kap-core operators (.map /
 *  .recover / .timeout / .settled / .memoize / .timed / .andThen /
 *  .evalGraph) are available directly on partial wrappers as well. For raw
 *  `Kap<F>` (e.g. an external API parameter), use `.asKap`.
 */
class FixtGenericFnKap<F>(@PublishedApi internal val _kap: Kap<F>) : KapLike<F>, FixtGenericFnSeedSlot, FixtGenericFnNSlot {
    override val asKap: Kap<F> get() = _kap
    override val seed: FixtGenericFnSeedTag = FixtGenericFnSeedTag()
    override val n: FixtGenericFnNTag = FixtGenericFnNTag()

    companion object {
        val seed: FixtGenericFnSeedTag = FixtGenericFnSeedTag()
        val n: FixtGenericFnNTag = FixtGenericFnNTag()
    }
}

// ── Per-slot operators — IDE shows exactly the field expected at this position ──

@kotlin.jvm.JvmName("with_seed")
inline infix fun <T, Rest> FixtGenericFnKap<(FixtGenericFnSeed<T>) -> Rest>.with(
    crossinline fa: suspend FixtGenericFnSeedSlot.() -> FixtGenericFnSeed<T>,
): FixtGenericFnKap<Rest> {
    val self = this
    return FixtGenericFnKap(self._kap.with(suspend { self.fa() }))
}

@kotlin.jvm.JvmName("then_seed")
inline infix fun <T, Rest> FixtGenericFnKap<(FixtGenericFnSeed<T>) -> Rest>.then(
    crossinline fa: suspend FixtGenericFnSeedSlot.() -> FixtGenericFnSeed<T>,
): FixtGenericFnKap<Rest> {
    val self = this
    return FixtGenericFnKap(self._kap.then(suspend { self.fa() }))
}

@kotlin.jvm.JvmName("thenValue_seed")
inline infix fun <T, Rest> FixtGenericFnKap<(FixtGenericFnSeed<T>) -> Rest>.thenValue(
    crossinline fa: suspend FixtGenericFnSeedSlot.() -> FixtGenericFnSeed<T>,
): FixtGenericFnKap<Rest> {
    val self = this
    return FixtGenericFnKap(self._kap.thenValue(suspend { self.fa() }))
}

@kotlin.jvm.JvmName("with_n")
inline infix fun <T> FixtGenericFnKap<(FixtGenericFnN) -> kotlin.Pair<T, kotlin.Int>>.with(
    crossinline fa: suspend FixtGenericFnNSlot.() -> FixtGenericFnN,
): Kap<kotlin.Pair<T, kotlin.Int>> {
    val self = this
    return self._kap.with(suspend { self.fa() })
}

@kotlin.jvm.JvmName("then_n")
inline infix fun <T> FixtGenericFnKap<(FixtGenericFnN) -> kotlin.Pair<T, kotlin.Int>>.then(
    crossinline fa: suspend FixtGenericFnNSlot.() -> FixtGenericFnN,
): Kap<kotlin.Pair<T, kotlin.Int>> {
    val self = this
    return self._kap.then(suspend { self.fa() })
}

@kotlin.jvm.JvmName("thenValue_n")
inline infix fun <T> FixtGenericFnKap<(FixtGenericFnN) -> kotlin.Pair<T, kotlin.Int>>.thenValue(
    crossinline fa: suspend FixtGenericFnNSlot.() -> FixtGenericFnN,
): Kap<kotlin.Pair<T, kotlin.Int>> {
    val self = this
    return self._kap.thenValue(suspend { self.fa() })
}

infix fun <A, B> FixtGenericFnKap<(A) -> B>.with(fa: Kap<A>): FixtGenericFnKap<B> =
    FixtGenericFnKap(_kap.with(fa))

infix fun <A, B> FixtGenericFnKap<(A) -> B>.then(fa: Kap<A>): FixtGenericFnKap<B> =
    FixtGenericFnKap(_kap.then(fa))

infix fun <A, B> FixtGenericFnKap<(A) -> B>.thenValue(fa: Kap<A>): FixtGenericFnKap<B> =
    FixtGenericFnKap(_kap.thenValue(fa))

infix fun <T> FixtGenericFnKap<(FixtGenericFnN) -> kotlin.Pair<T, kotlin.Int>>.with(fa: Kap<FixtGenericFnN>): Kap<kotlin.Pair<T, kotlin.Int>> =
    _kap.with(fa)

infix fun <T> FixtGenericFnKap<(FixtGenericFnN) -> kotlin.Pair<T, kotlin.Int>>.then(fa: Kap<FixtGenericFnN>): Kap<kotlin.Pair<T, kotlin.Int>> =
    _kap.then(fa)

infix fun <T> FixtGenericFnKap<(FixtGenericFnN) -> kotlin.Pair<T, kotlin.Int>>.thenValue(fa: Kap<FixtGenericFnN>): Kap<kotlin.Pair<T, kotlin.Int>> =
    _kap.thenValue(fa)

inline infix fun <A, B> FixtGenericFnKap<A>.andThen(
    crossinline f: (A) -> Kap<B>,
): Kap<B> = _kap.andThen(f)

suspend fun <A> FixtGenericFnKap<A>.evalGraph(): A = _kap.evalGraph()


/** Official entry point — returns FixtGenericFnKap so `.with { field from value }` works without imports. */
fun <T> kapFixtGenericFn(): FixtGenericFnKap<(FixtGenericFnSeed<T>) -> (FixtGenericFnN) -> kotlin.Pair<T, kotlin.Int>> =
    FixtGenericFnKap(Kap.of({ p0: FixtGenericFnSeed<T> -> { p1: FixtGenericFnN -> fixtGenericFn(p0.value, p1.value) } }))

/** Extension property — enables `(::myFn).kap` and `kap((::myFn)::kap)` forms. */
val <T> ((T, kotlin.Int) -> kotlin.Pair<T, kotlin.Int>).kap: FixtGenericFnKap<(FixtGenericFnSeed<T>) -> (FixtGenericFnN) -> kotlin.Pair<T, kotlin.Int>>
    get() = FixtGenericFnKap(Kap.of({ p0: FixtGenericFnSeed<T> -> { p1: FixtGenericFnN -> this(p0.value, p1.value) } }))
