// AUTO-GENERATED by kap-ksp — do not edit
import arrow.core.Either
import arrow.core.NonEmptyList
import kap.Kap
import kap.KapLike
import kap.of
import kap.withV
import kap.thenV
import kap.thenValueV
import kap.evalGraph

// ── Validated infix `from` — maps Either<Nel<E>, FieldType> into tagged wrapper ──

infix fun <E, Rest> FixtParamRestBodyTag.from(value: Either<NonEmptyList<E>, Rest>): Either<NonEmptyList<E>, FixtParamRestBody<Rest>> =
    value.map(::FixtParamRestBody)

infix fun <E> FixtParamRestCountTag.from(value: Either<NonEmptyList<E>, kotlin.Int>): Either<NonEmptyList<E>, FixtParamRestCount> =
    value.map(::FixtParamRestCount)

/** Validated scoped builder for @KapTypeSafe FixtParamRest. Uses the same per-slot
 *  tag interfaces as FixtParamRestKap — each `.withV { field from validateField() }`
 *  narrows the receiver to one slot, accumulating errors via Arrow's applicative.
 */
class FixtParamRestValidatedKap<E, F>(@PublishedApi internal val _kap: Kap<Either<NonEmptyList<E>, F>>) : KapLike<Either<NonEmptyList<E>, F>>, FixtParamRestBodySlot, FixtParamRestCountSlot {
    override val asKap: Kap<Either<NonEmptyList<E>, F>> get() = _kap
    override val body: FixtParamRestBodyTag = FixtParamRestBodyTag()
    override val count: FixtParamRestCountTag = FixtParamRestCountTag()

    companion object {
        val body: FixtParamRestBodyTag = FixtParamRestBodyTag()
        val count: FixtParamRestCountTag = FixtParamRestCountTag()
    }
}

// ── Per-slot .withV / .thenV / .thenValueV operators ──

@kotlin.jvm.JvmName("withV_body")
inline infix fun <E, Rest, Rest_> FixtParamRestValidatedKap<E, (FixtParamRestBody<Rest>) -> Rest_>.withV(
    crossinline fa: suspend FixtParamRestBodySlot.() -> Either<NonEmptyList<E>, FixtParamRestBody<Rest>>,
): FixtParamRestValidatedKap<E, Rest_> {
    val self = this
    return FixtParamRestValidatedKap(self._kap.withV(Kap { self.fa() }))
}

@kotlin.jvm.JvmName("thenV_body")
inline infix fun <E, Rest, Rest_> FixtParamRestValidatedKap<E, (FixtParamRestBody<Rest>) -> Rest_>.thenV(
    crossinline fa: suspend FixtParamRestBodySlot.() -> Either<NonEmptyList<E>, FixtParamRestBody<Rest>>,
): FixtParamRestValidatedKap<E, Rest_> {
    val self = this
    return FixtParamRestValidatedKap(self._kap.thenV(Kap { self.fa() }))
}

@kotlin.jvm.JvmName("thenValueV_body")
inline infix fun <E, Rest, Rest_> FixtParamRestValidatedKap<E, (FixtParamRestBody<Rest>) -> Rest_>.thenValueV(
    crossinline fa: suspend FixtParamRestBodySlot.() -> Either<NonEmptyList<E>, FixtParamRestBody<Rest>>,
): FixtParamRestValidatedKap<E, Rest_> {
    val self = this
    return FixtParamRestValidatedKap(self._kap.thenValueV(Kap { self.fa() }))
}

@kotlin.jvm.JvmName("withV_count")
inline infix fun <E, Rest> FixtParamRestValidatedKap<E, (FixtParamRestCount) -> FixtParamRest<Rest>>.withV(
    crossinline fa: suspend FixtParamRestCountSlot.() -> Either<NonEmptyList<E>, FixtParamRestCount>,
): Kap<Either<NonEmptyList<E>, FixtParamRest<Rest>>> {
    val self = this
    return self._kap.withV(Kap { self.fa() })
}

@kotlin.jvm.JvmName("thenV_count")
inline infix fun <E, Rest> FixtParamRestValidatedKap<E, (FixtParamRestCount) -> FixtParamRest<Rest>>.thenV(
    crossinline fa: suspend FixtParamRestCountSlot.() -> Either<NonEmptyList<E>, FixtParamRestCount>,
): Kap<Either<NonEmptyList<E>, FixtParamRest<Rest>>> {
    val self = this
    return self._kap.thenV(Kap { self.fa() })
}

@kotlin.jvm.JvmName("thenValueV_count")
inline infix fun <E, Rest> FixtParamRestValidatedKap<E, (FixtParamRestCount) -> FixtParamRest<Rest>>.thenValueV(
    crossinline fa: suspend FixtParamRestCountSlot.() -> Either<NonEmptyList<E>, FixtParamRestCount>,
): Kap<Either<NonEmptyList<E>, FixtParamRest<Rest>>> {
    val self = this
    return self._kap.thenValueV(Kap { self.fa() })
}

infix fun <E, A, B> FixtParamRestValidatedKap<E, (A) -> B>.withV(fa: Kap<Either<NonEmptyList<E>, A>>): FixtParamRestValidatedKap<E, B> =
    FixtParamRestValidatedKap(_kap.withV(fa))

infix fun <E, A, B> FixtParamRestValidatedKap<E, (A) -> B>.thenV(fa: Kap<Either<NonEmptyList<E>, A>>): FixtParamRestValidatedKap<E, B> =
    FixtParamRestValidatedKap(_kap.thenV(fa))

infix fun <E, A, B> FixtParamRestValidatedKap<E, (A) -> B>.thenValueV(fa: Kap<Either<NonEmptyList<E>, A>>): FixtParamRestValidatedKap<E, B> =
    FixtParamRestValidatedKap(_kap.thenValueV(fa))

infix fun <E, Rest> FixtParamRestValidatedKap<E, (FixtParamRestCount) -> FixtParamRest<Rest>>.withV(fa: Kap<Either<NonEmptyList<E>, FixtParamRestCount>>): Kap<Either<NonEmptyList<E>, FixtParamRest<Rest>>> =
    _kap.withV(fa)

infix fun <E, Rest> FixtParamRestValidatedKap<E, (FixtParamRestCount) -> FixtParamRest<Rest>>.thenV(fa: Kap<Either<NonEmptyList<E>, FixtParamRestCount>>): Kap<Either<NonEmptyList<E>, FixtParamRest<Rest>>> =
    _kap.thenV(fa)

infix fun <E, Rest> FixtParamRestValidatedKap<E, (FixtParamRestCount) -> FixtParamRest<Rest>>.thenValueV(fa: Kap<Either<NonEmptyList<E>, FixtParamRestCount>>): Kap<Either<NonEmptyList<E>, FixtParamRest<Rest>>> =
    _kap.thenValueV(fa)

suspend fun <E, A> FixtParamRestValidatedKap<E, A>.evalGraph(): Either<NonEmptyList<E>, A> = _kap.evalGraph()


/** Validated entry — returns FixtParamRestValidatedKap so `.withV { field from validate() }` works without imports. */
fun <E, Rest> kapVFixtParamRest(): FixtParamRestValidatedKap<E, (FixtParamRestBody<Rest>) -> (FixtParamRestCount) -> FixtParamRest<Rest>> {
    val fn: (FixtParamRestBody<Rest>) -> (FixtParamRestCount) -> FixtParamRest<Rest> = { p0: FixtParamRestBody<Rest> -> { p1: FixtParamRestCount -> FixtParamRest(p0.value, p1.value) } }
    val kap: Kap<Either<NonEmptyList<E>, (FixtParamRestBody<Rest>) -> (FixtParamRestCount) -> FixtParamRest<Rest>>> = Kap.of(Either.Right(fn))
    return FixtParamRestValidatedKap(kap)
}
