// AUTO-GENERATED by kap-ksp — do not edit
import arrow.core.Either
import arrow.core.NonEmptyList
import kap.Kap
import kap.KapLike
import kap.of
import kap.withV
import kap.thenV
import kap.thenValueV
import kap.evalGraph

// ── Validated infix `from` — maps Either<Nel<E>, FieldType> into tagged wrapper ──

infix fun <E> FixtFiveUserTag.from(value: Either<NonEmptyList<E>, kotlin.String>): Either<NonEmptyList<E>, FixtFiveUser> =
    value.map(::FixtFiveUser)

infix fun <E> FixtFiveCartTag.from(value: Either<NonEmptyList<E>, kotlin.String>): Either<NonEmptyList<E>, FixtFiveCart> =
    value.map(::FixtFiveCart)

infix fun <E> FixtFiveStockTag.from(value: Either<NonEmptyList<E>, kotlin.Boolean>): Either<NonEmptyList<E>, FixtFiveStock> =
    value.map(::FixtFiveStock)

infix fun <E> FixtFiveShippingTag.from(value: Either<NonEmptyList<E>, kotlin.Double>): Either<NonEmptyList<E>, FixtFiveShipping> =
    value.map(::FixtFiveShipping)

infix fun <E> FixtFiveTaxTag.from(value: Either<NonEmptyList<E>, kotlin.Double>): Either<NonEmptyList<E>, FixtFiveTax> =
    value.map(::FixtFiveTax)

/** Validated scoped builder for @KapTypeSafe FixtFive. Uses the same per-slot
 *  tag interfaces as FixtFiveKap — each `.withV { field from validateField() }`
 *  narrows the receiver to one slot, accumulating errors via Arrow's applicative.
 */
class FixtFiveValidatedKap<E, F>(@PublishedApi internal val _kap: Kap<Either<NonEmptyList<E>, F>>) : KapLike<Either<NonEmptyList<E>, F>>, FixtFiveUserSlot, FixtFiveCartSlot, FixtFiveStockSlot, FixtFiveShippingSlot, FixtFiveTaxSlot {
    override val asKap: Kap<Either<NonEmptyList<E>, F>> get() = _kap
    override val user: FixtFiveUserTag = FixtFiveUserTag()
    override val cart: FixtFiveCartTag = FixtFiveCartTag()
    override val stock: FixtFiveStockTag = FixtFiveStockTag()
    override val shipping: FixtFiveShippingTag = FixtFiveShippingTag()
    override val tax: FixtFiveTaxTag = FixtFiveTaxTag()

    companion object {
        val user: FixtFiveUserTag = FixtFiveUserTag()
        val cart: FixtFiveCartTag = FixtFiveCartTag()
        val stock: FixtFiveStockTag = FixtFiveStockTag()
        val shipping: FixtFiveShippingTag = FixtFiveShippingTag()
        val tax: FixtFiveTaxTag = FixtFiveTaxTag()
    }
}

// ── Per-slot .withV / .thenV / .thenValueV operators ──

@kotlin.jvm.JvmName("withV_user")
inline infix fun <E, Rest> FixtFiveValidatedKap<E, (FixtFiveUser) -> Rest>.withV(
    crossinline fa: suspend FixtFiveUserSlot.() -> Either<NonEmptyList<E>, FixtFiveUser>,
): FixtFiveValidatedKap<E, Rest> {
    val self = this
    return FixtFiveValidatedKap(self._kap.withV(Kap { self.fa() }))
}

@kotlin.jvm.JvmName("thenV_user")
inline infix fun <E, Rest> FixtFiveValidatedKap<E, (FixtFiveUser) -> Rest>.thenV(
    crossinline fa: suspend FixtFiveUserSlot.() -> Either<NonEmptyList<E>, FixtFiveUser>,
): FixtFiveValidatedKap<E, Rest> {
    val self = this
    return FixtFiveValidatedKap(self._kap.thenV(Kap { self.fa() }))
}

@kotlin.jvm.JvmName("thenValueV_user")
inline infix fun <E, Rest> FixtFiveValidatedKap<E, (FixtFiveUser) -> Rest>.thenValueV(
    crossinline fa: suspend FixtFiveUserSlot.() -> Either<NonEmptyList<E>, FixtFiveUser>,
): FixtFiveValidatedKap<E, Rest> {
    val self = this
    return FixtFiveValidatedKap(self._kap.thenValueV(Kap { self.fa() }))
}

@kotlin.jvm.JvmName("withV_cart")
inline infix fun <E, Rest> FixtFiveValidatedKap<E, (FixtFiveCart) -> Rest>.withV(
    crossinline fa: suspend FixtFiveCartSlot.() -> Either<NonEmptyList<E>, FixtFiveCart>,
): FixtFiveValidatedKap<E, Rest> {
    val self = this
    return FixtFiveValidatedKap(self._kap.withV(Kap { self.fa() }))
}

@kotlin.jvm.JvmName("thenV_cart")
inline infix fun <E, Rest> FixtFiveValidatedKap<E, (FixtFiveCart) -> Rest>.thenV(
    crossinline fa: suspend FixtFiveCartSlot.() -> Either<NonEmptyList<E>, FixtFiveCart>,
): FixtFiveValidatedKap<E, Rest> {
    val self = this
    return FixtFiveValidatedKap(self._kap.thenV(Kap { self.fa() }))
}

@kotlin.jvm.JvmName("thenValueV_cart")
inline infix fun <E, Rest> FixtFiveValidatedKap<E, (FixtFiveCart) -> Rest>.thenValueV(
    crossinline fa: suspend FixtFiveCartSlot.() -> Either<NonEmptyList<E>, FixtFiveCart>,
): FixtFiveValidatedKap<E, Rest> {
    val self = this
    return FixtFiveValidatedKap(self._kap.thenValueV(Kap { self.fa() }))
}

@kotlin.jvm.JvmName("withV_stock")
inline infix fun <E, Rest> FixtFiveValidatedKap<E, (FixtFiveStock) -> Rest>.withV(
    crossinline fa: suspend FixtFiveStockSlot.() -> Either<NonEmptyList<E>, FixtFiveStock>,
): FixtFiveValidatedKap<E, Rest> {
    val self = this
    return FixtFiveValidatedKap(self._kap.withV(Kap { self.fa() }))
}

@kotlin.jvm.JvmName("thenV_stock")
inline infix fun <E, Rest> FixtFiveValidatedKap<E, (FixtFiveStock) -> Rest>.thenV(
    crossinline fa: suspend FixtFiveStockSlot.() -> Either<NonEmptyList<E>, FixtFiveStock>,
): FixtFiveValidatedKap<E, Rest> {
    val self = this
    return FixtFiveValidatedKap(self._kap.thenV(Kap { self.fa() }))
}

@kotlin.jvm.JvmName("thenValueV_stock")
inline infix fun <E, Rest> FixtFiveValidatedKap<E, (FixtFiveStock) -> Rest>.thenValueV(
    crossinline fa: suspend FixtFiveStockSlot.() -> Either<NonEmptyList<E>, FixtFiveStock>,
): FixtFiveValidatedKap<E, Rest> {
    val self = this
    return FixtFiveValidatedKap(self._kap.thenValueV(Kap { self.fa() }))
}

@kotlin.jvm.JvmName("withV_shipping")
inline infix fun <E, Rest> FixtFiveValidatedKap<E, (FixtFiveShipping) -> Rest>.withV(
    crossinline fa: suspend FixtFiveShippingSlot.() -> Either<NonEmptyList<E>, FixtFiveShipping>,
): FixtFiveValidatedKap<E, Rest> {
    val self = this
    return FixtFiveValidatedKap(self._kap.withV(Kap { self.fa() }))
}

@kotlin.jvm.JvmName("thenV_shipping")
inline infix fun <E, Rest> FixtFiveValidatedKap<E, (FixtFiveShipping) -> Rest>.thenV(
    crossinline fa: suspend FixtFiveShippingSlot.() -> Either<NonEmptyList<E>, FixtFiveShipping>,
): FixtFiveValidatedKap<E, Rest> {
    val self = this
    return FixtFiveValidatedKap(self._kap.thenV(Kap { self.fa() }))
}

@kotlin.jvm.JvmName("thenValueV_shipping")
inline infix fun <E, Rest> FixtFiveValidatedKap<E, (FixtFiveShipping) -> Rest>.thenValueV(
    crossinline fa: suspend FixtFiveShippingSlot.() -> Either<NonEmptyList<E>, FixtFiveShipping>,
): FixtFiveValidatedKap<E, Rest> {
    val self = this
    return FixtFiveValidatedKap(self._kap.thenValueV(Kap { self.fa() }))
}

@kotlin.jvm.JvmName("withV_tax")
inline infix fun <E> FixtFiveValidatedKap<E, (FixtFiveTax) -> FixtFive>.withV(
    crossinline fa: suspend FixtFiveTaxSlot.() -> Either<NonEmptyList<E>, FixtFiveTax>,
): Kap<Either<NonEmptyList<E>, FixtFive>> {
    val self = this
    return self._kap.withV(Kap { self.fa() })
}

@kotlin.jvm.JvmName("thenV_tax")
inline infix fun <E> FixtFiveValidatedKap<E, (FixtFiveTax) -> FixtFive>.thenV(
    crossinline fa: suspend FixtFiveTaxSlot.() -> Either<NonEmptyList<E>, FixtFiveTax>,
): Kap<Either<NonEmptyList<E>, FixtFive>> {
    val self = this
    return self._kap.thenV(Kap { self.fa() })
}

@kotlin.jvm.JvmName("thenValueV_tax")
inline infix fun <E> FixtFiveValidatedKap<E, (FixtFiveTax) -> FixtFive>.thenValueV(
    crossinline fa: suspend FixtFiveTaxSlot.() -> Either<NonEmptyList<E>, FixtFiveTax>,
): Kap<Either<NonEmptyList<E>, FixtFive>> {
    val self = this
    return self._kap.thenValueV(Kap { self.fa() })
}

infix fun <E, A, B> FixtFiveValidatedKap<E, (A) -> B>.withV(fa: Kap<Either<NonEmptyList<E>, A>>): FixtFiveValidatedKap<E, B> =
    FixtFiveValidatedKap(_kap.withV(fa))

infix fun <E, A, B> FixtFiveValidatedKap<E, (A) -> B>.thenV(fa: Kap<Either<NonEmptyList<E>, A>>): FixtFiveValidatedKap<E, B> =
    FixtFiveValidatedKap(_kap.thenV(fa))

infix fun <E, A, B> FixtFiveValidatedKap<E, (A) -> B>.thenValueV(fa: Kap<Either<NonEmptyList<E>, A>>): FixtFiveValidatedKap<E, B> =
    FixtFiveValidatedKap(_kap.thenValueV(fa))

infix fun <E> FixtFiveValidatedKap<E, (FixtFiveTax) -> FixtFive>.withV(fa: Kap<Either<NonEmptyList<E>, FixtFiveTax>>): Kap<Either<NonEmptyList<E>, FixtFive>> =
    _kap.withV(fa)

infix fun <E> FixtFiveValidatedKap<E, (FixtFiveTax) -> FixtFive>.thenV(fa: Kap<Either<NonEmptyList<E>, FixtFiveTax>>): Kap<Either<NonEmptyList<E>, FixtFive>> =
    _kap.thenV(fa)

infix fun <E> FixtFiveValidatedKap<E, (FixtFiveTax) -> FixtFive>.thenValueV(fa: Kap<Either<NonEmptyList<E>, FixtFiveTax>>): Kap<Either<NonEmptyList<E>, FixtFive>> =
    _kap.thenValueV(fa)

suspend fun <E, A> FixtFiveValidatedKap<E, A>.evalGraph(): Either<NonEmptyList<E>, A> = _kap.evalGraph()


/** Validated entry — `kapV(::C)` / `kapV<Double>(::C)` for generics. */
fun <E> kapV(f: (kotlin.String, kotlin.String, kotlin.Boolean, kotlin.Double, kotlin.Double) -> FixtFive): FixtFiveValidatedKap<E, (FixtFiveUser) -> (FixtFiveCart) -> (FixtFiveStock) -> (FixtFiveShipping) -> (FixtFiveTax) -> FixtFive> {
    val fn: (FixtFiveUser) -> (FixtFiveCart) -> (FixtFiveStock) -> (FixtFiveShipping) -> (FixtFiveTax) -> FixtFive = { p0: FixtFiveUser -> { p1: FixtFiveCart -> { p2: FixtFiveStock -> { p3: FixtFiveShipping -> { p4: FixtFiveTax -> f(p0.value, p1.value, p2.value, p3.value, p4.value) } } } } }
    val kap: Kap<Either<NonEmptyList<E>, (FixtFiveUser) -> (FixtFiveCart) -> (FixtFiveStock) -> (FixtFiveShipping) -> (FixtFiveTax) -> FixtFive>> = Kap.of(Either.Right(fn))
    return FixtFiveValidatedKap(kap)
}

