// AUTO-GENERATED by kap-ksp — do not edit
import kap.Kap
import kap.KapLike
import kap.of
import kap.with
import kap.then
import kap.thenValue
import kap.map
import kap.andThen
import kap.evalGraph

// ── Opaque wrappers — one per field ──

data class FixtPfxTwoA(val value: kotlin.String)

// ── Tag classes (receivers for infix `from`) ──

class FixtPfxTwoATag internal constructor()

// ── Infix `from` — wraps raw value or Kap<T> into the tagged wrapper ──

infix fun FixtPfxTwoATag.from(value: kotlin.String): FixtPfxTwoA = FixtPfxTwoA(value)
infix fun FixtPfxTwoATag.from(kap: Kap<kotlin.String>): Kap<FixtPfxTwoA> = kap.map(::FixtPfxTwoA)

// ── Per-slot interfaces (lambda receivers for `.with` / `.then`) ──

interface FixtPfxTwoASlot { val a: FixtPfxTwoATag }

/** Scoped builder for @KapTypeSafe FixtPfxTwo. Implements every slot interface
 *  so each field is reachable as a member. The per-slot `.with` overloads
 *  below narrow the lambda receiver to a single tag — the IDE shows only the
 *  field expected at the current curry position when the body is empty.
 *
 *  The wrapper deliberately does NOT delegate to `Kap<F>`. If it did, the
 *  imported `Kap.with(suspend () -> A)` would compete with the slot-specific
 *  `.with { field from … }` and K2's overload resolution sometimes picks the
 *  generic one (before typechecking the lambda body), causing the slot's tag
 *  reference to fail with `Unresolved reference`.
 *
 *  The wrapper implements `KapLike<F>`, so kap-core operators (.map /
 *  .recover / .timeout / .settled / .memoize / .timed / .andThen /
 *  .evalGraph) are available directly on partial wrappers as well. For raw
 *  `Kap<F>` (e.g. an external API parameter), use `.asKap`.
 */
class FixtPfxTwoKap<F>(@PublishedApi internal val _kap: Kap<F>) : KapLike<F>, FixtPfxTwoASlot {
    override val asKap: Kap<F> get() = _kap
    override val a: FixtPfxTwoATag = FixtPfxTwoATag()

    companion object {
        val a: FixtPfxTwoATag = FixtPfxTwoATag()
    }
}

// ── Per-slot operators — IDE shows exactly the field expected at this position ──

@kotlin.jvm.JvmName("with_a")
inline infix fun FixtPfxTwoKap<(FixtPfxTwoA) -> kotlin.Int>.with(
    crossinline fa: suspend FixtPfxTwoASlot.() -> FixtPfxTwoA,
): Kap<kotlin.Int> {
    val self = this
    return self._kap.with(suspend { self.fa() })
}

@kotlin.jvm.JvmName("then_a")
inline infix fun FixtPfxTwoKap<(FixtPfxTwoA) -> kotlin.Int>.then(
    crossinline fa: suspend FixtPfxTwoASlot.() -> FixtPfxTwoA,
): Kap<kotlin.Int> {
    val self = this
    return self._kap.then(suspend { self.fa() })
}

@kotlin.jvm.JvmName("thenValue_a")
inline infix fun FixtPfxTwoKap<(FixtPfxTwoA) -> kotlin.Int>.thenValue(
    crossinline fa: suspend FixtPfxTwoASlot.() -> FixtPfxTwoA,
): Kap<kotlin.Int> {
    val self = this
    return self._kap.thenValue(suspend { self.fa() })
}

infix fun <A, B> FixtPfxTwoKap<(A) -> B>.with(fa: Kap<A>): FixtPfxTwoKap<B> =
    FixtPfxTwoKap(_kap.with(fa))

infix fun <A, B> FixtPfxTwoKap<(A) -> B>.then(fa: Kap<A>): FixtPfxTwoKap<B> =
    FixtPfxTwoKap(_kap.then(fa))

infix fun <A, B> FixtPfxTwoKap<(A) -> B>.thenValue(fa: Kap<A>): FixtPfxTwoKap<B> =
    FixtPfxTwoKap(_kap.thenValue(fa))

infix fun FixtPfxTwoKap<(FixtPfxTwoA) -> kotlin.Int>.with(fa: Kap<FixtPfxTwoA>): Kap<kotlin.Int> =
    _kap.with(fa)

infix fun FixtPfxTwoKap<(FixtPfxTwoA) -> kotlin.Int>.then(fa: Kap<FixtPfxTwoA>): Kap<kotlin.Int> =
    _kap.then(fa)

infix fun FixtPfxTwoKap<(FixtPfxTwoA) -> kotlin.Int>.thenValue(fa: Kap<FixtPfxTwoA>): Kap<kotlin.Int> =
    _kap.thenValue(fa)

inline infix fun <A, B> FixtPfxTwoKap<A>.andThen(
    crossinline f: (A) -> Kap<B>,
): Kap<B> = _kap.andThen(f)

suspend fun <A> FixtPfxTwoKap<A>.evalGraph(): A = _kap.evalGraph()


/** Official entry — `kap(::C)` plain, `kap<Double>(::C)` for generics. */
fun kap(f: (kotlin.String) -> kotlin.Int): FixtPfxTwoKap<(FixtPfxTwoA) -> kotlin.Int> =
    FixtPfxTwoKap(Kap.of({ p0: FixtPfxTwoA -> f(p0.value) }))


/** Extension property — enables `(::myFn).kap` and `kap((::myFn)::kap)` forms. */
val ((kotlin.String) -> kotlin.Int).kap: FixtPfxTwoKap<(FixtPfxTwoA) -> kotlin.Int>
    get() = FixtPfxTwoKap(Kap.of({ p0: FixtPfxTwoA -> this(p0.value) }))
