// AUTO-GENERATED by kap-ksp — do not edit
import kap.Kap
import kap.KapLike
import kap.of
import kap.with
import kap.then
import kap.thenValue
import kap.map
import kap.andThen
import kap.evalGraph

// ── Opaque wrappers — one per field ──

data class FixtPfxOneA(val value: kotlin.String)

// ── Tag classes (receivers for infix `from`) ──

class FixtPfxOneATag internal constructor()

// ── Infix `from` — wraps raw value or Kap<T> into the tagged wrapper ──

infix fun FixtPfxOneATag.from(value: kotlin.String): FixtPfxOneA = FixtPfxOneA(value)
infix fun FixtPfxOneATag.from(kap: Kap<kotlin.String>): Kap<FixtPfxOneA> = kap.map(::FixtPfxOneA)

// ── Per-slot interfaces (lambda receivers for `.with` / `.then`) ──

interface FixtPfxOneASlot { val a: FixtPfxOneATag }

/** Scoped builder for @KapTypeSafe FixtPfxOne. Implements every slot interface
 *  so each field is reachable as a member. The per-slot `.with` overloads
 *  below narrow the lambda receiver to a single tag — the IDE shows only the
 *  field expected at the current curry position when the body is empty.
 *
 *  The wrapper deliberately does NOT delegate to `Kap<F>`. If it did, the
 *  imported `Kap.with(suspend () -> A)` would compete with the slot-specific
 *  `.with { field from … }` and K2's overload resolution sometimes picks the
 *  generic one (before typechecking the lambda body), causing the slot's tag
 *  reference to fail with `Unresolved reference`.
 *
 *  The wrapper implements `KapLike<F>`, so kap-core operators (.map /
 *  .recover / .timeout / .settled / .memoize / .timed / .andThen /
 *  .evalGraph) are available directly on partial wrappers as well. For raw
 *  `Kap<F>` (e.g. an external API parameter), use `.asKap`.
 */
class FixtPfxOneKap<F>(@PublishedApi internal val _kap: Kap<F>) : KapLike<F>, FixtPfxOneASlot {
    override val asKap: Kap<F> get() = _kap
    override val a: FixtPfxOneATag = FixtPfxOneATag()

    companion object {
        val a: FixtPfxOneATag = FixtPfxOneATag()
    }
}

// ── Per-slot operators — IDE shows exactly the field expected at this position ──

@kotlin.jvm.JvmName("with_a")
inline infix fun FixtPfxOneKap<(FixtPfxOneA) -> kotlin.String>.with(
    crossinline fa: suspend FixtPfxOneASlot.() -> FixtPfxOneA,
): Kap<kotlin.String> {
    val self = this
    return self._kap.with(suspend { self.fa() })
}

@kotlin.jvm.JvmName("then_a")
inline infix fun FixtPfxOneKap<(FixtPfxOneA) -> kotlin.String>.then(
    crossinline fa: suspend FixtPfxOneASlot.() -> FixtPfxOneA,
): Kap<kotlin.String> {
    val self = this
    return self._kap.then(suspend { self.fa() })
}

@kotlin.jvm.JvmName("thenValue_a")
inline infix fun FixtPfxOneKap<(FixtPfxOneA) -> kotlin.String>.thenValue(
    crossinline fa: suspend FixtPfxOneASlot.() -> FixtPfxOneA,
): Kap<kotlin.String> {
    val self = this
    return self._kap.thenValue(suspend { self.fa() })
}

infix fun <A, B> FixtPfxOneKap<(A) -> B>.with(fa: Kap<A>): FixtPfxOneKap<B> =
    FixtPfxOneKap(_kap.with(fa))

infix fun <A, B> FixtPfxOneKap<(A) -> B>.then(fa: Kap<A>): FixtPfxOneKap<B> =
    FixtPfxOneKap(_kap.then(fa))

infix fun <A, B> FixtPfxOneKap<(A) -> B>.thenValue(fa: Kap<A>): FixtPfxOneKap<B> =
    FixtPfxOneKap(_kap.thenValue(fa))

infix fun FixtPfxOneKap<(FixtPfxOneA) -> kotlin.String>.with(fa: Kap<FixtPfxOneA>): Kap<kotlin.String> =
    _kap.with(fa)

infix fun FixtPfxOneKap<(FixtPfxOneA) -> kotlin.String>.then(fa: Kap<FixtPfxOneA>): Kap<kotlin.String> =
    _kap.then(fa)

infix fun FixtPfxOneKap<(FixtPfxOneA) -> kotlin.String>.thenValue(fa: Kap<FixtPfxOneA>): Kap<kotlin.String> =
    _kap.thenValue(fa)

inline infix fun <A, B> FixtPfxOneKap<A>.andThen(
    crossinline f: (A) -> Kap<B>,
): Kap<B> = _kap.andThen(f)

suspend fun <A> FixtPfxOneKap<A>.evalGraph(): A = _kap.evalGraph()


/** Official entry point — returns FixtPfxOneKap so `.with { field from value }` works without imports. */
fun kapFixtPfxOne(f: (kotlin.String) -> kotlin.String): FixtPfxOneKap<(FixtPfxOneA) -> kotlin.String> =
    FixtPfxOneKap(Kap.of({ p0: FixtPfxOneA -> f(p0.value) }))
