// AUTO-GENERATED by kap-ksp — do not edit
import arrow.core.Either
import arrow.core.NonEmptyList
import kap.Kap
import kap.KapLike
import kap.of
import kap.withV
import kap.thenV
import kap.thenValueV
import kap.evalGraph

// ── Validated infix `from` — maps Either<Nel<E>, FieldType> into tagged wrapper ──

infix fun <E> FixtPfxTwoATag.from(value: Either<NonEmptyList<E>, kotlin.String>): Either<NonEmptyList<E>, FixtPfxTwoA> =
    value.map(::FixtPfxTwoA)

/** Validated scoped builder for @KapTypeSafe FixtPfxTwo. Uses the same per-slot
 *  tag interfaces as FixtPfxTwoKap — each `.withV { field from validateField() }`
 *  narrows the receiver to one slot, accumulating errors via Arrow's applicative.
 */
class FixtPfxTwoValidatedKap<E, F>(@PublishedApi internal val _kap: Kap<Either<NonEmptyList<E>, F>>) : KapLike<Either<NonEmptyList<E>, F>>, FixtPfxTwoASlot {
    override val asKap: Kap<Either<NonEmptyList<E>, F>> get() = _kap
    override val a: FixtPfxTwoATag = FixtPfxTwoATag()

    companion object {
        val a: FixtPfxTwoATag = FixtPfxTwoATag()
    }
}

// ── Per-slot .withV / .thenV / .thenValueV operators ──

@kotlin.jvm.JvmName("withV_a")
inline infix fun <E> FixtPfxTwoValidatedKap<E, (FixtPfxTwoA) -> kotlin.Int>.withV(
    crossinline fa: suspend FixtPfxTwoASlot.() -> Either<NonEmptyList<E>, FixtPfxTwoA>,
): Kap<Either<NonEmptyList<E>, kotlin.Int>> {
    val self = this
    return self._kap.withV(Kap { self.fa() })
}

@kotlin.jvm.JvmName("thenV_a")
inline infix fun <E> FixtPfxTwoValidatedKap<E, (FixtPfxTwoA) -> kotlin.Int>.thenV(
    crossinline fa: suspend FixtPfxTwoASlot.() -> Either<NonEmptyList<E>, FixtPfxTwoA>,
): Kap<Either<NonEmptyList<E>, kotlin.Int>> {
    val self = this
    return self._kap.thenV(Kap { self.fa() })
}

@kotlin.jvm.JvmName("thenValueV_a")
inline infix fun <E> FixtPfxTwoValidatedKap<E, (FixtPfxTwoA) -> kotlin.Int>.thenValueV(
    crossinline fa: suspend FixtPfxTwoASlot.() -> Either<NonEmptyList<E>, FixtPfxTwoA>,
): Kap<Either<NonEmptyList<E>, kotlin.Int>> {
    val self = this
    return self._kap.thenValueV(Kap { self.fa() })
}

infix fun <E, A, B> FixtPfxTwoValidatedKap<E, (A) -> B>.withV(fa: Kap<Either<NonEmptyList<E>, A>>): FixtPfxTwoValidatedKap<E, B> =
    FixtPfxTwoValidatedKap(_kap.withV(fa))

infix fun <E, A, B> FixtPfxTwoValidatedKap<E, (A) -> B>.thenV(fa: Kap<Either<NonEmptyList<E>, A>>): FixtPfxTwoValidatedKap<E, B> =
    FixtPfxTwoValidatedKap(_kap.thenV(fa))

infix fun <E, A, B> FixtPfxTwoValidatedKap<E, (A) -> B>.thenValueV(fa: Kap<Either<NonEmptyList<E>, A>>): FixtPfxTwoValidatedKap<E, B> =
    FixtPfxTwoValidatedKap(_kap.thenValueV(fa))

infix fun <E> FixtPfxTwoValidatedKap<E, (FixtPfxTwoA) -> kotlin.Int>.withV(fa: Kap<Either<NonEmptyList<E>, FixtPfxTwoA>>): Kap<Either<NonEmptyList<E>, kotlin.Int>> =
    _kap.withV(fa)

infix fun <E> FixtPfxTwoValidatedKap<E, (FixtPfxTwoA) -> kotlin.Int>.thenV(fa: Kap<Either<NonEmptyList<E>, FixtPfxTwoA>>): Kap<Either<NonEmptyList<E>, kotlin.Int>> =
    _kap.thenV(fa)

infix fun <E> FixtPfxTwoValidatedKap<E, (FixtPfxTwoA) -> kotlin.Int>.thenValueV(fa: Kap<Either<NonEmptyList<E>, FixtPfxTwoA>>): Kap<Either<NonEmptyList<E>, kotlin.Int>> =
    _kap.thenValueV(fa)

suspend fun <E, A> FixtPfxTwoValidatedKap<E, A>.evalGraph(): Either<NonEmptyList<E>, A> = _kap.evalGraph()


/** Validated entry — `kapV(::C)` / `kapV<Double>(::C)` for generics. */
fun <E> kapV(f: (kotlin.String) -> kotlin.Int): FixtPfxTwoValidatedKap<E, (FixtPfxTwoA) -> kotlin.Int> {
    val fn: (FixtPfxTwoA) -> kotlin.Int = { p0: FixtPfxTwoA -> f(p0.value) }
    val kap: Kap<Either<NonEmptyList<E>, (FixtPfxTwoA) -> kotlin.Int>> = Kap.of(Either.Right(fn))
    return FixtPfxTwoValidatedKap(kap)
}

