// AUTO-GENERATED by kap-ksp — do not edit
import arrow.core.Either
import arrow.core.NonEmptyList
import kap.Kap
import kap.KapLike
import kap.of
import kap.withV
import kap.thenV
import kap.thenValueV
import kap.evalGraph

// ── Validated infix `from` — maps Either<Nel<E>, FieldType> into tagged wrapper ──

infix fun <E> FixtPfxOneATag.from(value: Either<NonEmptyList<E>, kotlin.String>): Either<NonEmptyList<E>, FixtPfxOneA> =
    value.map(::FixtPfxOneA)

/** Validated scoped builder for @KapTypeSafe FixtPfxOne. Uses the same per-slot
 *  tag interfaces as FixtPfxOneKap — each `.withV { field from validateField() }`
 *  narrows the receiver to one slot, accumulating errors via Arrow's applicative.
 */
class FixtPfxOneValidatedKap<E, F>(@PublishedApi internal val _kap: Kap<Either<NonEmptyList<E>, F>>) : KapLike<Either<NonEmptyList<E>, F>>, FixtPfxOneASlot {
    override val asKap: Kap<Either<NonEmptyList<E>, F>> get() = _kap
    override val a: FixtPfxOneATag = FixtPfxOneATag()

    companion object {
        val a: FixtPfxOneATag = FixtPfxOneATag()
    }
}

// ── Per-slot .withV / .thenV / .thenValueV operators ──

@kotlin.jvm.JvmName("withV_a")
inline infix fun <E> FixtPfxOneValidatedKap<E, (FixtPfxOneA) -> kotlin.String>.withV(
    crossinline fa: suspend FixtPfxOneASlot.() -> Either<NonEmptyList<E>, FixtPfxOneA>,
): Kap<Either<NonEmptyList<E>, kotlin.String>> {
    val self = this
    return self._kap.withV(Kap { self.fa() })
}

@kotlin.jvm.JvmName("thenV_a")
inline infix fun <E> FixtPfxOneValidatedKap<E, (FixtPfxOneA) -> kotlin.String>.thenV(
    crossinline fa: suspend FixtPfxOneASlot.() -> Either<NonEmptyList<E>, FixtPfxOneA>,
): Kap<Either<NonEmptyList<E>, kotlin.String>> {
    val self = this
    return self._kap.thenV(Kap { self.fa() })
}

@kotlin.jvm.JvmName("thenValueV_a")
inline infix fun <E> FixtPfxOneValidatedKap<E, (FixtPfxOneA) -> kotlin.String>.thenValueV(
    crossinline fa: suspend FixtPfxOneASlot.() -> Either<NonEmptyList<E>, FixtPfxOneA>,
): Kap<Either<NonEmptyList<E>, kotlin.String>> {
    val self = this
    return self._kap.thenValueV(Kap { self.fa() })
}

infix fun <E, A, B> FixtPfxOneValidatedKap<E, (A) -> B>.withV(fa: Kap<Either<NonEmptyList<E>, A>>): FixtPfxOneValidatedKap<E, B> =
    FixtPfxOneValidatedKap(_kap.withV(fa))

infix fun <E, A, B> FixtPfxOneValidatedKap<E, (A) -> B>.thenV(fa: Kap<Either<NonEmptyList<E>, A>>): FixtPfxOneValidatedKap<E, B> =
    FixtPfxOneValidatedKap(_kap.thenV(fa))

infix fun <E, A, B> FixtPfxOneValidatedKap<E, (A) -> B>.thenValueV(fa: Kap<Either<NonEmptyList<E>, A>>): FixtPfxOneValidatedKap<E, B> =
    FixtPfxOneValidatedKap(_kap.thenValueV(fa))

infix fun <E> FixtPfxOneValidatedKap<E, (FixtPfxOneA) -> kotlin.String>.withV(fa: Kap<Either<NonEmptyList<E>, FixtPfxOneA>>): Kap<Either<NonEmptyList<E>, kotlin.String>> =
    _kap.withV(fa)

infix fun <E> FixtPfxOneValidatedKap<E, (FixtPfxOneA) -> kotlin.String>.thenV(fa: Kap<Either<NonEmptyList<E>, FixtPfxOneA>>): Kap<Either<NonEmptyList<E>, kotlin.String>> =
    _kap.thenV(fa)

infix fun <E> FixtPfxOneValidatedKap<E, (FixtPfxOneA) -> kotlin.String>.thenValueV(fa: Kap<Either<NonEmptyList<E>, FixtPfxOneA>>): Kap<Either<NonEmptyList<E>, kotlin.String>> =
    _kap.thenValueV(fa)

suspend fun <E, A> FixtPfxOneValidatedKap<E, A>.evalGraph(): Either<NonEmptyList<E>, A> = _kap.evalGraph()


/** Validated entry — `kapV(::C)` / `kapV<Double>(::C)` for generics. */
fun <E> kapVFixtPfxOne(f: (kotlin.String) -> kotlin.String): FixtPfxOneValidatedKap<E, (FixtPfxOneA) -> kotlin.String> {
    val fn: (FixtPfxOneA) -> kotlin.String = { p0: FixtPfxOneA -> f(p0.value) }
    val kap: Kap<Either<NonEmptyList<E>, (FixtPfxOneA) -> kotlin.String>> = Kap.of(Either.Right(fn))
    return FixtPfxOneValidatedKap(kap)
}

