package kap.ksp

import kotlin.test.Test
import kotlin.test.assertTrue

/**
 * Unit tests for the PURE emission engine — hand-built specs, no KSP, no
 * compiler. The goldens (GoldenTest) pin the full pipeline end-to-end; these
 * pin the engine's decision rules in isolation.
 */
class KapEmitterTest {

    private fun spec(
        baseName: String = "Checkout",
        params: List<ParamInfo>,
        returnType: String,
        typeParams: List<TypeParamInfo> = emptyList(),
        callable: String = "Checkout",
        packageName: String = "",
    ) = BuilderSpec(
        baseName = baseName,
        packageName = packageName,
        params = params,
        returnType = returnType,
        typeParams = typeParams,
        callable = callable,
    )

    private val generic = spec(
        params = listOf(
            ParamInfo("user", "kotlin.String", isNullable = false),
            ParamInfo("total", "T", isNullable = false),
        ),
        returnType = "Checkout<T>",
        typeParams = listOf(TypeParamInfo("T", null)),
    )

    @Test
    fun `generic wrapper quantifies exactly its free variables`() {
        val out = KapBuilderEmitter.plainFile(generic, "kapCheckout", kapExtensionProperty = false)
        assertTrue("data class CheckoutUser(val value: kotlin.String)" in out, out)
        assertTrue("data class CheckoutTotal<T>(val value: T)" in out, out)
    }

    @Test
    fun `generic entry takes the callable and the zero-arg fallback is emitted`() {
        val out = KapBuilderEmitter.plainFile(generic, "kapCheckout", kapExtensionProperty = false)
        assertTrue(
            "fun <T> kapCheckout(f: (kotlin.String, T) -> Checkout<T>): " in out, out,
        )
        assertTrue("fun <T> kapCheckout(): CheckoutKap<" in out, out)
    }

    @Test
    fun `from is generic over the variables its field mentions`() {
        val out = KapBuilderEmitter.plainFile(generic, "kapCheckout", kapExtensionProperty = false)
        assertTrue(
            "infix fun <T> CheckoutTotalTag.from(value: T): CheckoutTotal<T>" in out, out,
        )
        assertTrue(
            "infix fun CheckoutUserTag.from(value: kotlin.String): CheckoutUser" in out, out,
        )
    }

    @Test
    fun `last-slot operator quantifies slot plus return type variables`() {
        val out = KapBuilderEmitter.plainFile(generic, "kapCheckout", kapExtensionProperty = false)
        assertTrue(
            "inline infix fun <T> CheckoutKap<(CheckoutTotal<T>) -> Checkout<T>>.with(" in out, out,
        )
    }

    @Test
    fun `bounds are preserved in every generalized declaration`() {
        val bounded = spec(
            baseName = "Box",
            params = listOf(ParamInfo("amount", "T", isNullable = false)),
            returnType = "Box<T>",
            typeParams = listOf(TypeParamInfo("T", "kotlin.Number")),
            callable = "Box",
        )
        val out = KapBuilderEmitter.plainFile(bounded, "kapBox", kapExtensionProperty = false)
        assertTrue("data class BoxAmount<T : kotlin.Number>(val value: T)" in out, out)
        assertTrue("fun <T : kotlin.Number> kapBox(" in out, out)
    }

    @Test
    fun `error binder is alpha-renamed on collision with a user type parameter`() {
        val colliding = spec(
            params = listOf(ParamInfo("payload", "E", isNullable = false)),
            returnType = "UsesE<E>",
            typeParams = listOf(TypeParamInfo("E", null)),
        )
        val out = KapBuilderEmitter.validatedFile(colliding, "kapVUsesE")
        assertTrue("<E_, " in out, "expected the generated error binder renamed to E_, got:\n$out")
        assertTrue("Kap<Either<NonEmptyList<E_>, " in out, out)
    }

    @Test
    fun `validated from overload maps Either with the error binder`() {
        val plain = spec(
            params = listOf(ParamInfo("user", "kotlin.String", isNullable = false)),
            returnType = "Checkout",
        )
        val out = KapBuilderEmitter.validatedFile(plain, "kapV")
        assertTrue(
            "infix fun <E> CheckoutUserTag.from(value: Either<NonEmptyList<E>, kotlin.String>)" in out,
            out,
        )
    }

    @Test
    fun `header carries the package and the auto-generated marker`() {
        val out = KapBuilderEmitter.plainFile(
            generic.copy(packageName = "com.acme"),
            "kapCheckout",
            kapExtensionProperty = false,
        )
        assertTrue(out.startsWith("// AUTO-GENERATED by kap-ksp"), out)
        assertTrue("package com.acme" in out, out)
    }

    @Test
    fun `extension property only for unique-signature functions`() {
        val with = KapBuilderEmitter.plainFile(generic, "kapCheckout", kapExtensionProperty = true)
        assertTrue(").kap: CheckoutKap<" in with, with)
        val without = KapBuilderEmitter.plainFile(generic, "kapCheckout", kapExtensionProperty = false)
        assertTrue(").kap: CheckoutKap<" !in without, without)
    }
}
